/*
 * asynchronousByzantineAgreementProtocols - Example Bracha87 Fig 4 program
 * Copyright (C) 2026 G. David Butler <gdb@dbSystems.com>
 *
 * This file is part of asynchronousByzantineAgreementProtocols
 *
 * asynchronousByzantineAgreementProtocols is free software: you can
 * redistribute it and/or modify it under the terms of the GNU Lesser General
 * Public License as published by the Free Software Foundation, either
 * version 3 of the License, or (at your option) any later version.
 *
 * asynchronousByzantineAgreementProtocols is distributed in the hope
 * that it will be useful, but WITHOUT ANY WARRANTY; without even the implied
 * warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Lesser General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public License
 * along with this program.  If not, see <https://www.gnu.org/licenses/>.
 */

/*
 * bracha87Fig4.c — Standalone demonstration of Bracha 1987 Figure 4:
 * Binary Byzantine agreement (Theorem 2).
 *
 * What Figure 4 brings to the table: given Fig 3's validated round
 * messages, all correct peers decide on the same bit despite up to t
 * Byzantine peers and arbitrary asynchrony.  Decision is binary by
 * construction (initialValue is 0 or 1; the coin breaks ties at step
 * 3 case (iii)).  Multi-byte agreement is the bkr94acs layer.
 *
 * The Fig 4 round messages are reliably broadcast via Fig 1 — that
 * is the composition the paper specifies, and the Fig 1 layer is
 * present here as the natural delivery primitive, not as an add-on:
 *
 *   message -> Fig1(n,t) -> accept -> Fig3(N) -> round complete
 *           -> Fig4(coin) -> decision
 *
 * The high-level bracha87Fig4Input entry point drives this entire
 * cascade in a single call: Fig 1 Input + Fig 3 Accept on ACCEPT +
 * round-completion scan + Fig 4 Round on each completion +
 * origination of the next round's Fig 1 broadcast.  Acts surfaced
 * to the application are (origin, round, type, value) for
 * broadcast actions plus DECIDE / EXHAUSTED for terminal events.
 *
 * Each process maintains:
 *   - One Fig 1 instance per (origin, round) for reliable broadcast
 *   - One Fig 4 instance (which embeds Fig 3) for consensus
 *
 * Messages are queued in a simulated all-to-all network.  Optional
 * Fisher-Yates shuffling demonstrates asynchrony tolerance.
 *
 * Scope: this demo runs in a single process with a synchronous
 * deterministic in-memory queue — every input is delivered, no
 * loss, no reordering.  It exercises the protocol state machines
 * but does NOT exercise BPR replay under loss or the
 * deployment-time termination policies (silence-quorum + K-sweep
 * gate) needed under real asynchronous transport.  See README.md
 * "Architecture", "Caller Composition Pattern", and "Termination
 * policy" for the design.
 *
 * Build:
 *   (from project root) make example_bracha87Fig4
 *
 * Usage:
 *   ./example_bracha87Fig4 [-v] [-s seed] [-b split] n t [init_values...]
 */

#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include "bracha87.h"

/*------------------------------------------------------------------------*/
/*  Constants                                                             */
/*------------------------------------------------------------------------*/

#define MAX_PEERS 16
#define MAX_PHASES 10

/*------------------------------------------------------------------------*/
/*  Message queue — simulated network                                     */
/*                                                                        */
/*  Dynamically allocated to accommodate the O(n^2 * rounds) messages     */
/*  generated by the all-to-all broadcast protocol.                       */
/*------------------------------------------------------------------------*/

struct msg {
  unsigned char round;
  unsigned char type;    /* BRACHA87_INITIAL, BRACHA87_ECHO, BRACHA87_READY */
  unsigned char from;
  unsigned char to;
  unsigned char origin;  /* which peer's broadcast instance */
  unsigned char value;
};

static struct msg *MsgQ;
static unsigned int Qcap;
static unsigned int Qhead;
static unsigned int Qtail;

static int
qAlloc(
  unsigned int cap
){
  MsgQ = (struct msg *)calloc(cap, sizeof (struct msg));
  if (!MsgQ)
    return (-1);
  Qcap = cap;
  Qhead = Qtail = 0;
  return (0);
}

static void
qFree(
  void
){
  free(MsgQ);
  MsgQ = 0;
}

static void
qPush(
  unsigned char round
 ,unsigned char type
 ,unsigned char from
 ,unsigned char to
 ,unsigned char origin
 ,unsigned char value
){
  if (Qtail >= Qcap)
    return;
  MsgQ[Qtail].round = round;
  MsgQ[Qtail].type = type;
  MsgQ[Qtail].from = from;
  MsgQ[Qtail].to = to;
  MsgQ[Qtail].origin = origin;
  MsgQ[Qtail].value = value;
  ++Qtail;
}

/*
 * Fisher-Yates shuffle of the unprocessed portion of the queue.
 * LCG produces repeatable sequences from a given seed.
 */
static void
qShuffle(
  unsigned int *seed
){
  unsigned int n;
  unsigned int i;

  n = Qtail - Qhead;
  if (n < 2)
    return;
  for (i = n - 1; i > 0; --i) {
    unsigned int j;
    struct msg tmp;

    *seed = *seed * 1103515245u + 12345u;
    j = ((*seed >> 16) & 0x7FFF) % (i + 1);
    tmp = MsgQ[Qhead + i];
    MsgQ[Qhead + i] = MsgQ[Qhead + j];
    MsgQ[Qhead + j] = tmp;
  }
}

/*------------------------------------------------------------------------*/
/*  Coin — deterministic alternating, adequate for demonstration only.    */
/*------------------------------------------------------------------------*/

static unsigned char
coin(
  void *closure
 ,unsigned char phase
){
  (void)closure;
  return (phase % 2);
}

/*------------------------------------------------------------------------*/
/*  Per-process state                                                     */
/*------------------------------------------------------------------------*/

struct peerState {
  struct bracha87Fig1 **fig1;  /* [maxRounds * n] instances */
  struct bracha87Fig4 *fig4;
  struct bracha87Fig3 *fig3;   /* &fig4->fig3 */
  unsigned char nextRound;     /* next round to check for completion */
};

/*------------------------------------------------------------------------*/
/*  Verbose message names                                                 */
/*------------------------------------------------------------------------*/

static const char *
typeName(
  unsigned char type
){
  switch (type) {
  case BRACHA87_INITIAL: return ("INITIAL");
  case BRACHA87_ECHO:    return ("ECHO");
  case BRACHA87_READY:   return ("READY");
  default:               return ("???");
  }
}

/*------------------------------------------------------------------------*/
/*  Main simulation                                                       */
/*------------------------------------------------------------------------*/

int
main(
  int argc
 ,char *argv[]
){
  /* Configuration */
  unsigned int n;
  unsigned int t;
  unsigned char initVals[MAX_PEERS];
  unsigned int verbose;
  unsigned int shuffleSeed;
  unsigned int origSeed;
  unsigned int byzSplit;

  /* Per-process state */
  struct peerState peers[MAX_PEERS];
  unsigned char decisions[MAX_PEERS];
  /*
   * Per-peer exhaustion flag.  Bracha87 Fig4 has no built-in sentinel
   * for "exhausted" -- the application observes BRACHA87_EXHAUSTED in
   * the action stream and tracks it itself.  This is the pattern users
   * copying the example should learn.
   */
  unsigned char exhausted[MAX_PEERS];
  unsigned int  exhaustedCount;

  /* Derived */
  unsigned int maxRounds;
  unsigned long f1sz;

  /* Loop / temp */
  unsigned int i;
  unsigned int j;
  unsigned int r;
  int arg;
  int exitCode;

  /* Verification state */
  unsigned int decided;
  unsigned char firstDec;
  int lemma1ok;
  int lemma2ok;
  int thm2ok;
  int step1ok;

  /*----------------------------------------------------------------------*/
  /*  Parse command line                                                   */
  /*----------------------------------------------------------------------*/

  verbose = 0;
  shuffleSeed = 0;
  byzSplit = 0;
  exitCode = 0;

  arg = 1;
  while (arg < argc && argv[arg][0] == '-') {
    if (argv[arg][1] == 'v' && argv[arg][2] == '\0') {
      verbose = 1;
      ++arg;
    } else if (argv[arg][1] == 's' && argv[arg][2] == '\0') {
      ++arg;
      if (arg >= argc) goto usage;
      shuffleSeed = (unsigned int)atoi(argv[arg]);
      ++arg;
    } else if (argv[arg][1] == 'b' && argv[arg][2] == '\0') {
      ++arg;
      if (arg >= argc) goto usage;
      byzSplit = (unsigned int)atoi(argv[arg]);
      ++arg;
    } else {
      goto usage;
    }
  }

  if (argc - arg < 2) goto usage;
  n = (unsigned int)atoi(argv[arg++]);
  t = (unsigned int)atoi(argv[arg++]);

  if (n < 1 || n > MAX_PEERS) {
    fprintf(stderr, "n must be 1..%d\n", MAX_PEERS);
    return (1);
  }
  if (n <= 3 * t) {
    fprintf(stderr, "need n > 3t (n=%u, t=%u)\n", n, t);
    return (1);
  }
  if (byzSplit > n) {
    fprintf(stderr, "split must be <= n\n");
    return (1);
  }

  origSeed = shuffleSeed;

  /* Initial values: defaults to all 0 */
  memset(initVals, 0, sizeof (initVals));
  for (i = 0; arg < argc && i < n; ++i, ++arg)
    initVals[i] = (unsigned char)(atoi(argv[arg]) ? 1 : 0);

  /*----------------------------------------------------------------------*/
  /*  Allocate per-process state                                          */
  /*----------------------------------------------------------------------*/

  maxRounds = (unsigned int)MAX_PHASES * BRACHA87_ROUNDS_PER_PHASE;
  f1sz = bracha87Fig1Sz(n - 1, 0);  /* n-1 is the encoded n; vLen=0 => 1 byte */

  memset(peers, 0, sizeof (peers));
  memset(decisions, 0xFF, sizeof (decisions));
  memset(exhausted, 0, sizeof (exhausted));
  exhaustedCount = 0;

  for (i = 0; i < n; ++i) {
    /* Byzantine peer 0 when byzSplit is set: skip state allocation */
    if (byzSplit && i == 0)
      continue;

    peers[i].fig1 = (struct bracha87Fig1 **)calloc(
      maxRounds * n, sizeof (struct bracha87Fig1 *));
    peers[i].fig4 = (struct bracha87Fig4 *)calloc(
      1, bracha87Fig4Sz(n - 1, MAX_PHASES));
    if (!peers[i].fig1 || !peers[i].fig4) {
      fprintf(stderr, "allocation failed\n");
      exitCode = 1;
      goto cleanup;
    }

    for (j = 0; j < maxRounds * n; ++j) {
      peers[i].fig1[j] = (struct bracha87Fig1 *)calloc(1, f1sz);
      if (!peers[i].fig1[j]) {
        fprintf(stderr, "allocation failed\n");
        exitCode = 1;
        goto cleanup;
      }
      bracha87Fig1Init(peers[i].fig1[j], (unsigned char)(n - 1),
                       (unsigned char)t, 0);
    }

    bracha87Fig4Init(peers[i].fig4, (unsigned char)(n - 1),
                     (unsigned char)t, MAX_PHASES, initVals[i], coin, 0);
    peers[i].fig3 = &peers[i].fig4->fig3;
    peers[i].nextRound = 0;
  }

  /*----------------------------------------------------------------------*/
  /*  Allocate message queue                                              */
  /*  Each round can produce up to 3*n^2 messages (INITIAL, ECHO, READY  */
  /*  from n origins to n peers). Budget 4*n^2 per round for headroom.   */
  /*----------------------------------------------------------------------*/

  if (qAlloc(16u * n * n * maxRounds)) {
    fprintf(stderr, "queue allocation failed\n");
    exitCode = 1;
    goto cleanup;
  }

  /*----------------------------------------------------------------------*/
  /*  Bootstrap: each correct peer self-initiates round 0 via Fig4Start.  */
  /*  Byzantine peer 0 (when -b is set) bypasses the library and pushes   */
  /*  equivocating INITIALs directly.                                     */
  /*----------------------------------------------------------------------*/
  for (i = 0; i < n; ++i) {
    struct bracha87Fig4Act sact;
    unsigned int ns;

    if (byzSplit && i == 0) {
      /* Byzantine equivocation: peer 0 sends different values */
      for (j = 0; j < n; ++j)
        qPush(0, BRACHA87_INITIAL, 0, (unsigned char)j, 0,
              (j < byzSplit) ? 0 : 1);
      continue;
    }

    ns = bracha87Fig4Start(peers[i].fig4, peers[i].fig1,
                           (unsigned char)i, &sact, 1);
    if (ns == 1) {
      for (j = 0; j < n; ++j)
        qPush(sact.round, sact.type, (unsigned char)i,
              (unsigned char)j, sact.origin, sact.value);
    }
  }
  if (shuffleSeed)
    qShuffle(&shuffleSeed);

  /*----------------------------------------------------------------------*/
  /*  Process message queue                                               */
  /*                                                                      */
  /*  bracha87Fig4Input drives Fig 1 ladder + Fig 3 validation cascade +  */
  /*  Fig 4 round-completion + next-round origination in a single call.   */
  /*  The application's job is to broadcast the emitted *_ALL acts and    */
  /*  record DECIDE / EXHAUSTED outcomes.                                 */
  /*----------------------------------------------------------------------*/

  step1ok = 1;

  while (Qhead < Qtail) {
    struct msg *m;
    struct bracha87Fig4Act acts[BRACHA87_FIG4_MAX_ACTS];
    unsigned int nacts;
    unsigned int k;
    unsigned int oldTail;

    m = &MsgQ[Qhead++];

    /* Skip messages to Byzantine peer */
    if (byzSplit && m->to == 0)
      continue;
    if (m->round >= maxRounds || m->origin >= n || m->from >= n)
      continue;

    oldTail = Qtail;

    if (verbose)
      printf("peer %u: recv %s(round=%u, origin=%u, value=%u) from %u\n",
             (unsigned)m->to, typeName(m->type),
             (unsigned)m->round, (unsigned)m->origin,
             (unsigned)(m->value & 1), (unsigned)m->from);

    nacts = bracha87Fig4Input(peers[m->to].fig4, peers[m->to].fig1,
                              m->to, m->round, m->origin,
                              m->type, m->from, m->value,
                              acts, BRACHA87_FIG4_MAX_ACTS);

    for (k = 0; k < nacts; ++k) {
      switch (acts[k].act) {
      case BRACHA87_INITIAL_ALL:
      case BRACHA87_ECHO_ALL:
      case BRACHA87_READY_ALL:
        /* Verify step 1 broadcasts (sub-round 0 of any phase) never
         * carry D_FLAG — a Byzantine peer flagging a step-1 INITIAL
         * would corrupt the value distinction the protocol relies on. */
        if (acts[k].act == BRACHA87_INITIAL_ALL
         && acts[k].round % 3 == 0
         && (acts[k].value & BRACHA87_D_FLAG))
          step1ok = 0;

        if (verbose) {
          const char *name;
          name = (acts[k].act == BRACHA87_INITIAL_ALL) ? "INITIAL_ALL"
               : (acts[k].act == BRACHA87_ECHO_ALL)    ? "ECHO_ALL"
               :                                          "READY_ALL";
          printf("peer %u: -> %s(round=%u, origin=%u, value=%u)\n",
                 (unsigned)m->to, name,
                 (unsigned)acts[k].round, (unsigned)acts[k].origin,
                 (unsigned)(acts[k].value & 1));
        }

        for (j = 0; j < n; ++j)
          qPush(acts[k].round, acts[k].type, m->to,
                (unsigned char)j, acts[k].origin, acts[k].value);
        break;

      case BRACHA87_FIG4_DECIDE:
        decisions[m->to] = acts[k].decision;
        if (verbose)
          printf("peer %u: Fig4 round %u -> DECIDE value=%u\n",
                 (unsigned)m->to, (unsigned)acts[k].round,
                 (unsigned)acts[k].decision);
        break;

      case BRACHA87_FIG4_EXHAUSTED:
        /* Not verbose-gated: fatal protocol event. */
        if (!exhausted[m->to])
          ++exhaustedCount;
        exhausted[m->to] = 1;
        printf("peer %u: EXHAUSTED -- no decision in %u phases\n",
               (unsigned)m->to, (unsigned)MAX_PHASES);
        break;
      }
    }

    if (shuffleSeed && Qtail > oldTail)
      qShuffle(&shuffleSeed);
  }

  /*----------------------------------------------------------------------*/
  /*  Pump tick                                                           */
  /*                                                                      */
  /*  In a real deployment, the BPR pump is called once per tick.         */
  /*  Looping until idle would flood the network — see bracha87.h's       */
  /*  flood warning.  The call is shown here as a representative tick.    */
  /*----------------------------------------------------------------------*/

  for (i = 0; i < n; ++i) {
    struct bracha87Pump pump;
    struct bracha87Fig4Act pacts[BRACHA87_FIG4_MAX_ACTS];
    unsigned int n_pacts;
    unsigned int p;

    if (byzSplit && i == 0) continue;
    bracha87PumpInit(&pump);
    n_pacts = bracha87Fig4Pump(peers[i].fig4, peers[i].fig1,
                               &pump, pacts, BRACHA87_FIG4_MAX_ACTS);
    for (p = 0; p < n_pacts; ++p)
      for (j = 0; j < n; ++j)
        qPush(pacts[p].round, pacts[p].type, (unsigned char)i,
              (unsigned char)j, pacts[p].origin, pacts[p].value);
  }

  /*----------------------------------------------------------------------*/
  /*  Drain the post-pump replay queue.  Receivers dedup at Fig1Input,    */
  /*  so under perfect delivery these replays produce no new state.       */
  /*----------------------------------------------------------------------*/

  while (Qhead < Qtail) {
    struct msg *m;
    struct bracha87Fig4Act dacts[BRACHA87_FIG4_MAX_ACTS];

    m = &MsgQ[Qhead++];
    if (byzSplit && m->to == 0) continue;
    if (m->round >= maxRounds || m->origin >= n || m->from >= n) continue;
    bracha87Fig4Input(peers[m->to].fig4, peers[m->to].fig1,
                      m->to, m->round, m->origin,
                      m->type, m->from, m->value,
                      dacts, BRACHA87_FIG4_MAX_ACTS);
    /* Replay-induced acts are duplicates that dedup at Fig1Input;
     * the caller already received them via the main loop.  Discarded
     * here. */
  }

  /*----------------------------------------------------------------------*/
  /*  Post-simulation verification                                        */
  /*----------------------------------------------------------------------*/

  /* Lemma 1: all honest readys agree per (origin, round) */
  lemma1ok = 1;
  for (r = 0; r < maxRounds; ++r) {
    unsigned int orig;

    for (orig = 0; orig < n; ++orig) {
      unsigned char rdVal;
      int rdSeen;

      rdVal = 0;
      rdSeen = 0;
      for (i = 0; i < n; ++i) {
        struct bracha87Fig1 *fi;
        const unsigned char *rv;

        if (byzSplit && i == 0)
          continue;
        fi = peers[i].fig1[r * n + orig];
        if ((fi->flags & BRACHA87_F1_RDSENT)) {
          rv = bracha87Fig1Value(fi);
          if (rv) {
            if (!rdSeen) {
              rdVal = rv[0];
              rdSeen = 1;
            } else if (rv[0] != rdVal) {
              lemma1ok = 0;
            }
          }
        }
      }
    }
  }

  /* Lemma 2: all honest accepts agree per (origin, round) */
  lemma2ok = 1;
  for (r = 0; r < maxRounds; ++r) {
    unsigned int orig;

    for (orig = 0; orig < n; ++orig) {
      unsigned char acVal;
      int acSeen;

      acVal = 0;
      acSeen = 0;
      for (i = 0; i < n; ++i) {
        struct bracha87Fig1 *fi;
        const unsigned char *av;

        if (byzSplit && i == 0)
          continue;
        fi = peers[i].fig1[r * n + orig];
        if ((fi->flags & BRACHA87_F1_ACCEPTED)) {
          av = bracha87Fig1Value(fi);
          if (av) {
            if (!acSeen) {
              acVal = av[0];
              acSeen = 1;
            } else if (av[0] != acVal) {
              lemma2ok = 0;
            }
          }
        }
      }
    }
  }

  /* Theorem 2: all honest decisions agree */
  decided = 0;
  firstDec = 0xFF;
  thm2ok = 1;
  for (i = 0; i < n; ++i) {
    if (byzSplit && i == 0)
      continue;
    if (decisions[i] != 0xFF) {
      if (firstDec == 0xFF)
        firstDec = decisions[i];
      else if (decisions[i] != firstDec)
        thm2ok = 0;
      ++decided;
    }
  }

  /*----------------------------------------------------------------------*/
  /*  Output summary                                                      */
  /*----------------------------------------------------------------------*/

  printf("\n--- Results (n=%u, t=%u, seed=%u) ---\n", n, t, origSeed);
  for (i = 0; i < n; ++i) {
    if (byzSplit && i == 0) {
      printf("Peer %u: Byzantine (equivocating, split=%u)\n", i, byzSplit);
    } else if (decisions[i] == 0xFF) {
      /*
       * Distinguish exhaustion (Fig4 ran to BRACHA87_MAX_PHASES with
       * no decision -- protocol failure) from no-decision-yet (Fig4
       * still in progress when the queue drained -- simulator
       * artifact, shouldn't happen here since the queue drains
       * deterministically).  Conflating them would teach users to
       * miss real protocol failures.
       */
      if (exhausted[i])
        printf("Peer %u: EXHAUSTED (no decision in %u phases)\n",
               i, (unsigned)MAX_PHASES);
      else
        printf("Peer %u: no decision\n", i);
    } else {
      printf("Peer %u: decided %u\n", i, (unsigned)decisions[i]);
    }
  }
  printf("Lemma 1 (honest readys agree): %s\n", lemma1ok ? "ok" : "FAIL");
  printf("Lemma 2 (honest accepts agree): %s\n", lemma2ok ? "ok" : "FAIL");
  printf("Theorem 2 (decisions agree): %s\n",
         (decided > 1) ? (thm2ok ? "ok" : "FAIL")
                       : "n/a (fewer than 2 decisions)");
  printf("Step 1 no D_FLAG: %s\n", step1ok ? "ok" : "FAIL");
  if (exhaustedCount)
    printf("Exhaustion: %u honest peer(s) failed to terminate\n",
           exhaustedCount);

  if (!lemma1ok || !lemma2ok || !thm2ok || !step1ok || exhaustedCount)
    exitCode = 1;

  /*----------------------------------------------------------------------*/
  /*  Cleanup                                                             */
  /*----------------------------------------------------------------------*/

cleanup:
  for (i = 0; i < n; ++i) {
    if (peers[i].fig1) {
      for (j = 0; j < maxRounds * n; ++j)
        free(peers[i].fig1[j]);
      free(peers[i].fig1);
    }
    free(peers[i].fig4);
  }
  qFree();

  return (exitCode);

usage:
  fprintf(stderr,
    "usage: example_bracha87Fig4 [-v] [-s seed] [-b split] n t [init_values...]\n"
    "  n          total peers (1-%d)\n"
    "  t          max Byzantine faults\n"
    "  init_values  per-peer initial values (0 or 1), defaults to all 0\n"
    "  -v         verbose: trace every message\n"
    "  -s seed    shuffle seed (0 = ordered delivery)\n"
    "  -b split   Byzantine peer 0 equivocates: sends 0 to [0..split-1],"
    " 1 to [split..n-1]\n",
    MAX_PEERS);
  return (1);
}
