/* Generated by psu.awk from bkr94acs.psu -- dispatch depth 11. */
/* Edit the .dtc and regenerate; changes here are overwritten. */
  if (enabled == 0)
    goto L2;
  /* "enabled" = yes */
  if (postCountAllN == 0)
    goto L5;
  /* "post-output BA-output count == n" = yes */
  if (nothingLeft == 0)
    goto L8;
  /* "duty" = MET */
  /* "nothing left to wait for" = yes */
  duty = BKR94ACS_DUTY_MET;
  if (seam == BKR94ACS_SEAM_TURN)
    goto L11;
  /* "fire on call" = no */
  /* "seam" = fanout */
  fire = 0;
L13:;
  if (acsEvent == BKR94ACS_ACS_EVENT_BA0)
    goto L14;
  if (acsEvent == BKR94ACS_ACS_EVENT_BA1)
    goto L17;
  /* "kind of ACS event" = Q(j) = 1 */
  /* "output SubSet" = no */
  doOutputSubset = 0;
L19:;
  if (inputToBAj == BKR94ACS_ENTER_NONE)
    goto L20;
  /* "input 1 to BA_j" = no */
  doInput1 = 0;
L22:;
  if (inputToBAj == BKR94ACS_ENTER_ONE)
    goto L23;
  /* "input to BA_j" = 0 */
L25:;
  if (baDecision == 0)
    goto L26;
  /* "walk A-Cast j" = yes */
  walk = 1;
  if (baDecision == 0xFE)
    goto L29;
  if (baDecision == 0xFF)
    goto L32;
  /* "BA_j decision" = decided 1 */
  goto Ldone;
L32:;
  /* "BA_j decision" = undecided */
  goto Ldone;
L29:;
  /* "BA_j decision" = exhausted */
  goto Ldone;
L26:;
  /* "BA_j decision" = decided 0 */
  /* "walk A-Cast j" = no */
  walk = 0;
  goto Ldone;
L23:;
  /* "input to BA_j" = 1 */
  goto L25;
L20:;
  /* "input 1 to BA_j" = yes */
  /* "input to BA_j" = none */
  doInput1 = 1;
  goto L25;
L17:;
  /* "input 1 to BA_j" = no */
  /* "kind of ACS event" = BA_j outputs 1 */
  /* "output SubSet" = yes */
  doInput1 = 0;
  doOutputSubset = 1;
L34:;
  if (inputToBAj == BKR94ACS_ENTER_NONE)
    goto L35;
  goto L22;
L35:;
  /* "input to BA_j" = none */
  goto L25;
L14:;
  /* "input 1 to BA_j" = no */
  /* "kind of ACS event" = BA_j outputs 0 */
  /* "output SubSet" = yes */
  doInput1 = 0;
  doOutputSubset = 1;
  goto L34;
L11:;
  /* "fire on call" = yes */
  /* "seam" = turn */
  fire = 1;
  goto L13;
L8:;
  /* "duty" = TOLERANCE */
  /* "fire on call" = yes */
  /* "nothing left to wait for" = no */
  duty = BKR94ACS_DUTY_TOLERANCE;
  fire = 1;
L37:;
  if (seam == BKR94ACS_SEAM_TURN)
    goto L38;
  /* "seam" = fanout */
  goto L13;
L38:;
  /* "seam" = turn */
  goto L13;
L5:;
  /* "output SubSet" = no */
  /* "post-output BA-output count == n" = no */
  doOutputSubset = 0;
  if (nothingLeft == 0)
    goto L41;
  /* "duty" = MET */
  /* "nothing left to wait for" = yes */
  duty = BKR94ACS_DUTY_MET;
  if (seam == BKR94ACS_SEAM_TURN)
    goto L44;
  /* "fire on call" = no */
  /* "seam" = fanout */
  fire = 0;
L46:;
  if (acsEvent == BKR94ACS_ACS_EVENT_BA0)
    goto L47;
  if (acsEvent == BKR94ACS_ACS_EVENT_BA1)
    goto L50;
  /* "kind of ACS event" = Q(j) = 1 */
  goto L19;
L50:;
  /* "input 1 to BA_j" = no */
  /* "kind of ACS event" = BA_j outputs 1 */
  doInput1 = 0;
  goto L34;
L47:;
  /* "input 1 to BA_j" = no */
  /* "kind of ACS event" = BA_j outputs 0 */
  doInput1 = 0;
  goto L34;
L44:;
  /* "fire on call" = yes */
  /* "seam" = turn */
  fire = 1;
  goto L46;
L41:;
  /* "duty" = TOLERANCE */
  /* "fire on call" = yes */
  /* "nothing left to wait for" = no */
  duty = BKR94ACS_DUTY_TOLERANCE;
  fire = 1;
L52:;
  if (seam == BKR94ACS_SEAM_TURN)
    goto L53;
  /* "seam" = fanout */
  goto L46;
L53:;
  /* "seam" = turn */
  goto L46;
L2:;
  /* "enabled" = no */
  /* "fire on call" = no */
  fire = 0;
  if (postCountAllN == 0)
    goto L56;
  /* "post-output BA-output count == n" = yes */
  if (nothingLeft == 0)
    goto L59;
  /* "nothing left to wait for" = yes */
  if (seam == BKR94ACS_SEAM_TURN)
    goto L62;
  /* "duty" = MET */
  /* "seam" = fanout */
  duty = BKR94ACS_DUTY_MET;
  goto L13;
L62:;
  /* "duty" = HELD */
  /* "seam" = turn */
  duty = BKR94ACS_DUTY_HELD;
  goto L13;
L59:;
  /* "duty" = HELD */
  /* "nothing left to wait for" = no */
  duty = BKR94ACS_DUTY_HELD;
  goto L37;
L56:;
  /* "output SubSet" = no */
  /* "post-output BA-output count == n" = no */
  doOutputSubset = 0;
  if (nothingLeft == 0)
    goto L65;
  /* "nothing left to wait for" = yes */
  if (seam == BKR94ACS_SEAM_TURN)
    goto L68;
  /* "duty" = MET */
  /* "seam" = fanout */
  duty = BKR94ACS_DUTY_MET;
  goto L46;
L68:;
  /* "duty" = HELD */
  /* "seam" = turn */
  duty = BKR94ACS_DUTY_HELD;
  goto L46;
L65:;
  /* "duty" = HELD */
  /* "nothing left to wait for" = no */
  duty = BKR94ACS_DUTY_HELD;
  goto L52;
Ldone:;
