/* Generated by psu.awk from bkr94acs.psu -- dispatch depth 5. */
/* Edit the .dtc and regenerate; changes here are overwritten. */
  if (postCountAllN == 0)
    goto L2;
  /* "post-output BA-output count == n" = yes */
  if (acsEvent == BKR94ACS_ACS_EVENT_BA0)
    goto L5;
  if (acsEvent == BKR94ACS_ACS_EVENT_BA1)
    goto L8;
  /* "kind of ACS event" = Q(j) = 1 */
  /* "output SubSet" = no */
  doOutputSubset = 0;
L10:;
  if (inputToBAj == BKR94ACS_ENTER_NONE)
    goto L11;
  /* "input 1 to BA_j" = no */
  doInput1 = 0;
L13:;
  if (inputToBAj == BKR94ACS_ENTER_ONE)
    goto L14;
  /* "input to BA_j" = 0 */
  goto Ldone;
L14:;
  /* "input to BA_j" = 1 */
  goto Ldone;
L11:;
  /* "input 1 to BA_j" = yes */
  /* "input to BA_j" = none */
  doInput1 = 1;
  goto Ldone;
L8:;
  /* "input 1 to BA_j" = no */
  /* "kind of ACS event" = BA_j outputs 1 */
  /* "output SubSet" = yes */
  doInput1 = 0;
  doOutputSubset = 1;
L16:;
  if (inputToBAj == BKR94ACS_ENTER_NONE)
    goto L17;
  goto L13;
L17:;
  /* "input to BA_j" = none */
  goto Ldone;
L5:;
  /* "input 1 to BA_j" = no */
  /* "kind of ACS event" = BA_j outputs 0 */
  /* "output SubSet" = yes */
  doInput1 = 0;
  doOutputSubset = 1;
  goto L16;
L2:;
  /* "output SubSet" = no */
  /* "post-output BA-output count == n" = no */
  doOutputSubset = 0;
  if (acsEvent == BKR94ACS_ACS_EVENT_BA0)
    goto L20;
  if (acsEvent == BKR94ACS_ACS_EVENT_BA1)
    goto L23;
  /* "kind of ACS event" = Q(j) = 1 */
  goto L10;
L23:;
  /* "input 1 to BA_j" = no */
  /* "kind of ACS event" = BA_j outputs 1 */
  doInput1 = 0;
  goto L16;
L20:;
  /* "input 1 to BA_j" = no */
  /* "kind of ACS event" = BA_j outputs 0 */
  doInput1 = 0;
  goto L16;
Ldone:;
