/* Generated by psu.awk from bracha87Fig1.psu -- dispatch depth 14. */
/* Edit the .dtc and regenerate; changes here are overwritten. */
  if (allEchoed == 0)
    goto L2;
  /* "all echoed" = yes */
  /* "retry (initial, v)" = no */
  retryInitial = 0;
  if (amInitiator == 0)
    goto L5;
  /* "am initiator" = yes */
L7:;
  if (annAccepted == 0)
    goto L8;
  /* "carries ACCEPTED" = yes */
  if (annReceived == 0)
    goto L11;
  /* "arm re-send to sender" = no */
  /* "carries RECEIVED" = yes */
  armSender = 0;
  if (ecGtHalfNT == 0)
    goto L14;
  /* "echo-count(v) > (n+t)/2" = yes */
  if (haveAccepted == 0)
    goto L17;
  /* "accept(v)" = no */
  /* "have accepted" = yes */
  /* "retry (echo, v)" = no */
  acceptV = 0;
  retryEcho = 0;
L19:;
  if (haveEchoed == 0)
    goto L20;
  /* "have echoed" = yes */
  /* "send (echo, v)" = no */
  sendEcho = 0;
  if (haveSentReady == 0)
    goto L23;
L24:;
  /* "have sent ready" = yes */
  /* "send (ready, v)" = no */
  sendReady = 0;
  if (held == 0)
    goto L26;
  /* "held" = yes */
L28:;
  if (rdGe2TPlus1 == 0)
    goto L29;
  /* "ready-count(v) >= 2t+1" = yes */
L31:;
  if (rdGeTPlus1 == 0)
    goto L32;
  /* "ready-count(v) >= t+1" = yes */
L34:;
  if (readyMaskFull == 0)
    goto L35;
  /* "READY suppress mask covers all n" = yes */
  /* "retry (ready, v)" = no */
  retryReady = 0;
L37:;
  if (type == BRACHA87_ECHO)
    goto L38;
L40:;
  if (type == BRACHA87_INITIAL)
    goto L41;
  /* "kind of message" = (ready, v) */
  /* "record sender accepted" = yes */
  recordSender = 1;
  goto Ldone;
L41:;
  /* "kind of message" = (initial, v) */
  /* "record sender accepted" = no */
  recordSender = 0;
  goto Ldone;
L38:;
  /* "kind of message" = (echo, v) */
  /* "record sender accepted" = no */
  recordSender = 0;
  goto Ldone;
L35:;
  /* "READY suppress mask covers all n" = no */
  /* "retry (ready, v)" = yes */
  retryReady = 1;
  goto L37;
L32:;
  /* "ready-count(v) >= t+1" = no */
  goto L34;
L29:;
  /* "ready-count(v) >= 2t+1" = no */
  goto L31;
L26:;
  /* "held" = no */
  goto L28;
L23:;
  /* "have sent ready" = no */
  /* "retry (ready, v)" = no */
  retryReady = 0;
  if (held == 0)
    goto L44;
  /* "held" = yes */
L46:;
  if (rdGe2TPlus1 == 0)
    goto L47;
  /* "ready-count(v) >= 2t+1" = yes */
L49:;
  if (rdGeTPlus1 == 0)
    goto L50;
  /* "ready-count(v) >= t+1" = yes */
  if (readyMaskFull == 0)
    goto L53;
  /* "READY suppress mask covers all n" = yes */
L55:;
  if (type == BRACHA87_ECHO)
    goto L56;
L57:;
  if (type == BRACHA87_INITIAL)
    goto L59;
L60:;
  /* "kind of message" = (ready, v) */
  /* "record sender accepted" = yes */
  /* "send (ready, v)" = yes */
  recordSender = 1;
  sendReady = 1;
  goto Ldone;
L59:;
  /* "kind of message" = (initial, v) */
  /* "record sender accepted" = no */
  /* "send (ready, v)" = no */
  recordSender = 0;
  sendReady = 0;
  goto Ldone;
L56:;
  /* "kind of message" = (echo, v) */
  /* "record sender accepted" = no */
  /* "send (ready, v)" = yes */
  recordSender = 0;
  sendReady = 1;
  goto Ldone;
L53:;
  /* "READY suppress mask covers all n" = no */
  goto L55;
L50:;
  /* "ready-count(v) >= t+1" = no */
  if (readyMaskFull == 0)
    goto L62;
  /* "READY suppress mask covers all n" = yes */
L64:;
  if (type == BRACHA87_ECHO)
    goto L56;
  /* "send (ready, v)" = no */
  sendReady = 0;
  goto L40;
L62:;
  /* "READY suppress mask covers all n" = no */
  goto L64;
L47:;
  /* "ready-count(v) >= 2t+1" = no */
  goto L49;
L44:;
  /* "held" = no */
  goto L46;
L20:;
  /* "have echoed" = no */
  if (haveSentReady == 0)
    goto L67;
  /* "have sent ready" = yes */
  /* "send (ready, v)" = no */
  sendReady = 0;
  if (held == 0)
    goto L70;
  /* "held" = yes */
L72:;
  if (rdGe2TPlus1 == 0)
    goto L73;
  /* "ready-count(v) >= 2t+1" = yes */
L75:;
  if (rdGeTPlus1 == 0)
    goto L76;
  /* "ready-count(v) >= t+1" = yes */
  /* "send (echo, v)" = yes */
  sendEcho = 1;
  goto L34;
L76:;
  /* "ready-count(v) >= t+1" = no */
  if (readyMaskFull == 0)
    goto L79;
  /* "READY suppress mask covers all n" = yes */
  /* "retry (ready, v)" = no */
  retryReady = 0;
L81:;
  if (type == BRACHA87_ECHO)
    goto L82;
L83:;
  if (type == BRACHA87_INITIAL)
    goto L85;
  /* "kind of message" = (ready, v) */
  /* "record sender accepted" = yes */
  /* "send (echo, v)" = no */
  recordSender = 1;
  sendEcho = 0;
  goto Ldone;
L85:;
  /* "kind of message" = (initial, v) */
  /* "record sender accepted" = no */
  /* "send (echo, v)" = yes */
  recordSender = 0;
  sendEcho = 1;
  goto Ldone;
L82:;
  /* "kind of message" = (echo, v) */
  /* "record sender accepted" = no */
  /* "send (echo, v)" = yes */
  recordSender = 0;
  sendEcho = 1;
  goto Ldone;
L79:;
  /* "READY suppress mask covers all n" = no */
  /* "retry (ready, v)" = yes */
  retryReady = 1;
  goto L81;
L73:;
  /* "ready-count(v) >= 2t+1" = no */
  goto L75;
L70:;
  /* "held" = no */
  goto L72;
L67:;
  /* "have sent ready" = no */
  /* "retry (ready, v)" = no */
  retryReady = 0;
  if (held == 0)
    goto L88;
  /* "held" = yes */
L90:;
  if (rdGe2TPlus1 == 0)
    goto L91;
  /* "ready-count(v) >= 2t+1" = yes */
L93:;
  if (rdGeTPlus1 == 0)
    goto L94;
  /* "ready-count(v) >= t+1" = yes */
  /* "send (echo, v)" = yes */
  sendEcho = 1;
  if (readyMaskFull == 0)
    goto L97;
  /* "READY suppress mask covers all n" = yes */
L99:;
  if (type == BRACHA87_ECHO)
    goto L56;
L101:;
  if (type == BRACHA87_INITIAL)
    goto L59;
  goto L60;
L97:;
  /* "READY suppress mask covers all n" = no */
  goto L99;
L94:;
  /* "ready-count(v) >= t+1" = no */
  if (readyMaskFull == 0)
    goto L103;
  /* "READY suppress mask covers all n" = yes */
L105:;
  if (type == BRACHA87_ECHO)
    goto L106;
L107:;
  if (type == BRACHA87_INITIAL)
    goto L109;
  /* "kind of message" = (ready, v) */
  /* "record sender accepted" = yes */
  /* "send (echo, v)" = no */
  /* "send (ready, v)" = no */
  recordSender = 1;
  sendEcho = 0;
  sendReady = 0;
  goto Ldone;
L109:;
  /* "kind of message" = (initial, v) */
  /* "record sender accepted" = no */
  /* "send (echo, v)" = yes */
  /* "send (ready, v)" = no */
  recordSender = 0;
  sendEcho = 1;
  sendReady = 0;
  goto Ldone;
L106:;
  /* "kind of message" = (echo, v) */
  /* "record sender accepted" = no */
  /* "send (echo, v)" = yes */
  /* "send (ready, v)" = yes */
  recordSender = 0;
  sendEcho = 1;
  sendReady = 1;
  goto Ldone;
L103:;
  /* "READY suppress mask covers all n" = no */
  goto L105;
L91:;
  /* "ready-count(v) >= 2t+1" = no */
  goto L93;
L88:;
  /* "held" = no */
  goto L90;
L17:;
  /* "have accepted" = no */
  if (haveEchoed == 0)
    goto L112;
  /* "have echoed" = yes */
  /* "retry (echo, v)" = yes */
  /* "send (echo, v)" = no */
  retryEcho = 1;
  sendEcho = 0;
  if (haveSentReady == 0)
    goto L115;
L116:;
  /* "have sent ready" = yes */
  /* "send (ready, v)" = no */
  sendReady = 0;
  if (held == 0)
    goto L118;
  /* "held" = yes */
L120:;
  if (rdGe2TPlus1 == 0)
    goto L121;
  /* "ready-count(v) >= 2t+1" = yes */
  if (rdGeTPlus1 == 0)
    goto L124;
  /* "ready-count(v) >= t+1" = yes */
L126:;
  if (readyMaskFull == 0)
    goto L127;
  /* "READY suppress mask covers all n" = yes */
  /* "retry (ready, v)" = no */
  retryReady = 0;
L129:;
  if (type == BRACHA87_ECHO)
    goto L130;
L132:;
  if (type == BRACHA87_INITIAL)
    goto L133;
  /* "accept(v)" = yes */
  /* "kind of message" = (ready, v) */
  /* "record sender accepted" = yes */
  acceptV = 1;
  recordSender = 1;
  goto Ldone;
L133:;
  /* "accept(v)" = no */
  /* "kind of message" = (initial, v) */
  /* "record sender accepted" = no */
  acceptV = 0;
  recordSender = 0;
  goto Ldone;
L130:;
  /* "accept(v)" = no */
  /* "kind of message" = (echo, v) */
  /* "record sender accepted" = no */
  acceptV = 0;
  recordSender = 0;
  goto Ldone;
L127:;
  /* "READY suppress mask covers all n" = no */
  /* "retry (ready, v)" = yes */
  retryReady = 1;
  goto L129;
L124:;
  /* "ready-count(v) >= t+1" = no */
  goto L126;
L121:;
  /* "accept(v)" = no */
  /* "ready-count(v) >= 2t+1" = no */
  acceptV = 0;
  goto L31;
L118:;
  /* "held" = no */
  goto L120;
L115:;
  /* "have sent ready" = no */
  /* "retry (ready, v)" = no */
  retryReady = 0;
  if (held == 0)
    goto L136;
  /* "held" = yes */
L138:;
  if (rdGe2TPlus1 == 0)
    goto L139;
  /* "ready-count(v) >= 2t+1" = yes */
  if (rdGeTPlus1 == 0)
    goto L142;
  /* "ready-count(v) >= t+1" = yes */
  if (readyMaskFull == 0)
    goto L145;
  /* "READY suppress mask covers all n" = yes */
L147:;
  if (type == BRACHA87_ECHO)
    goto L148;
L149:;
  if (type == BRACHA87_INITIAL)
    goto L151;
L152:;
  /* "accept(v)" = yes */
  /* "kind of message" = (ready, v) */
  /* "record sender accepted" = yes */
  /* "send (ready, v)" = yes */
  acceptV = 1;
  recordSender = 1;
  sendReady = 1;
  goto Ldone;
L151:;
  /* "accept(v)" = no */
  /* "kind of message" = (initial, v) */
  /* "record sender accepted" = no */
  /* "send (ready, v)" = no */
  acceptV = 0;
  recordSender = 0;
  sendReady = 0;
  goto Ldone;
L148:;
  /* "accept(v)" = no */
  /* "kind of message" = (echo, v) */
  /* "record sender accepted" = no */
  /* "send (ready, v)" = yes */
  acceptV = 0;
  recordSender = 0;
  sendReady = 1;
  goto Ldone;
L145:;
  /* "READY suppress mask covers all n" = no */
  goto L147;
L142:;
  /* "ready-count(v) >= t+1" = no */
  if (readyMaskFull == 0)
    goto L154;
  /* "READY suppress mask covers all n" = yes */
L156:;
  if (type == BRACHA87_ECHO)
    goto L148;
  /* "accept(v)" = no */
  /* "send (ready, v)" = no */
  acceptV = 0;
  sendReady = 0;
  goto L40;
L154:;
  /* "READY suppress mask covers all n" = no */
  goto L156;
L139:;
  /* "accept(v)" = no */
  /* "ready-count(v) >= 2t+1" = no */
  acceptV = 0;
  goto L49;
L136:;
  /* "held" = no */
  goto L138;
L112:;
  /* "have echoed" = no */
  /* "retry (echo, v)" = no */
  retryEcho = 0;
  if (haveSentReady == 0)
    goto L159;
  /* "have sent ready" = yes */
  /* "send (ready, v)" = no */
  sendReady = 0;
  if (held == 0)
    goto L162;
  /* "held" = yes */
L164:;
  if (rdGe2TPlus1 == 0)
    goto L165;
  /* "ready-count(v) >= 2t+1" = yes */
  if (rdGeTPlus1 == 0)
    goto L168;
  /* "ready-count(v) >= t+1" = yes */
  /* "send (echo, v)" = yes */
  sendEcho = 1;
  goto L126;
L168:;
  /* "ready-count(v) >= t+1" = no */
  if (readyMaskFull == 0)
    goto L171;
  /* "READY suppress mask covers all n" = yes */
  /* "retry (ready, v)" = no */
  retryReady = 0;
L173:;
  if (type == BRACHA87_ECHO)
    goto L174;
L175:;
  if (type == BRACHA87_INITIAL)
    goto L177;
  /* "accept(v)" = yes */
  /* "kind of message" = (ready, v) */
  /* "record sender accepted" = yes */
  /* "send (echo, v)" = no */
  acceptV = 1;
  recordSender = 1;
  sendEcho = 0;
  goto Ldone;
L177:;
  /* "accept(v)" = no */
  /* "kind of message" = (initial, v) */
  /* "record sender accepted" = no */
  /* "send (echo, v)" = yes */
  acceptV = 0;
  recordSender = 0;
  sendEcho = 1;
  goto Ldone;
L174:;
  /* "accept(v)" = no */
  /* "kind of message" = (echo, v) */
  /* "record sender accepted" = no */
  /* "send (echo, v)" = yes */
  acceptV = 0;
  recordSender = 0;
  sendEcho = 1;
  goto Ldone;
L171:;
  /* "READY suppress mask covers all n" = no */
  /* "retry (ready, v)" = yes */
  retryReady = 1;
  goto L173;
L165:;
  /* "accept(v)" = no */
  /* "ready-count(v) >= 2t+1" = no */
  acceptV = 0;
  goto L75;
L162:;
  /* "held" = no */
  goto L164;
L159:;
  /* "have sent ready" = no */
  /* "retry (ready, v)" = no */
  retryReady = 0;
  if (held == 0)
    goto L180;
  /* "held" = yes */
L182:;
  if (rdGe2TPlus1 == 0)
    goto L183;
  /* "ready-count(v) >= 2t+1" = yes */
  if (rdGeTPlus1 == 0)
    goto L186;
  /* "ready-count(v) >= t+1" = yes */
  /* "send (echo, v)" = yes */
  sendEcho = 1;
  if (readyMaskFull == 0)
    goto L189;
  /* "READY suppress mask covers all n" = yes */
L191:;
  if (type == BRACHA87_ECHO)
    goto L148;
L193:;
  if (type == BRACHA87_INITIAL)
    goto L151;
  goto L152;
L189:;
  /* "READY suppress mask covers all n" = no */
  goto L191;
L186:;
  /* "ready-count(v) >= t+1" = no */
  if (readyMaskFull == 0)
    goto L195;
  /* "READY suppress mask covers all n" = yes */
L197:;
  if (type == BRACHA87_ECHO)
    goto L198;
L199:;
  if (type == BRACHA87_INITIAL)
    goto L201;
  /* "accept(v)" = no */
  /* "kind of message" = (ready, v) */
  /* "record sender accepted" = yes */
  /* "send (echo, v)" = no */
  /* "send (ready, v)" = no */
  acceptV = 0;
  recordSender = 1;
  sendEcho = 0;
  sendReady = 0;
  goto Ldone;
L201:;
  /* "accept(v)" = no */
  /* "kind of message" = (initial, v) */
  /* "record sender accepted" = no */
  /* "send (echo, v)" = yes */
  /* "send (ready, v)" = no */
  acceptV = 0;
  recordSender = 0;
  sendEcho = 1;
  sendReady = 0;
  goto Ldone;
L198:;
  /* "accept(v)" = no */
  /* "kind of message" = (echo, v) */
  /* "record sender accepted" = no */
  /* "send (echo, v)" = yes */
  /* "send (ready, v)" = yes */
  acceptV = 0;
  recordSender = 0;
  sendEcho = 1;
  sendReady = 1;
  goto Ldone;
L195:;
  /* "READY suppress mask covers all n" = no */
  goto L197;
L183:;
  /* "accept(v)" = no */
  /* "ready-count(v) >= 2t+1" = no */
  acceptV = 0;
  goto L93;
L180:;
  /* "held" = no */
  goto L182;
L14:;
  /* "echo-count(v) > (n+t)/2" = no */
  if (haveAccepted == 0)
    goto L204;
  /* "accept(v)" = no */
  /* "have accepted" = yes */
  /* "retry (echo, v)" = no */
  acceptV = 0;
  retryEcho = 0;
L206:;
  if (haveEchoed == 0)
    goto L207;
  /* "have echoed" = yes */
  /* "send (echo, v)" = no */
  sendEcho = 0;
  if (haveSentReady == 0)
    goto L210;
  goto L24;
L210:;
  /* "have sent ready" = no */
  /* "retry (ready, v)" = no */
  retryReady = 0;
  if (held == 0)
    goto L212;
  /* "held" = yes */
L214:;
  if (rdGe2TPlus1 == 0)
    goto L215;
  /* "ready-count(v) >= 2t+1" = yes */
L217:;
  if (rdGeTPlus1 == 0)
    goto L218;
  /* "ready-count(v) >= t+1" = yes */
  if (readyMaskFull == 0)
    goto L221;
  /* "READY suppress mask covers all n" = yes */
L223:;
  if (type == BRACHA87_ECHO)
    goto L224;
  goto L57;
L224:;
  /* "kind of message" = (echo, v) */
  /* "record sender accepted" = no */
  /* "send (ready, v)" = no */
  recordSender = 0;
  sendReady = 0;
  goto Ldone;
L221:;
  /* "READY suppress mask covers all n" = no */
  goto L223;
L218:;
  /* "ready-count(v) >= t+1" = no */
  /* "send (ready, v)" = no */
  sendReady = 0;
L225:;
  if (readyMaskFull == 0)
    goto L226;
  /* "READY suppress mask covers all n" = yes */
  goto L37;
L226:;
  /* "READY suppress mask covers all n" = no */
  goto L37;
L215:;
  /* "ready-count(v) >= 2t+1" = no */
  goto L217;
L212:;
  /* "held" = no */
  goto L214;
L207:;
  /* "have echoed" = no */
  if (haveSentReady == 0)
    goto L229;
  /* "have sent ready" = yes */
  /* "send (ready, v)" = no */
  sendReady = 0;
  if (held == 0)
    goto L232;
  /* "held" = yes */
L234:;
  if (rdGe2TPlus1 == 0)
    goto L235;
  /* "ready-count(v) >= 2t+1" = yes */
L237:;
  if (rdGeTPlus1 == 0)
    goto L238;
  /* "ready-count(v) >= t+1" = yes */
  if (readyMaskFull == 0)
    goto L241;
  /* "READY suppress mask covers all n" = yes */
  /* "retry (ready, v)" = no */
  retryReady = 0;
L243:;
  if (type == BRACHA87_ECHO)
    goto L244;
  /* "send (echo, v)" = yes */
  sendEcho = 1;
  goto L40;
L244:;
  /* "kind of message" = (echo, v) */
  /* "record sender accepted" = no */
  /* "send (echo, v)" = no */
  recordSender = 0;
  sendEcho = 0;
  goto Ldone;
L241:;
  /* "READY suppress mask covers all n" = no */
  /* "retry (ready, v)" = yes */
  retryReady = 1;
  goto L243;
L238:;
  /* "ready-count(v) >= t+1" = no */
  if (readyMaskFull == 0)
    goto L247;
  /* "READY suppress mask covers all n" = yes */
  /* "retry (ready, v)" = no */
  retryReady = 0;
L249:;
  if (type == BRACHA87_ECHO)
    goto L244;
  goto L83;
L247:;
  /* "READY suppress mask covers all n" = no */
  /* "retry (ready, v)" = yes */
  retryReady = 1;
  goto L249;
L235:;
  /* "ready-count(v) >= 2t+1" = no */
  goto L237;
L232:;
  /* "held" = no */
  goto L234;
L229:;
  /* "have sent ready" = no */
  /* "retry (ready, v)" = no */
  retryReady = 0;
  if (held == 0)
    goto L251;
  /* "held" = yes */
L253:;
  if (rdGe2TPlus1 == 0)
    goto L254;
  /* "ready-count(v) >= 2t+1" = yes */
L256:;
  if (rdGeTPlus1 == 0)
    goto L257;
  /* "ready-count(v) >= t+1" = yes */
  if (readyMaskFull == 0)
    goto L260;
  /* "READY suppress mask covers all n" = yes */
L262:;
  if (type == BRACHA87_ECHO)
    goto L263;
  /* "send (echo, v)" = yes */
  sendEcho = 1;
  goto L101;
L263:;
  /* "kind of message" = (echo, v) */
  /* "record sender accepted" = no */
  /* "send (echo, v)" = no */
  /* "send (ready, v)" = no */
  recordSender = 0;
  sendEcho = 0;
  sendReady = 0;
  goto Ldone;
L260:;
  /* "READY suppress mask covers all n" = no */
  goto L262;
L257:;
  /* "ready-count(v) >= t+1" = no */
  if (readyMaskFull == 0)
    goto L266;
  /* "READY suppress mask covers all n" = yes */
L268:;
  if (type == BRACHA87_ECHO)
    goto L263;
  goto L107;
L266:;
  /* "READY suppress mask covers all n" = no */
  goto L268;
L254:;
  /* "ready-count(v) >= 2t+1" = no */
  goto L256;
L251:;
  /* "held" = no */
  goto L253;
L204:;
  /* "have accepted" = no */
  if (haveEchoed == 0)
    goto L270;
  /* "have echoed" = yes */
  /* "retry (echo, v)" = yes */
  /* "send (echo, v)" = no */
  retryEcho = 1;
  sendEcho = 0;
  if (haveSentReady == 0)
    goto L273;
  goto L116;
L273:;
  /* "have sent ready" = no */
  /* "retry (ready, v)" = no */
  retryReady = 0;
  if (held == 0)
    goto L275;
  /* "held" = yes */
L277:;
  if (rdGe2TPlus1 == 0)
    goto L278;
  /* "ready-count(v) >= 2t+1" = yes */
  if (rdGeTPlus1 == 0)
    goto L281;
  /* "ready-count(v) >= t+1" = yes */
  if (readyMaskFull == 0)
    goto L284;
  /* "READY suppress mask covers all n" = yes */
L286:;
  if (type == BRACHA87_ECHO)
    goto L287;
  goto L149;
L287:;
  /* "accept(v)" = no */
  /* "kind of message" = (echo, v) */
  /* "record sender accepted" = no */
  /* "send (ready, v)" = no */
  acceptV = 0;
  recordSender = 0;
  sendReady = 0;
  goto Ldone;
L284:;
  /* "READY suppress mask covers all n" = no */
  goto L286;
L281:;
  /* "accept(v)" = no */
  /* "ready-count(v) >= t+1" = no */
  /* "send (ready, v)" = no */
  acceptV = 0;
  sendReady = 0;
  goto L225;
L278:;
  /* "accept(v)" = no */
  /* "ready-count(v) >= 2t+1" = no */
  acceptV = 0;
  goto L217;
L275:;
  /* "held" = no */
  goto L277;
L270:;
  /* "have echoed" = no */
  /* "retry (echo, v)" = no */
  retryEcho = 0;
  if (haveSentReady == 0)
    goto L289;
  /* "have sent ready" = yes */
  /* "send (ready, v)" = no */
  sendReady = 0;
  if (held == 0)
    goto L292;
  /* "held" = yes */
L294:;
  if (rdGe2TPlus1 == 0)
    goto L295;
  /* "ready-count(v) >= 2t+1" = yes */
  if (rdGeTPlus1 == 0)
    goto L298;
  /* "ready-count(v) >= t+1" = yes */
  if (readyMaskFull == 0)
    goto L301;
  /* "READY suppress mask covers all n" = yes */
  /* "retry (ready, v)" = no */
  retryReady = 0;
L303:;
  if (type == BRACHA87_ECHO)
    goto L304;
  /* "send (echo, v)" = yes */
  sendEcho = 1;
  goto L132;
L304:;
  /* "accept(v)" = no */
  /* "kind of message" = (echo, v) */
  /* "record sender accepted" = no */
  /* "send (echo, v)" = no */
  acceptV = 0;
  recordSender = 0;
  sendEcho = 0;
  goto Ldone;
L301:;
  /* "READY suppress mask covers all n" = no */
  /* "retry (ready, v)" = yes */
  retryReady = 1;
  goto L303;
L298:;
  /* "ready-count(v) >= t+1" = no */
  if (readyMaskFull == 0)
    goto L307;
  /* "READY suppress mask covers all n" = yes */
  /* "retry (ready, v)" = no */
  retryReady = 0;
L309:;
  if (type == BRACHA87_ECHO)
    goto L304;
  goto L175;
L307:;
  /* "READY suppress mask covers all n" = no */
  /* "retry (ready, v)" = yes */
  retryReady = 1;
  goto L309;
L295:;
  /* "accept(v)" = no */
  /* "ready-count(v) >= 2t+1" = no */
  acceptV = 0;
  goto L237;
L292:;
  /* "held" = no */
  goto L294;
L289:;
  /* "have sent ready" = no */
  /* "retry (ready, v)" = no */
  retryReady = 0;
  if (held == 0)
    goto L311;
  /* "held" = yes */
L313:;
  if (rdGe2TPlus1 == 0)
    goto L314;
  /* "ready-count(v) >= 2t+1" = yes */
  if (rdGeTPlus1 == 0)
    goto L317;
  /* "ready-count(v) >= t+1" = yes */
  if (readyMaskFull == 0)
    goto L320;
  /* "READY suppress mask covers all n" = yes */
L322:;
  if (type == BRACHA87_ECHO)
    goto L323;
  /* "send (echo, v)" = yes */
  sendEcho = 1;
  goto L193;
L323:;
  /* "accept(v)" = no */
  /* "kind of message" = (echo, v) */
  /* "record sender accepted" = no */
  /* "send (echo, v)" = no */
  /* "send (ready, v)" = no */
  acceptV = 0;
  recordSender = 0;
  sendEcho = 0;
  sendReady = 0;
  goto Ldone;
L320:;
  /* "READY suppress mask covers all n" = no */
  goto L322;
L317:;
  /* "ready-count(v) >= t+1" = no */
  if (readyMaskFull == 0)
    goto L326;
  /* "READY suppress mask covers all n" = yes */
L328:;
  if (type == BRACHA87_ECHO)
    goto L323;
  goto L199;
L326:;
  /* "READY suppress mask covers all n" = no */
  goto L328;
L314:;
  /* "accept(v)" = no */
  /* "ready-count(v) >= 2t+1" = no */
  acceptV = 0;
  goto L256;
L311:;
  /* "held" = no */
  goto L313;
L11:;
  /* "carries RECEIVED" = no */
  if (ecGtHalfNT == 0)
    goto L330;
  /* "echo-count(v) > (n+t)/2" = yes */
  if (haveAccepted == 0)
    goto L333;
  /* "accept(v)" = no */
  /* "have accepted" = yes */
  /* "retry (echo, v)" = no */
  acceptV = 0;
  retryEcho = 0;
L335:;
  if (haveEchoed == 0)
    goto L336;
  /* "have echoed" = yes */
  /* "send (echo, v)" = no */
  sendEcho = 0;
  if (haveSentReady == 0)
    goto L339;
L340:;
  /* "have sent ready" = yes */
  /* "send (ready, v)" = no */
  sendReady = 0;
  if (held == 0)
    goto L342;
  /* "held" = yes */
L344:;
  if (rdGe2TPlus1 == 0)
    goto L345;
  /* "ready-count(v) >= 2t+1" = yes */
L347:;
  if (rdGeTPlus1 == 0)
    goto L348;
  /* "ready-count(v) >= t+1" = yes */
L350:;
  if (readyMaskFull == 0)
    goto L351;
  /* "READY suppress mask covers all n" = yes */
  /* "retry (ready, v)" = no */
  retryReady = 0;
L353:;
  if (type == BRACHA87_ECHO)
    goto L354;
L356:;
  if (type == BRACHA87_INITIAL)
    goto L357;
  /* "arm re-send to sender" = yes */
  /* "kind of message" = (ready, v) */
  /* "record sender accepted" = yes */
  armSender = 1;
  recordSender = 1;
  goto Ldone;
L357:;
  /* "arm re-send to sender" = no */
  /* "kind of message" = (initial, v) */
  /* "record sender accepted" = no */
  armSender = 0;
  recordSender = 0;
  goto Ldone;
L354:;
  /* "arm re-send to sender" = no */
  /* "kind of message" = (echo, v) */
  /* "record sender accepted" = no */
  armSender = 0;
  recordSender = 0;
  goto Ldone;
L351:;
  /* "READY suppress mask covers all n" = no */
  /* "retry (ready, v)" = yes */
  retryReady = 1;
  goto L353;
L348:;
  /* "ready-count(v) >= t+1" = no */
  goto L350;
L345:;
  /* "ready-count(v) >= 2t+1" = no */
  goto L347;
L342:;
  /* "held" = no */
  goto L344;
L339:;
  /* "have sent ready" = no */
  /* "retry (ready, v)" = no */
  retryReady = 0;
  if (held == 0)
    goto L360;
  /* "held" = yes */
L362:;
  if (rdGe2TPlus1 == 0)
    goto L363;
  /* "ready-count(v) >= 2t+1" = yes */
L365:;
  if (rdGeTPlus1 == 0)
    goto L366;
  /* "ready-count(v) >= t+1" = yes */
  if (readyMaskFull == 0)
    goto L369;
  /* "READY suppress mask covers all n" = yes */
L371:;
  if (type == BRACHA87_ECHO)
    goto L372;
L373:;
  if (type == BRACHA87_INITIAL)
    goto L375;
L376:;
  /* "arm re-send to sender" = yes */
  /* "kind of message" = (ready, v) */
  /* "record sender accepted" = yes */
  /* "send (ready, v)" = yes */
  armSender = 1;
  recordSender = 1;
  sendReady = 1;
  goto Ldone;
L375:;
  /* "arm re-send to sender" = no */
  /* "kind of message" = (initial, v) */
  /* "record sender accepted" = no */
  /* "send (ready, v)" = no */
  armSender = 0;
  recordSender = 0;
  sendReady = 0;
  goto Ldone;
L372:;
  /* "arm re-send to sender" = no */
  /* "kind of message" = (echo, v) */
  /* "record sender accepted" = no */
  /* "send (ready, v)" = yes */
  armSender = 0;
  recordSender = 0;
  sendReady = 1;
  goto Ldone;
L369:;
  /* "READY suppress mask covers all n" = no */
  goto L371;
L366:;
  /* "ready-count(v) >= t+1" = no */
  if (readyMaskFull == 0)
    goto L378;
  /* "READY suppress mask covers all n" = yes */
L380:;
  if (type == BRACHA87_ECHO)
    goto L372;
  /* "send (ready, v)" = no */
  sendReady = 0;
  goto L356;
L378:;
  /* "READY suppress mask covers all n" = no */
  goto L380;
L363:;
  /* "ready-count(v) >= 2t+1" = no */
  goto L365;
L360:;
  /* "held" = no */
  goto L362;
L336:;
  /* "have echoed" = no */
  if (haveSentReady == 0)
    goto L383;
  /* "have sent ready" = yes */
  /* "send (ready, v)" = no */
  sendReady = 0;
  if (held == 0)
    goto L386;
  /* "held" = yes */
L388:;
  if (rdGe2TPlus1 == 0)
    goto L389;
  /* "ready-count(v) >= 2t+1" = yes */
L391:;
  if (rdGeTPlus1 == 0)
    goto L392;
  /* "ready-count(v) >= t+1" = yes */
  /* "send (echo, v)" = yes */
  sendEcho = 1;
  goto L350;
L392:;
  /* "ready-count(v) >= t+1" = no */
  if (readyMaskFull == 0)
    goto L395;
  /* "READY suppress mask covers all n" = yes */
  /* "retry (ready, v)" = no */
  retryReady = 0;
L397:;
  if (type == BRACHA87_ECHO)
    goto L398;
L399:;
  if (type == BRACHA87_INITIAL)
    goto L401;
  /* "arm re-send to sender" = yes */
  /* "kind of message" = (ready, v) */
  /* "record sender accepted" = yes */
  /* "send (echo, v)" = no */
  armSender = 1;
  recordSender = 1;
  sendEcho = 0;
  goto Ldone;
L401:;
  /* "arm re-send to sender" = no */
  /* "kind of message" = (initial, v) */
  /* "record sender accepted" = no */
  /* "send (echo, v)" = yes */
  armSender = 0;
  recordSender = 0;
  sendEcho = 1;
  goto Ldone;
L398:;
  /* "arm re-send to sender" = no */
  /* "kind of message" = (echo, v) */
  /* "record sender accepted" = no */
  /* "send (echo, v)" = yes */
  armSender = 0;
  recordSender = 0;
  sendEcho = 1;
  goto Ldone;
L395:;
  /* "READY suppress mask covers all n" = no */
  /* "retry (ready, v)" = yes */
  retryReady = 1;
  goto L397;
L389:;
  /* "ready-count(v) >= 2t+1" = no */
  goto L391;
L386:;
  /* "held" = no */
  goto L388;
L383:;
  /* "have sent ready" = no */
  /* "retry (ready, v)" = no */
  retryReady = 0;
  if (held == 0)
    goto L404;
  /* "held" = yes */
L406:;
  if (rdGe2TPlus1 == 0)
    goto L407;
  /* "ready-count(v) >= 2t+1" = yes */
L409:;
  if (rdGeTPlus1 == 0)
    goto L410;
  /* "ready-count(v) >= t+1" = yes */
  /* "send (echo, v)" = yes */
  sendEcho = 1;
  if (readyMaskFull == 0)
    goto L413;
  /* "READY suppress mask covers all n" = yes */
L415:;
  if (type == BRACHA87_ECHO)
    goto L372;
L417:;
  if (type == BRACHA87_INITIAL)
    goto L375;
  goto L376;
L413:;
  /* "READY suppress mask covers all n" = no */
  goto L415;
L410:;
  /* "ready-count(v) >= t+1" = no */
  if (readyMaskFull == 0)
    goto L419;
  /* "READY suppress mask covers all n" = yes */
L421:;
  if (type == BRACHA87_ECHO)
    goto L422;
L423:;
  if (type == BRACHA87_INITIAL)
    goto L425;
  /* "arm re-send to sender" = yes */
  /* "kind of message" = (ready, v) */
  /* "record sender accepted" = yes */
  /* "send (echo, v)" = no */
  /* "send (ready, v)" = no */
  armSender = 1;
  recordSender = 1;
  sendEcho = 0;
  sendReady = 0;
  goto Ldone;
L425:;
  /* "arm re-send to sender" = no */
  /* "kind of message" = (initial, v) */
  /* "record sender accepted" = no */
  /* "send (echo, v)" = yes */
  /* "send (ready, v)" = no */
  armSender = 0;
  recordSender = 0;
  sendEcho = 1;
  sendReady = 0;
  goto Ldone;
L422:;
  /* "arm re-send to sender" = no */
  /* "kind of message" = (echo, v) */
  /* "record sender accepted" = no */
  /* "send (echo, v)" = yes */
  /* "send (ready, v)" = yes */
  armSender = 0;
  recordSender = 0;
  sendEcho = 1;
  sendReady = 1;
  goto Ldone;
L419:;
  /* "READY suppress mask covers all n" = no */
  goto L421;
L407:;
  /* "ready-count(v) >= 2t+1" = no */
  goto L409;
L404:;
  /* "held" = no */
  goto L406;
L333:;
  /* "have accepted" = no */
  if (haveEchoed == 0)
    goto L428;
  /* "have echoed" = yes */
  /* "retry (echo, v)" = yes */
  /* "send (echo, v)" = no */
  retryEcho = 1;
  sendEcho = 0;
  if (haveSentReady == 0)
    goto L431;
L432:;
  /* "have sent ready" = yes */
  /* "send (ready, v)" = no */
  sendReady = 0;
  if (held == 0)
    goto L434;
  /* "held" = yes */
L436:;
  if (rdGe2TPlus1 == 0)
    goto L437;
  /* "ready-count(v) >= 2t+1" = yes */
  if (rdGeTPlus1 == 0)
    goto L440;
  /* "ready-count(v) >= t+1" = yes */
L442:;
  if (readyMaskFull == 0)
    goto L443;
  /* "READY suppress mask covers all n" = yes */
  /* "retry (ready, v)" = no */
  retryReady = 0;
L445:;
  if (type == BRACHA87_ECHO)
    goto L446;
L448:;
  if (type == BRACHA87_INITIAL)
    goto L449;
  /* "accept(v)" = yes */
  /* "arm re-send to sender" = yes */
  /* "kind of message" = (ready, v) */
  /* "record sender accepted" = yes */
  acceptV = 1;
  armSender = 1;
  recordSender = 1;
  goto Ldone;
L449:;
  /* "accept(v)" = no */
  /* "arm re-send to sender" = no */
  /* "kind of message" = (initial, v) */
  /* "record sender accepted" = no */
  acceptV = 0;
  armSender = 0;
  recordSender = 0;
  goto Ldone;
L446:;
  /* "accept(v)" = no */
  /* "arm re-send to sender" = no */
  /* "kind of message" = (echo, v) */
  /* "record sender accepted" = no */
  acceptV = 0;
  armSender = 0;
  recordSender = 0;
  goto Ldone;
L443:;
  /* "READY suppress mask covers all n" = no */
  /* "retry (ready, v)" = yes */
  retryReady = 1;
  goto L445;
L440:;
  /* "ready-count(v) >= t+1" = no */
  goto L442;
L437:;
  /* "accept(v)" = no */
  /* "arm re-send to sender" = no */
  /* "ready-count(v) >= 2t+1" = no */
  acceptV = 0;
  armSender = 0;
  goto L31;
L434:;
  /* "held" = no */
  goto L436;
L431:;
  /* "have sent ready" = no */
  /* "retry (ready, v)" = no */
  retryReady = 0;
  if (held == 0)
    goto L452;
  /* "held" = yes */
L454:;
  if (rdGe2TPlus1 == 0)
    goto L455;
  /* "ready-count(v) >= 2t+1" = yes */
  if (rdGeTPlus1 == 0)
    goto L458;
  /* "ready-count(v) >= t+1" = yes */
  if (readyMaskFull == 0)
    goto L461;
  /* "READY suppress mask covers all n" = yes */
L463:;
  if (type == BRACHA87_ECHO)
    goto L464;
L465:;
  if (type == BRACHA87_INITIAL)
    goto L467;
L468:;
  /* "accept(v)" = yes */
  /* "arm re-send to sender" = yes */
  /* "kind of message" = (ready, v) */
  /* "record sender accepted" = yes */
  /* "send (ready, v)" = yes */
  acceptV = 1;
  armSender = 1;
  recordSender = 1;
  sendReady = 1;
  goto Ldone;
L467:;
  /* "accept(v)" = no */
  /* "arm re-send to sender" = no */
  /* "kind of message" = (initial, v) */
  /* "record sender accepted" = no */
  /* "send (ready, v)" = no */
  acceptV = 0;
  armSender = 0;
  recordSender = 0;
  sendReady = 0;
  goto Ldone;
L464:;
  /* "accept(v)" = no */
  /* "arm re-send to sender" = no */
  /* "kind of message" = (echo, v) */
  /* "record sender accepted" = no */
  /* "send (ready, v)" = yes */
  acceptV = 0;
  armSender = 0;
  recordSender = 0;
  sendReady = 1;
  goto Ldone;
L461:;
  /* "READY suppress mask covers all n" = no */
  goto L463;
L458:;
  /* "ready-count(v) >= t+1" = no */
  if (readyMaskFull == 0)
    goto L470;
  /* "READY suppress mask covers all n" = yes */
L472:;
  if (type == BRACHA87_ECHO)
    goto L464;
  /* "accept(v)" = no */
  /* "arm re-send to sender" = no */
  /* "send (ready, v)" = no */
  acceptV = 0;
  armSender = 0;
  sendReady = 0;
  goto L40;
L470:;
  /* "READY suppress mask covers all n" = no */
  goto L472;
L455:;
  /* "accept(v)" = no */
  /* "arm re-send to sender" = no */
  /* "ready-count(v) >= 2t+1" = no */
  acceptV = 0;
  armSender = 0;
  goto L49;
L452:;
  /* "held" = no */
  goto L454;
L428:;
  /* "have echoed" = no */
  /* "retry (echo, v)" = no */
  retryEcho = 0;
  if (haveSentReady == 0)
    goto L475;
  /* "have sent ready" = yes */
  /* "send (ready, v)" = no */
  sendReady = 0;
  if (held == 0)
    goto L478;
  /* "held" = yes */
L480:;
  if (rdGe2TPlus1 == 0)
    goto L481;
  /* "ready-count(v) >= 2t+1" = yes */
  if (rdGeTPlus1 == 0)
    goto L484;
  /* "ready-count(v) >= t+1" = yes */
  /* "send (echo, v)" = yes */
  sendEcho = 1;
  goto L442;
L484:;
  /* "ready-count(v) >= t+1" = no */
  if (readyMaskFull == 0)
    goto L487;
  /* "READY suppress mask covers all n" = yes */
  /* "retry (ready, v)" = no */
  retryReady = 0;
L489:;
  if (type == BRACHA87_ECHO)
    goto L490;
L491:;
  if (type == BRACHA87_INITIAL)
    goto L493;
  /* "accept(v)" = yes */
  /* "arm re-send to sender" = yes */
  /* "kind of message" = (ready, v) */
  /* "record sender accepted" = yes */
  /* "send (echo, v)" = no */
  acceptV = 1;
  armSender = 1;
  recordSender = 1;
  sendEcho = 0;
  goto Ldone;
L493:;
  /* "accept(v)" = no */
  /* "arm re-send to sender" = no */
  /* "kind of message" = (initial, v) */
  /* "record sender accepted" = no */
  /* "send (echo, v)" = yes */
  acceptV = 0;
  armSender = 0;
  recordSender = 0;
  sendEcho = 1;
  goto Ldone;
L490:;
  /* "accept(v)" = no */
  /* "arm re-send to sender" = no */
  /* "kind of message" = (echo, v) */
  /* "record sender accepted" = no */
  /* "send (echo, v)" = yes */
  acceptV = 0;
  armSender = 0;
  recordSender = 0;
  sendEcho = 1;
  goto Ldone;
L487:;
  /* "READY suppress mask covers all n" = no */
  /* "retry (ready, v)" = yes */
  retryReady = 1;
  goto L489;
L481:;
  /* "accept(v)" = no */
  /* "arm re-send to sender" = no */
  /* "ready-count(v) >= 2t+1" = no */
  acceptV = 0;
  armSender = 0;
  goto L75;
L478:;
  /* "held" = no */
  goto L480;
L475:;
  /* "have sent ready" = no */
  /* "retry (ready, v)" = no */
  retryReady = 0;
  if (held == 0)
    goto L496;
  /* "held" = yes */
L498:;
  if (rdGe2TPlus1 == 0)
    goto L499;
  /* "ready-count(v) >= 2t+1" = yes */
  if (rdGeTPlus1 == 0)
    goto L502;
  /* "ready-count(v) >= t+1" = yes */
  /* "send (echo, v)" = yes */
  sendEcho = 1;
  if (readyMaskFull == 0)
    goto L505;
  /* "READY suppress mask covers all n" = yes */
L507:;
  if (type == BRACHA87_ECHO)
    goto L464;
L509:;
  if (type == BRACHA87_INITIAL)
    goto L467;
  goto L468;
L505:;
  /* "READY suppress mask covers all n" = no */
  goto L507;
L502:;
  /* "ready-count(v) >= t+1" = no */
  if (readyMaskFull == 0)
    goto L511;
  /* "READY suppress mask covers all n" = yes */
L513:;
  if (type == BRACHA87_ECHO)
    goto L514;
L515:;
  if (type == BRACHA87_INITIAL)
    goto L517;
  /* "accept(v)" = no */
  /* "arm re-send to sender" = no */
  /* "kind of message" = (ready, v) */
  /* "record sender accepted" = yes */
  /* "send (echo, v)" = no */
  /* "send (ready, v)" = no */
  acceptV = 0;
  armSender = 0;
  recordSender = 1;
  sendEcho = 0;
  sendReady = 0;
  goto Ldone;
L517:;
  /* "accept(v)" = no */
  /* "arm re-send to sender" = no */
  /* "kind of message" = (initial, v) */
  /* "record sender accepted" = no */
  /* "send (echo, v)" = yes */
  /* "send (ready, v)" = no */
  acceptV = 0;
  armSender = 0;
  recordSender = 0;
  sendEcho = 1;
  sendReady = 0;
  goto Ldone;
L514:;
  /* "accept(v)" = no */
  /* "arm re-send to sender" = no */
  /* "kind of message" = (echo, v) */
  /* "record sender accepted" = no */
  /* "send (echo, v)" = yes */
  /* "send (ready, v)" = yes */
  acceptV = 0;
  armSender = 0;
  recordSender = 0;
  sendEcho = 1;
  sendReady = 1;
  goto Ldone;
L511:;
  /* "READY suppress mask covers all n" = no */
  goto L513;
L499:;
  /* "accept(v)" = no */
  /* "arm re-send to sender" = no */
  /* "ready-count(v) >= 2t+1" = no */
  acceptV = 0;
  armSender = 0;
  goto L93;
L496:;
  /* "held" = no */
  goto L498;
L330:;
  /* "echo-count(v) > (n+t)/2" = no */
  if (haveAccepted == 0)
    goto L520;
  /* "accept(v)" = no */
  /* "have accepted" = yes */
  /* "retry (echo, v)" = no */
  acceptV = 0;
  retryEcho = 0;
L522:;
  if (haveEchoed == 0)
    goto L523;
  /* "have echoed" = yes */
  /* "send (echo, v)" = no */
  sendEcho = 0;
  if (haveSentReady == 0)
    goto L526;
  goto L340;
L526:;
  /* "have sent ready" = no */
  /* "retry (ready, v)" = no */
  retryReady = 0;
  if (held == 0)
    goto L528;
  /* "held" = yes */
L530:;
  if (rdGe2TPlus1 == 0)
    goto L531;
  /* "ready-count(v) >= 2t+1" = yes */
L533:;
  if (rdGeTPlus1 == 0)
    goto L534;
  /* "ready-count(v) >= t+1" = yes */
  if (readyMaskFull == 0)
    goto L537;
  /* "READY suppress mask covers all n" = yes */
L539:;
  if (type == BRACHA87_ECHO)
    goto L540;
  goto L373;
L540:;
  /* "arm re-send to sender" = no */
  /* "kind of message" = (echo, v) */
  /* "record sender accepted" = no */
  /* "send (ready, v)" = no */
  armSender = 0;
  recordSender = 0;
  sendReady = 0;
  goto Ldone;
L537:;
  /* "READY suppress mask covers all n" = no */
  goto L539;
L534:;
  /* "ready-count(v) >= t+1" = no */
  /* "send (ready, v)" = no */
  sendReady = 0;
  if (readyMaskFull == 0)
    goto L542;
  /* "READY suppress mask covers all n" = yes */
  goto L353;
L542:;
  /* "READY suppress mask covers all n" = no */
  goto L353;
L531:;
  /* "ready-count(v) >= 2t+1" = no */
  goto L533;
L528:;
  /* "held" = no */
  goto L530;
L523:;
  /* "have echoed" = no */
  if (haveSentReady == 0)
    goto L545;
  /* "have sent ready" = yes */
  /* "send (ready, v)" = no */
  sendReady = 0;
  if (held == 0)
    goto L548;
  /* "held" = yes */
L550:;
  if (rdGe2TPlus1 == 0)
    goto L551;
  /* "ready-count(v) >= 2t+1" = yes */
L553:;
  if (rdGeTPlus1 == 0)
    goto L554;
  /* "ready-count(v) >= t+1" = yes */
  if (readyMaskFull == 0)
    goto L557;
  /* "READY suppress mask covers all n" = yes */
  /* "retry (ready, v)" = no */
  retryReady = 0;
L559:;
  if (type == BRACHA87_ECHO)
    goto L560;
  /* "send (echo, v)" = yes */
  sendEcho = 1;
  goto L356;
L560:;
  /* "arm re-send to sender" = no */
  /* "kind of message" = (echo, v) */
  /* "record sender accepted" = no */
  /* "send (echo, v)" = no */
  armSender = 0;
  recordSender = 0;
  sendEcho = 0;
  goto Ldone;
L557:;
  /* "READY suppress mask covers all n" = no */
  /* "retry (ready, v)" = yes */
  retryReady = 1;
  goto L559;
L554:;
  /* "ready-count(v) >= t+1" = no */
  if (readyMaskFull == 0)
    goto L563;
  /* "READY suppress mask covers all n" = yes */
  /* "retry (ready, v)" = no */
  retryReady = 0;
L565:;
  if (type == BRACHA87_ECHO)
    goto L560;
  goto L399;
L563:;
  /* "READY suppress mask covers all n" = no */
  /* "retry (ready, v)" = yes */
  retryReady = 1;
  goto L565;
L551:;
  /* "ready-count(v) >= 2t+1" = no */
  goto L553;
L548:;
  /* "held" = no */
  goto L550;
L545:;
  /* "have sent ready" = no */
  /* "retry (ready, v)" = no */
  retryReady = 0;
  if (held == 0)
    goto L567;
  /* "held" = yes */
L569:;
  if (rdGe2TPlus1 == 0)
    goto L570;
  /* "ready-count(v) >= 2t+1" = yes */
L572:;
  if (rdGeTPlus1 == 0)
    goto L573;
  /* "ready-count(v) >= t+1" = yes */
  if (readyMaskFull == 0)
    goto L576;
  /* "READY suppress mask covers all n" = yes */
L578:;
  if (type == BRACHA87_ECHO)
    goto L579;
  /* "send (echo, v)" = yes */
  sendEcho = 1;
  goto L417;
L579:;
  /* "arm re-send to sender" = no */
  /* "kind of message" = (echo, v) */
  /* "record sender accepted" = no */
  /* "send (echo, v)" = no */
  /* "send (ready, v)" = no */
  armSender = 0;
  recordSender = 0;
  sendEcho = 0;
  sendReady = 0;
  goto Ldone;
L576:;
  /* "READY suppress mask covers all n" = no */
  goto L578;
L573:;
  /* "ready-count(v) >= t+1" = no */
  if (readyMaskFull == 0)
    goto L582;
  /* "READY suppress mask covers all n" = yes */
L584:;
  if (type == BRACHA87_ECHO)
    goto L579;
  goto L423;
L582:;
  /* "READY suppress mask covers all n" = no */
  goto L584;
L570:;
  /* "ready-count(v) >= 2t+1" = no */
  goto L572;
L567:;
  /* "held" = no */
  goto L569;
L520:;
  /* "have accepted" = no */
  if (haveEchoed == 0)
    goto L586;
  /* "have echoed" = yes */
  /* "retry (echo, v)" = yes */
  /* "send (echo, v)" = no */
  retryEcho = 1;
  sendEcho = 0;
  if (haveSentReady == 0)
    goto L589;
  goto L432;
L589:;
  /* "have sent ready" = no */
  /* "retry (ready, v)" = no */
  retryReady = 0;
  if (held == 0)
    goto L591;
  /* "held" = yes */
L593:;
  if (rdGe2TPlus1 == 0)
    goto L594;
  /* "ready-count(v) >= 2t+1" = yes */
  if (rdGeTPlus1 == 0)
    goto L597;
  /* "ready-count(v) >= t+1" = yes */
  if (readyMaskFull == 0)
    goto L600;
  /* "READY suppress mask covers all n" = yes */
L602:;
  if (type == BRACHA87_ECHO)
    goto L603;
  goto L465;
L603:;
  /* "accept(v)" = no */
  /* "arm re-send to sender" = no */
  /* "kind of message" = (echo, v) */
  /* "record sender accepted" = no */
  /* "send (ready, v)" = no */
  acceptV = 0;
  armSender = 0;
  recordSender = 0;
  sendReady = 0;
  goto Ldone;
L600:;
  /* "READY suppress mask covers all n" = no */
  goto L602;
L597:;
  /* "accept(v)" = no */
  /* "arm re-send to sender" = no */
  /* "ready-count(v) >= t+1" = no */
  /* "send (ready, v)" = no */
  acceptV = 0;
  armSender = 0;
  sendReady = 0;
  goto L225;
L594:;
  /* "accept(v)" = no */
  /* "arm re-send to sender" = no */
  /* "ready-count(v) >= 2t+1" = no */
  acceptV = 0;
  armSender = 0;
  goto L217;
L591:;
  /* "held" = no */
  goto L593;
L586:;
  /* "have echoed" = no */
  /* "retry (echo, v)" = no */
  retryEcho = 0;
  if (haveSentReady == 0)
    goto L605;
  /* "have sent ready" = yes */
  /* "send (ready, v)" = no */
  sendReady = 0;
  if (held == 0)
    goto L608;
  /* "held" = yes */
L610:;
  if (rdGe2TPlus1 == 0)
    goto L611;
  /* "ready-count(v) >= 2t+1" = yes */
  if (rdGeTPlus1 == 0)
    goto L614;
  /* "ready-count(v) >= t+1" = yes */
  if (readyMaskFull == 0)
    goto L617;
  /* "READY suppress mask covers all n" = yes */
  /* "retry (ready, v)" = no */
  retryReady = 0;
L619:;
  if (type == BRACHA87_ECHO)
    goto L620;
  /* "send (echo, v)" = yes */
  sendEcho = 1;
  goto L448;
L620:;
  /* "accept(v)" = no */
  /* "arm re-send to sender" = no */
  /* "kind of message" = (echo, v) */
  /* "record sender accepted" = no */
  /* "send (echo, v)" = no */
  acceptV = 0;
  armSender = 0;
  recordSender = 0;
  sendEcho = 0;
  goto Ldone;
L617:;
  /* "READY suppress mask covers all n" = no */
  /* "retry (ready, v)" = yes */
  retryReady = 1;
  goto L619;
L614:;
  /* "ready-count(v) >= t+1" = no */
  if (readyMaskFull == 0)
    goto L623;
  /* "READY suppress mask covers all n" = yes */
  /* "retry (ready, v)" = no */
  retryReady = 0;
L625:;
  if (type == BRACHA87_ECHO)
    goto L620;
  goto L491;
L623:;
  /* "READY suppress mask covers all n" = no */
  /* "retry (ready, v)" = yes */
  retryReady = 1;
  goto L625;
L611:;
  /* "accept(v)" = no */
  /* "arm re-send to sender" = no */
  /* "ready-count(v) >= 2t+1" = no */
  acceptV = 0;
  armSender = 0;
  goto L237;
L608:;
  /* "held" = no */
  goto L610;
L605:;
  /* "have sent ready" = no */
  /* "retry (ready, v)" = no */
  retryReady = 0;
  if (held == 0)
    goto L627;
  /* "held" = yes */
L629:;
  if (rdGe2TPlus1 == 0)
    goto L630;
  /* "ready-count(v) >= 2t+1" = yes */
  if (rdGeTPlus1 == 0)
    goto L633;
  /* "ready-count(v) >= t+1" = yes */
  if (readyMaskFull == 0)
    goto L636;
  /* "READY suppress mask covers all n" = yes */
L638:;
  if (type == BRACHA87_ECHO)
    goto L639;
  /* "send (echo, v)" = yes */
  sendEcho = 1;
  goto L509;
L639:;
  /* "accept(v)" = no */
  /* "arm re-send to sender" = no */
  /* "kind of message" = (echo, v) */
  /* "record sender accepted" = no */
  /* "send (echo, v)" = no */
  /* "send (ready, v)" = no */
  acceptV = 0;
  armSender = 0;
  recordSender = 0;
  sendEcho = 0;
  sendReady = 0;
  goto Ldone;
L636:;
  /* "READY suppress mask covers all n" = no */
  goto L638;
L633:;
  /* "ready-count(v) >= t+1" = no */
  if (readyMaskFull == 0)
    goto L642;
  /* "READY suppress mask covers all n" = yes */
L644:;
  if (type == BRACHA87_ECHO)
    goto L639;
  goto L515;
L642:;
  /* "READY suppress mask covers all n" = no */
  goto L644;
L630:;
  /* "accept(v)" = no */
  /* "arm re-send to sender" = no */
  /* "ready-count(v) >= 2t+1" = no */
  acceptV = 0;
  armSender = 0;
  goto L256;
L627:;
  /* "held" = no */
  goto L629;
L8:;
  /* "carries ACCEPTED" = no */
  /* "record sender accepted" = no */
  recordSender = 0;
  if (annReceived == 0)
    goto L646;
  /* "arm re-send to sender" = no */
  /* "carries RECEIVED" = yes */
  armSender = 0;
  if (ecGtHalfNT == 0)
    goto L649;
  /* "echo-count(v) > (n+t)/2" = yes */
  if (haveAccepted == 0)
    goto L652;
  /* "accept(v)" = no */
  /* "have accepted" = yes */
  /* "retry (echo, v)" = no */
  acceptV = 0;
  retryEcho = 0;
L654:;
  if (haveEchoed == 0)
    goto L655;
  /* "have echoed" = yes */
  /* "send (echo, v)" = no */
  sendEcho = 0;
  if (haveSentReady == 0)
    goto L658;
L659:;
  /* "have sent ready" = yes */
  /* "send (ready, v)" = no */
  sendReady = 0;
  if (held == 0)
    goto L661;
  /* "held" = yes */
L663:;
  if (rdGe2TPlus1 == 0)
    goto L664;
  /* "ready-count(v) >= 2t+1" = yes */
L666:;
  if (rdGeTPlus1 == 0)
    goto L667;
  /* "ready-count(v) >= t+1" = yes */
L669:;
  if (readyMaskFull == 0)
    goto L670;
  /* "READY suppress mask covers all n" = yes */
  /* "retry (ready, v)" = no */
  retryReady = 0;
L672:;
  if (type == BRACHA87_ECHO)
    goto L673;
L675:;
  if (type == BRACHA87_INITIAL)
    goto L676;
  /* "kind of message" = (ready, v) */
  goto Ldone;
L676:;
  /* "kind of message" = (initial, v) */
  goto Ldone;
L673:;
  /* "kind of message" = (echo, v) */
  goto Ldone;
L670:;
  /* "READY suppress mask covers all n" = no */
  /* "retry (ready, v)" = yes */
  retryReady = 1;
  goto L672;
L667:;
  /* "ready-count(v) >= t+1" = no */
  goto L669;
L664:;
  /* "ready-count(v) >= 2t+1" = no */
  goto L666;
L661:;
  /* "held" = no */
  goto L663;
L658:;
  /* "have sent ready" = no */
  /* "retry (ready, v)" = no */
  retryReady = 0;
  if (held == 0)
    goto L679;
  /* "held" = yes */
L681:;
  if (rdGe2TPlus1 == 0)
    goto L682;
  /* "ready-count(v) >= 2t+1" = yes */
L684:;
  if (rdGeTPlus1 == 0)
    goto L685;
  /* "ready-count(v) >= t+1" = yes */
  if (readyMaskFull == 0)
    goto L688;
  /* "READY suppress mask covers all n" = yes */
L690:;
  if (type == BRACHA87_ECHO)
    goto L691;
L692:;
  if (type == BRACHA87_INITIAL)
    goto L694;
L695:;
  /* "kind of message" = (ready, v) */
  /* "send (ready, v)" = yes */
  sendReady = 1;
  goto Ldone;
L694:;
  /* "kind of message" = (initial, v) */
  /* "send (ready, v)" = no */
  sendReady = 0;
  goto Ldone;
L691:;
  /* "kind of message" = (echo, v) */
  /* "send (ready, v)" = yes */
  sendReady = 1;
  goto Ldone;
L688:;
  /* "READY suppress mask covers all n" = no */
  goto L690;
L685:;
  /* "ready-count(v) >= t+1" = no */
  if (readyMaskFull == 0)
    goto L697;
  /* "READY suppress mask covers all n" = yes */
L699:;
  if (type == BRACHA87_ECHO)
    goto L691;
  /* "send (ready, v)" = no */
  sendReady = 0;
  goto L675;
L697:;
  /* "READY suppress mask covers all n" = no */
  goto L699;
L682:;
  /* "ready-count(v) >= 2t+1" = no */
  goto L684;
L679:;
  /* "held" = no */
  goto L681;
L655:;
  /* "have echoed" = no */
  if (haveSentReady == 0)
    goto L702;
  /* "have sent ready" = yes */
  /* "send (ready, v)" = no */
  sendReady = 0;
  if (held == 0)
    goto L705;
  /* "held" = yes */
L707:;
  if (rdGe2TPlus1 == 0)
    goto L708;
  /* "ready-count(v) >= 2t+1" = yes */
L710:;
  if (rdGeTPlus1 == 0)
    goto L711;
  /* "ready-count(v) >= t+1" = yes */
  /* "send (echo, v)" = yes */
  sendEcho = 1;
  goto L669;
L711:;
  /* "ready-count(v) >= t+1" = no */
  if (readyMaskFull == 0)
    goto L714;
  /* "READY suppress mask covers all n" = yes */
  /* "retry (ready, v)" = no */
  retryReady = 0;
L716:;
  if (type == BRACHA87_ECHO)
    goto L717;
L718:;
  if (type == BRACHA87_INITIAL)
    goto L720;
  /* "kind of message" = (ready, v) */
  /* "send (echo, v)" = no */
  sendEcho = 0;
  goto Ldone;
L720:;
  /* "kind of message" = (initial, v) */
  /* "send (echo, v)" = yes */
  sendEcho = 1;
  goto Ldone;
L717:;
  /* "kind of message" = (echo, v) */
  /* "send (echo, v)" = yes */
  sendEcho = 1;
  goto Ldone;
L714:;
  /* "READY suppress mask covers all n" = no */
  /* "retry (ready, v)" = yes */
  retryReady = 1;
  goto L716;
L708:;
  /* "ready-count(v) >= 2t+1" = no */
  goto L710;
L705:;
  /* "held" = no */
  goto L707;
L702:;
  /* "have sent ready" = no */
  /* "retry (ready, v)" = no */
  retryReady = 0;
  if (held == 0)
    goto L723;
  /* "held" = yes */
L725:;
  if (rdGe2TPlus1 == 0)
    goto L726;
  /* "ready-count(v) >= 2t+1" = yes */
L728:;
  if (rdGeTPlus1 == 0)
    goto L729;
  /* "ready-count(v) >= t+1" = yes */
  /* "send (echo, v)" = yes */
  sendEcho = 1;
  if (readyMaskFull == 0)
    goto L732;
  /* "READY suppress mask covers all n" = yes */
L734:;
  if (type == BRACHA87_ECHO)
    goto L691;
L736:;
  if (type == BRACHA87_INITIAL)
    goto L694;
  goto L695;
L732:;
  /* "READY suppress mask covers all n" = no */
  goto L734;
L729:;
  /* "ready-count(v) >= t+1" = no */
  if (readyMaskFull == 0)
    goto L738;
  /* "READY suppress mask covers all n" = yes */
L740:;
  if (type == BRACHA87_ECHO)
    goto L741;
L742:;
  if (type == BRACHA87_INITIAL)
    goto L744;
  /* "kind of message" = (ready, v) */
  /* "send (echo, v)" = no */
  /* "send (ready, v)" = no */
  sendEcho = 0;
  sendReady = 0;
  goto Ldone;
L744:;
  /* "kind of message" = (initial, v) */
  /* "send (echo, v)" = yes */
  /* "send (ready, v)" = no */
  sendEcho = 1;
  sendReady = 0;
  goto Ldone;
L741:;
  /* "kind of message" = (echo, v) */
  /* "send (echo, v)" = yes */
  /* "send (ready, v)" = yes */
  sendEcho = 1;
  sendReady = 1;
  goto Ldone;
L738:;
  /* "READY suppress mask covers all n" = no */
  goto L740;
L726:;
  /* "ready-count(v) >= 2t+1" = no */
  goto L728;
L723:;
  /* "held" = no */
  goto L725;
L652:;
  /* "have accepted" = no */
  if (haveEchoed == 0)
    goto L747;
  /* "have echoed" = yes */
  /* "retry (echo, v)" = yes */
  /* "send (echo, v)" = no */
  retryEcho = 1;
  sendEcho = 0;
  if (haveSentReady == 0)
    goto L750;
L751:;
  /* "have sent ready" = yes */
  /* "send (ready, v)" = no */
  sendReady = 0;
  if (held == 0)
    goto L753;
  /* "held" = yes */
L755:;
  if (rdGe2TPlus1 == 0)
    goto L756;
  /* "ready-count(v) >= 2t+1" = yes */
  if (rdGeTPlus1 == 0)
    goto L759;
  /* "ready-count(v) >= t+1" = yes */
L761:;
  if (readyMaskFull == 0)
    goto L762;
  /* "READY suppress mask covers all n" = yes */
  /* "retry (ready, v)" = no */
  retryReady = 0;
L764:;
  if (type == BRACHA87_ECHO)
    goto L765;
L767:;
  if (type == BRACHA87_INITIAL)
    goto L768;
  /* "accept(v)" = yes */
  /* "kind of message" = (ready, v) */
  acceptV = 1;
  goto Ldone;
L768:;
  /* "accept(v)" = no */
  /* "kind of message" = (initial, v) */
  acceptV = 0;
  goto Ldone;
L765:;
  /* "accept(v)" = no */
  /* "kind of message" = (echo, v) */
  acceptV = 0;
  goto Ldone;
L762:;
  /* "READY suppress mask covers all n" = no */
  /* "retry (ready, v)" = yes */
  retryReady = 1;
  goto L764;
L759:;
  /* "ready-count(v) >= t+1" = no */
  goto L761;
L756:;
  /* "accept(v)" = no */
  /* "ready-count(v) >= 2t+1" = no */
  acceptV = 0;
  goto L666;
L753:;
  /* "held" = no */
  goto L755;
L750:;
  /* "have sent ready" = no */
  /* "retry (ready, v)" = no */
  retryReady = 0;
  if (held == 0)
    goto L771;
  /* "held" = yes */
L773:;
  if (rdGe2TPlus1 == 0)
    goto L774;
  /* "ready-count(v) >= 2t+1" = yes */
  if (rdGeTPlus1 == 0)
    goto L777;
  /* "ready-count(v) >= t+1" = yes */
  if (readyMaskFull == 0)
    goto L780;
  /* "READY suppress mask covers all n" = yes */
L782:;
  if (type == BRACHA87_ECHO)
    goto L783;
L784:;
  if (type == BRACHA87_INITIAL)
    goto L786;
L787:;
  /* "accept(v)" = yes */
  /* "kind of message" = (ready, v) */
  /* "send (ready, v)" = yes */
  acceptV = 1;
  sendReady = 1;
  goto Ldone;
L786:;
  /* "accept(v)" = no */
  /* "kind of message" = (initial, v) */
  /* "send (ready, v)" = no */
  acceptV = 0;
  sendReady = 0;
  goto Ldone;
L783:;
  /* "accept(v)" = no */
  /* "kind of message" = (echo, v) */
  /* "send (ready, v)" = yes */
  acceptV = 0;
  sendReady = 1;
  goto Ldone;
L780:;
  /* "READY suppress mask covers all n" = no */
  goto L782;
L777:;
  /* "ready-count(v) >= t+1" = no */
  if (readyMaskFull == 0)
    goto L789;
  /* "READY suppress mask covers all n" = yes */
L791:;
  if (type == BRACHA87_ECHO)
    goto L783;
  /* "accept(v)" = no */
  /* "send (ready, v)" = no */
  acceptV = 0;
  sendReady = 0;
  goto L675;
L789:;
  /* "READY suppress mask covers all n" = no */
  goto L791;
L774:;
  /* "accept(v)" = no */
  /* "ready-count(v) >= 2t+1" = no */
  acceptV = 0;
  goto L684;
L771:;
  /* "held" = no */
  goto L773;
L747:;
  /* "have echoed" = no */
  /* "retry (echo, v)" = no */
  retryEcho = 0;
  if (haveSentReady == 0)
    goto L794;
  /* "have sent ready" = yes */
  /* "send (ready, v)" = no */
  sendReady = 0;
  if (held == 0)
    goto L797;
  /* "held" = yes */
L799:;
  if (rdGe2TPlus1 == 0)
    goto L800;
  /* "ready-count(v) >= 2t+1" = yes */
  if (rdGeTPlus1 == 0)
    goto L803;
  /* "ready-count(v) >= t+1" = yes */
  /* "send (echo, v)" = yes */
  sendEcho = 1;
  goto L761;
L803:;
  /* "ready-count(v) >= t+1" = no */
  if (readyMaskFull == 0)
    goto L806;
  /* "READY suppress mask covers all n" = yes */
  /* "retry (ready, v)" = no */
  retryReady = 0;
L808:;
  if (type == BRACHA87_ECHO)
    goto L809;
L810:;
  if (type == BRACHA87_INITIAL)
    goto L812;
  /* "accept(v)" = yes */
  /* "kind of message" = (ready, v) */
  /* "send (echo, v)" = no */
  acceptV = 1;
  sendEcho = 0;
  goto Ldone;
L812:;
  /* "accept(v)" = no */
  /* "kind of message" = (initial, v) */
  /* "send (echo, v)" = yes */
  acceptV = 0;
  sendEcho = 1;
  goto Ldone;
L809:;
  /* "accept(v)" = no */
  /* "kind of message" = (echo, v) */
  /* "send (echo, v)" = yes */
  acceptV = 0;
  sendEcho = 1;
  goto Ldone;
L806:;
  /* "READY suppress mask covers all n" = no */
  /* "retry (ready, v)" = yes */
  retryReady = 1;
  goto L808;
L800:;
  /* "accept(v)" = no */
  /* "ready-count(v) >= 2t+1" = no */
  acceptV = 0;
  goto L710;
L797:;
  /* "held" = no */
  goto L799;
L794:;
  /* "have sent ready" = no */
  /* "retry (ready, v)" = no */
  retryReady = 0;
  if (held == 0)
    goto L815;
  /* "held" = yes */
L817:;
  if (rdGe2TPlus1 == 0)
    goto L818;
  /* "ready-count(v) >= 2t+1" = yes */
  if (rdGeTPlus1 == 0)
    goto L821;
  /* "ready-count(v) >= t+1" = yes */
  /* "send (echo, v)" = yes */
  sendEcho = 1;
  if (readyMaskFull == 0)
    goto L824;
  /* "READY suppress mask covers all n" = yes */
L826:;
  if (type == BRACHA87_ECHO)
    goto L783;
L828:;
  if (type == BRACHA87_INITIAL)
    goto L786;
  goto L787;
L824:;
  /* "READY suppress mask covers all n" = no */
  goto L826;
L821:;
  /* "ready-count(v) >= t+1" = no */
  if (readyMaskFull == 0)
    goto L830;
  /* "READY suppress mask covers all n" = yes */
L832:;
  if (type == BRACHA87_ECHO)
    goto L833;
L834:;
  if (type == BRACHA87_INITIAL)
    goto L836;
  /* "accept(v)" = no */
  /* "kind of message" = (ready, v) */
  /* "send (echo, v)" = no */
  /* "send (ready, v)" = no */
  acceptV = 0;
  sendEcho = 0;
  sendReady = 0;
  goto Ldone;
L836:;
  /* "accept(v)" = no */
  /* "kind of message" = (initial, v) */
  /* "send (echo, v)" = yes */
  /* "send (ready, v)" = no */
  acceptV = 0;
  sendEcho = 1;
  sendReady = 0;
  goto Ldone;
L833:;
  /* "accept(v)" = no */
  /* "kind of message" = (echo, v) */
  /* "send (echo, v)" = yes */
  /* "send (ready, v)" = yes */
  acceptV = 0;
  sendEcho = 1;
  sendReady = 1;
  goto Ldone;
L830:;
  /* "READY suppress mask covers all n" = no */
  goto L832;
L818:;
  /* "accept(v)" = no */
  /* "ready-count(v) >= 2t+1" = no */
  acceptV = 0;
  goto L728;
L815:;
  /* "held" = no */
  goto L817;
L649:;
  /* "echo-count(v) > (n+t)/2" = no */
  if (haveAccepted == 0)
    goto L839;
  /* "accept(v)" = no */
  /* "have accepted" = yes */
  /* "retry (echo, v)" = no */
  acceptV = 0;
  retryEcho = 0;
L841:;
  if (haveEchoed == 0)
    goto L842;
  /* "have echoed" = yes */
  /* "send (echo, v)" = no */
  sendEcho = 0;
  if (haveSentReady == 0)
    goto L845;
  goto L659;
L845:;
  /* "have sent ready" = no */
  /* "retry (ready, v)" = no */
  retryReady = 0;
  if (held == 0)
    goto L847;
  /* "held" = yes */
L849:;
  if (rdGe2TPlus1 == 0)
    goto L850;
  /* "ready-count(v) >= 2t+1" = yes */
L852:;
  if (rdGeTPlus1 == 0)
    goto L853;
  /* "ready-count(v) >= t+1" = yes */
  if (readyMaskFull == 0)
    goto L856;
  /* "READY suppress mask covers all n" = yes */
L858:;
  if (type == BRACHA87_ECHO)
    goto L859;
  goto L692;
L859:;
  /* "kind of message" = (echo, v) */
  /* "send (ready, v)" = no */
  sendReady = 0;
  goto Ldone;
L856:;
  /* "READY suppress mask covers all n" = no */
  goto L858;
L853:;
  /* "ready-count(v) >= t+1" = no */
  /* "send (ready, v)" = no */
  sendReady = 0;
L860:;
  if (readyMaskFull == 0)
    goto L861;
  /* "READY suppress mask covers all n" = yes */
  goto L672;
L861:;
  /* "READY suppress mask covers all n" = no */
  goto L672;
L850:;
  /* "ready-count(v) >= 2t+1" = no */
  goto L852;
L847:;
  /* "held" = no */
  goto L849;
L842:;
  /* "have echoed" = no */
  if (haveSentReady == 0)
    goto L864;
  /* "have sent ready" = yes */
  /* "send (ready, v)" = no */
  sendReady = 0;
  if (held == 0)
    goto L867;
  /* "held" = yes */
L869:;
  if (rdGe2TPlus1 == 0)
    goto L870;
  /* "ready-count(v) >= 2t+1" = yes */
L872:;
  if (rdGeTPlus1 == 0)
    goto L873;
  /* "ready-count(v) >= t+1" = yes */
  if (readyMaskFull == 0)
    goto L876;
  /* "READY suppress mask covers all n" = yes */
  /* "retry (ready, v)" = no */
  retryReady = 0;
L878:;
  if (type == BRACHA87_ECHO)
    goto L879;
  /* "send (echo, v)" = yes */
  sendEcho = 1;
  goto L675;
L879:;
  /* "kind of message" = (echo, v) */
  /* "send (echo, v)" = no */
  sendEcho = 0;
  goto Ldone;
L876:;
  /* "READY suppress mask covers all n" = no */
  /* "retry (ready, v)" = yes */
  retryReady = 1;
  goto L878;
L873:;
  /* "ready-count(v) >= t+1" = no */
  if (readyMaskFull == 0)
    goto L882;
  /* "READY suppress mask covers all n" = yes */
  /* "retry (ready, v)" = no */
  retryReady = 0;
L884:;
  if (type == BRACHA87_ECHO)
    goto L879;
  goto L718;
L882:;
  /* "READY suppress mask covers all n" = no */
  /* "retry (ready, v)" = yes */
  retryReady = 1;
  goto L884;
L870:;
  /* "ready-count(v) >= 2t+1" = no */
  goto L872;
L867:;
  /* "held" = no */
  goto L869;
L864:;
  /* "have sent ready" = no */
  /* "retry (ready, v)" = no */
  retryReady = 0;
  if (held == 0)
    goto L886;
  /* "held" = yes */
L888:;
  if (rdGe2TPlus1 == 0)
    goto L889;
  /* "ready-count(v) >= 2t+1" = yes */
L891:;
  if (rdGeTPlus1 == 0)
    goto L892;
  /* "ready-count(v) >= t+1" = yes */
  if (readyMaskFull == 0)
    goto L895;
  /* "READY suppress mask covers all n" = yes */
L897:;
  if (type == BRACHA87_ECHO)
    goto L898;
  /* "send (echo, v)" = yes */
  sendEcho = 1;
  goto L736;
L898:;
  /* "kind of message" = (echo, v) */
  /* "send (echo, v)" = no */
  /* "send (ready, v)" = no */
  sendEcho = 0;
  sendReady = 0;
  goto Ldone;
L895:;
  /* "READY suppress mask covers all n" = no */
  goto L897;
L892:;
  /* "ready-count(v) >= t+1" = no */
  if (readyMaskFull == 0)
    goto L901;
  /* "READY suppress mask covers all n" = yes */
L903:;
  if (type == BRACHA87_ECHO)
    goto L898;
  goto L742;
L901:;
  /* "READY suppress mask covers all n" = no */
  goto L903;
L889:;
  /* "ready-count(v) >= 2t+1" = no */
  goto L891;
L886:;
  /* "held" = no */
  goto L888;
L839:;
  /* "have accepted" = no */
  if (haveEchoed == 0)
    goto L905;
  /* "have echoed" = yes */
  /* "retry (echo, v)" = yes */
  /* "send (echo, v)" = no */
  retryEcho = 1;
  sendEcho = 0;
  if (haveSentReady == 0)
    goto L908;
  goto L751;
L908:;
  /* "have sent ready" = no */
  /* "retry (ready, v)" = no */
  retryReady = 0;
  if (held == 0)
    goto L910;
  /* "held" = yes */
L912:;
  if (rdGe2TPlus1 == 0)
    goto L913;
  /* "ready-count(v) >= 2t+1" = yes */
  if (rdGeTPlus1 == 0)
    goto L916;
  /* "ready-count(v) >= t+1" = yes */
  if (readyMaskFull == 0)
    goto L919;
  /* "READY suppress mask covers all n" = yes */
L921:;
  if (type == BRACHA87_ECHO)
    goto L922;
  goto L784;
L922:;
  /* "accept(v)" = no */
  /* "kind of message" = (echo, v) */
  /* "send (ready, v)" = no */
  acceptV = 0;
  sendReady = 0;
  goto Ldone;
L919:;
  /* "READY suppress mask covers all n" = no */
  goto L921;
L916:;
  /* "accept(v)" = no */
  /* "ready-count(v) >= t+1" = no */
  /* "send (ready, v)" = no */
  acceptV = 0;
  sendReady = 0;
  goto L860;
L913:;
  /* "accept(v)" = no */
  /* "ready-count(v) >= 2t+1" = no */
  acceptV = 0;
  goto L852;
L910:;
  /* "held" = no */
  goto L912;
L905:;
  /* "have echoed" = no */
  /* "retry (echo, v)" = no */
  retryEcho = 0;
  if (haveSentReady == 0)
    goto L924;
  /* "have sent ready" = yes */
  /* "send (ready, v)" = no */
  sendReady = 0;
  if (held == 0)
    goto L927;
  /* "held" = yes */
L929:;
  if (rdGe2TPlus1 == 0)
    goto L930;
  /* "ready-count(v) >= 2t+1" = yes */
  if (rdGeTPlus1 == 0)
    goto L933;
  /* "ready-count(v) >= t+1" = yes */
  if (readyMaskFull == 0)
    goto L936;
  /* "READY suppress mask covers all n" = yes */
  /* "retry (ready, v)" = no */
  retryReady = 0;
L938:;
  if (type == BRACHA87_ECHO)
    goto L939;
  /* "send (echo, v)" = yes */
  sendEcho = 1;
  goto L767;
L939:;
  /* "accept(v)" = no */
  /* "kind of message" = (echo, v) */
  /* "send (echo, v)" = no */
  acceptV = 0;
  sendEcho = 0;
  goto Ldone;
L936:;
  /* "READY suppress mask covers all n" = no */
  /* "retry (ready, v)" = yes */
  retryReady = 1;
  goto L938;
L933:;
  /* "ready-count(v) >= t+1" = no */
  if (readyMaskFull == 0)
    goto L942;
  /* "READY suppress mask covers all n" = yes */
  /* "retry (ready, v)" = no */
  retryReady = 0;
L944:;
  if (type == BRACHA87_ECHO)
    goto L939;
  goto L810;
L942:;
  /* "READY suppress mask covers all n" = no */
  /* "retry (ready, v)" = yes */
  retryReady = 1;
  goto L944;
L930:;
  /* "accept(v)" = no */
  /* "ready-count(v) >= 2t+1" = no */
  acceptV = 0;
  goto L872;
L927:;
  /* "held" = no */
  goto L929;
L924:;
  /* "have sent ready" = no */
  /* "retry (ready, v)" = no */
  retryReady = 0;
  if (held == 0)
    goto L946;
  /* "held" = yes */
L948:;
  if (rdGe2TPlus1 == 0)
    goto L949;
  /* "ready-count(v) >= 2t+1" = yes */
  if (rdGeTPlus1 == 0)
    goto L952;
  /* "ready-count(v) >= t+1" = yes */
  if (readyMaskFull == 0)
    goto L955;
  /* "READY suppress mask covers all n" = yes */
L957:;
  if (type == BRACHA87_ECHO)
    goto L958;
  /* "send (echo, v)" = yes */
  sendEcho = 1;
  goto L828;
L958:;
  /* "accept(v)" = no */
  /* "kind of message" = (echo, v) */
  /* "send (echo, v)" = no */
  /* "send (ready, v)" = no */
  acceptV = 0;
  sendEcho = 0;
  sendReady = 0;
  goto Ldone;
L955:;
  /* "READY suppress mask covers all n" = no */
  goto L957;
L952:;
  /* "ready-count(v) >= t+1" = no */
  if (readyMaskFull == 0)
    goto L961;
  /* "READY suppress mask covers all n" = yes */
L963:;
  if (type == BRACHA87_ECHO)
    goto L958;
  goto L834;
L961:;
  /* "READY suppress mask covers all n" = no */
  goto L963;
L949:;
  /* "accept(v)" = no */
  /* "ready-count(v) >= 2t+1" = no */
  acceptV = 0;
  goto L891;
L946:;
  /* "held" = no */
  goto L948;
L646:;
  /* "carries RECEIVED" = no */
  if (ecGtHalfNT == 0)
    goto L965;
  /* "echo-count(v) > (n+t)/2" = yes */
  if (haveAccepted == 0)
    goto L968;
  /* "accept(v)" = no */
  /* "have accepted" = yes */
  /* "retry (echo, v)" = no */
  acceptV = 0;
  retryEcho = 0;
L970:;
  if (haveEchoed == 0)
    goto L971;
  /* "have echoed" = yes */
  /* "send (echo, v)" = no */
  sendEcho = 0;
  if (haveSentReady == 0)
    goto L974;
L975:;
  /* "have sent ready" = yes */
  /* "send (ready, v)" = no */
  sendReady = 0;
  if (held == 0)
    goto L977;
  /* "held" = yes */
L979:;
  if (rdGe2TPlus1 == 0)
    goto L980;
  /* "ready-count(v) >= 2t+1" = yes */
L982:;
  if (rdGeTPlus1 == 0)
    goto L983;
  /* "ready-count(v) >= t+1" = yes */
L985:;
  if (readyMaskFull == 0)
    goto L986;
  /* "READY suppress mask covers all n" = yes */
  /* "retry (ready, v)" = no */
  retryReady = 0;
L988:;
  if (type == BRACHA87_ECHO)
    goto L989;
L991:;
  if (type == BRACHA87_INITIAL)
    goto L992;
  /* "arm re-send to sender" = yes */
  /* "kind of message" = (ready, v) */
  armSender = 1;
  goto Ldone;
L992:;
  /* "arm re-send to sender" = no */
  /* "kind of message" = (initial, v) */
  armSender = 0;
  goto Ldone;
L989:;
  /* "arm re-send to sender" = no */
  /* "kind of message" = (echo, v) */
  armSender = 0;
  goto Ldone;
L986:;
  /* "READY suppress mask covers all n" = no */
  /* "retry (ready, v)" = yes */
  retryReady = 1;
  goto L988;
L983:;
  /* "ready-count(v) >= t+1" = no */
  goto L985;
L980:;
  /* "ready-count(v) >= 2t+1" = no */
  goto L982;
L977:;
  /* "held" = no */
  goto L979;
L974:;
  /* "have sent ready" = no */
  /* "retry (ready, v)" = no */
  retryReady = 0;
  if (held == 0)
    goto L995;
  /* "held" = yes */
L997:;
  if (rdGe2TPlus1 == 0)
    goto L998;
  /* "ready-count(v) >= 2t+1" = yes */
L1000:;
  if (rdGeTPlus1 == 0)
    goto L1001;
  /* "ready-count(v) >= t+1" = yes */
  if (readyMaskFull == 0)
    goto L1004;
  /* "READY suppress mask covers all n" = yes */
L1006:;
  if (type == BRACHA87_ECHO)
    goto L1007;
L1008:;
  if (type == BRACHA87_INITIAL)
    goto L1010;
L1011:;
  /* "arm re-send to sender" = yes */
  /* "kind of message" = (ready, v) */
  /* "send (ready, v)" = yes */
  armSender = 1;
  sendReady = 1;
  goto Ldone;
L1010:;
  /* "arm re-send to sender" = no */
  /* "kind of message" = (initial, v) */
  /* "send (ready, v)" = no */
  armSender = 0;
  sendReady = 0;
  goto Ldone;
L1007:;
  /* "arm re-send to sender" = no */
  /* "kind of message" = (echo, v) */
  /* "send (ready, v)" = yes */
  armSender = 0;
  sendReady = 1;
  goto Ldone;
L1004:;
  /* "READY suppress mask covers all n" = no */
  goto L1006;
L1001:;
  /* "ready-count(v) >= t+1" = no */
  if (readyMaskFull == 0)
    goto L1013;
  /* "READY suppress mask covers all n" = yes */
L1015:;
  if (type == BRACHA87_ECHO)
    goto L1007;
  /* "send (ready, v)" = no */
  sendReady = 0;
  goto L991;
L1013:;
  /* "READY suppress mask covers all n" = no */
  goto L1015;
L998:;
  /* "ready-count(v) >= 2t+1" = no */
  goto L1000;
L995:;
  /* "held" = no */
  goto L997;
L971:;
  /* "have echoed" = no */
  if (haveSentReady == 0)
    goto L1018;
  /* "have sent ready" = yes */
  /* "send (ready, v)" = no */
  sendReady = 0;
  if (held == 0)
    goto L1021;
  /* "held" = yes */
L1023:;
  if (rdGe2TPlus1 == 0)
    goto L1024;
  /* "ready-count(v) >= 2t+1" = yes */
L1026:;
  if (rdGeTPlus1 == 0)
    goto L1027;
  /* "ready-count(v) >= t+1" = yes */
  /* "send (echo, v)" = yes */
  sendEcho = 1;
  goto L985;
L1027:;
  /* "ready-count(v) >= t+1" = no */
  if (readyMaskFull == 0)
    goto L1030;
  /* "READY suppress mask covers all n" = yes */
  /* "retry (ready, v)" = no */
  retryReady = 0;
L1032:;
  if (type == BRACHA87_ECHO)
    goto L1033;
L1034:;
  if (type == BRACHA87_INITIAL)
    goto L1036;
  /* "arm re-send to sender" = yes */
  /* "kind of message" = (ready, v) */
  /* "send (echo, v)" = no */
  armSender = 1;
  sendEcho = 0;
  goto Ldone;
L1036:;
  /* "arm re-send to sender" = no */
  /* "kind of message" = (initial, v) */
  /* "send (echo, v)" = yes */
  armSender = 0;
  sendEcho = 1;
  goto Ldone;
L1033:;
  /* "arm re-send to sender" = no */
  /* "kind of message" = (echo, v) */
  /* "send (echo, v)" = yes */
  armSender = 0;
  sendEcho = 1;
  goto Ldone;
L1030:;
  /* "READY suppress mask covers all n" = no */
  /* "retry (ready, v)" = yes */
  retryReady = 1;
  goto L1032;
L1024:;
  /* "ready-count(v) >= 2t+1" = no */
  goto L1026;
L1021:;
  /* "held" = no */
  goto L1023;
L1018:;
  /* "have sent ready" = no */
  /* "retry (ready, v)" = no */
  retryReady = 0;
  if (held == 0)
    goto L1039;
  /* "held" = yes */
L1041:;
  if (rdGe2TPlus1 == 0)
    goto L1042;
  /* "ready-count(v) >= 2t+1" = yes */
L1044:;
  if (rdGeTPlus1 == 0)
    goto L1045;
  /* "ready-count(v) >= t+1" = yes */
  /* "send (echo, v)" = yes */
  sendEcho = 1;
  if (readyMaskFull == 0)
    goto L1048;
  /* "READY suppress mask covers all n" = yes */
L1050:;
  if (type == BRACHA87_ECHO)
    goto L1007;
L1052:;
  if (type == BRACHA87_INITIAL)
    goto L1010;
  goto L1011;
L1048:;
  /* "READY suppress mask covers all n" = no */
  goto L1050;
L1045:;
  /* "ready-count(v) >= t+1" = no */
  if (readyMaskFull == 0)
    goto L1054;
  /* "READY suppress mask covers all n" = yes */
L1056:;
  if (type == BRACHA87_ECHO)
    goto L1057;
L1058:;
  if (type == BRACHA87_INITIAL)
    goto L1060;
  /* "arm re-send to sender" = yes */
  /* "kind of message" = (ready, v) */
  /* "send (echo, v)" = no */
  /* "send (ready, v)" = no */
  armSender = 1;
  sendEcho = 0;
  sendReady = 0;
  goto Ldone;
L1060:;
  /* "arm re-send to sender" = no */
  /* "kind of message" = (initial, v) */
  /* "send (echo, v)" = yes */
  /* "send (ready, v)" = no */
  armSender = 0;
  sendEcho = 1;
  sendReady = 0;
  goto Ldone;
L1057:;
  /* "arm re-send to sender" = no */
  /* "kind of message" = (echo, v) */
  /* "send (echo, v)" = yes */
  /* "send (ready, v)" = yes */
  armSender = 0;
  sendEcho = 1;
  sendReady = 1;
  goto Ldone;
L1054:;
  /* "READY suppress mask covers all n" = no */
  goto L1056;
L1042:;
  /* "ready-count(v) >= 2t+1" = no */
  goto L1044;
L1039:;
  /* "held" = no */
  goto L1041;
L968:;
  /* "have accepted" = no */
  if (haveEchoed == 0)
    goto L1063;
  /* "have echoed" = yes */
  /* "retry (echo, v)" = yes */
  /* "send (echo, v)" = no */
  retryEcho = 1;
  sendEcho = 0;
  if (haveSentReady == 0)
    goto L1066;
L1067:;
  /* "have sent ready" = yes */
  /* "send (ready, v)" = no */
  sendReady = 0;
  if (held == 0)
    goto L1069;
  /* "held" = yes */
L1071:;
  if (rdGe2TPlus1 == 0)
    goto L1072;
  /* "ready-count(v) >= 2t+1" = yes */
  if (rdGeTPlus1 == 0)
    goto L1075;
  /* "ready-count(v) >= t+1" = yes */
L1077:;
  if (readyMaskFull == 0)
    goto L1078;
  /* "READY suppress mask covers all n" = yes */
  /* "retry (ready, v)" = no */
  retryReady = 0;
L1080:;
  if (type == BRACHA87_ECHO)
    goto L1081;
L1083:;
  if (type == BRACHA87_INITIAL)
    goto L1084;
  /* "accept(v)" = yes */
  /* "arm re-send to sender" = yes */
  /* "kind of message" = (ready, v) */
  acceptV = 1;
  armSender = 1;
  goto Ldone;
L1084:;
  /* "accept(v)" = no */
  /* "arm re-send to sender" = no */
  /* "kind of message" = (initial, v) */
  acceptV = 0;
  armSender = 0;
  goto Ldone;
L1081:;
  /* "accept(v)" = no */
  /* "arm re-send to sender" = no */
  /* "kind of message" = (echo, v) */
  acceptV = 0;
  armSender = 0;
  goto Ldone;
L1078:;
  /* "READY suppress mask covers all n" = no */
  /* "retry (ready, v)" = yes */
  retryReady = 1;
  goto L1080;
L1075:;
  /* "ready-count(v) >= t+1" = no */
  goto L1077;
L1072:;
  /* "accept(v)" = no */
  /* "arm re-send to sender" = no */
  /* "ready-count(v) >= 2t+1" = no */
  acceptV = 0;
  armSender = 0;
  goto L666;
L1069:;
  /* "held" = no */
  goto L1071;
L1066:;
  /* "have sent ready" = no */
  /* "retry (ready, v)" = no */
  retryReady = 0;
  if (held == 0)
    goto L1087;
  /* "held" = yes */
L1089:;
  if (rdGe2TPlus1 == 0)
    goto L1090;
  /* "ready-count(v) >= 2t+1" = yes */
  if (rdGeTPlus1 == 0)
    goto L1093;
  /* "ready-count(v) >= t+1" = yes */
  if (readyMaskFull == 0)
    goto L1096;
  /* "READY suppress mask covers all n" = yes */
L1098:;
  if (type == BRACHA87_ECHO)
    goto L1099;
L1100:;
  if (type == BRACHA87_INITIAL)
    goto L1102;
L1103:;
  /* "accept(v)" = yes */
  /* "arm re-send to sender" = yes */
  /* "kind of message" = (ready, v) */
  /* "send (ready, v)" = yes */
  acceptV = 1;
  armSender = 1;
  sendReady = 1;
  goto Ldone;
L1102:;
  /* "accept(v)" = no */
  /* "arm re-send to sender" = no */
  /* "kind of message" = (initial, v) */
  /* "send (ready, v)" = no */
  acceptV = 0;
  armSender = 0;
  sendReady = 0;
  goto Ldone;
L1099:;
  /* "accept(v)" = no */
  /* "arm re-send to sender" = no */
  /* "kind of message" = (echo, v) */
  /* "send (ready, v)" = yes */
  acceptV = 0;
  armSender = 0;
  sendReady = 1;
  goto Ldone;
L1096:;
  /* "READY suppress mask covers all n" = no */
  goto L1098;
L1093:;
  /* "ready-count(v) >= t+1" = no */
  if (readyMaskFull == 0)
    goto L1105;
  /* "READY suppress mask covers all n" = yes */
L1107:;
  if (type == BRACHA87_ECHO)
    goto L1099;
  /* "accept(v)" = no */
  /* "arm re-send to sender" = no */
  /* "send (ready, v)" = no */
  acceptV = 0;
  armSender = 0;
  sendReady = 0;
  goto L675;
L1105:;
  /* "READY suppress mask covers all n" = no */
  goto L1107;
L1090:;
  /* "accept(v)" = no */
  /* "arm re-send to sender" = no */
  /* "ready-count(v) >= 2t+1" = no */
  acceptV = 0;
  armSender = 0;
  goto L684;
L1087:;
  /* "held" = no */
  goto L1089;
L1063:;
  /* "have echoed" = no */
  /* "retry (echo, v)" = no */
  retryEcho = 0;
  if (haveSentReady == 0)
    goto L1110;
  /* "have sent ready" = yes */
  /* "send (ready, v)" = no */
  sendReady = 0;
  if (held == 0)
    goto L1113;
  /* "held" = yes */
L1115:;
  if (rdGe2TPlus1 == 0)
    goto L1116;
  /* "ready-count(v) >= 2t+1" = yes */
  if (rdGeTPlus1 == 0)
    goto L1119;
  /* "ready-count(v) >= t+1" = yes */
  /* "send (echo, v)" = yes */
  sendEcho = 1;
  goto L1077;
L1119:;
  /* "ready-count(v) >= t+1" = no */
  if (readyMaskFull == 0)
    goto L1122;
  /* "READY suppress mask covers all n" = yes */
  /* "retry (ready, v)" = no */
  retryReady = 0;
L1124:;
  if (type == BRACHA87_ECHO)
    goto L1125;
L1126:;
  if (type == BRACHA87_INITIAL)
    goto L1128;
  /* "accept(v)" = yes */
  /* "arm re-send to sender" = yes */
  /* "kind of message" = (ready, v) */
  /* "send (echo, v)" = no */
  acceptV = 1;
  armSender = 1;
  sendEcho = 0;
  goto Ldone;
L1128:;
  /* "accept(v)" = no */
  /* "arm re-send to sender" = no */
  /* "kind of message" = (initial, v) */
  /* "send (echo, v)" = yes */
  acceptV = 0;
  armSender = 0;
  sendEcho = 1;
  goto Ldone;
L1125:;
  /* "accept(v)" = no */
  /* "arm re-send to sender" = no */
  /* "kind of message" = (echo, v) */
  /* "send (echo, v)" = yes */
  acceptV = 0;
  armSender = 0;
  sendEcho = 1;
  goto Ldone;
L1122:;
  /* "READY suppress mask covers all n" = no */
  /* "retry (ready, v)" = yes */
  retryReady = 1;
  goto L1124;
L1116:;
  /* "accept(v)" = no */
  /* "arm re-send to sender" = no */
  /* "ready-count(v) >= 2t+1" = no */
  acceptV = 0;
  armSender = 0;
  goto L710;
L1113:;
  /* "held" = no */
  goto L1115;
L1110:;
  /* "have sent ready" = no */
  /* "retry (ready, v)" = no */
  retryReady = 0;
  if (held == 0)
    goto L1131;
  /* "held" = yes */
L1133:;
  if (rdGe2TPlus1 == 0)
    goto L1134;
  /* "ready-count(v) >= 2t+1" = yes */
  if (rdGeTPlus1 == 0)
    goto L1137;
  /* "ready-count(v) >= t+1" = yes */
  /* "send (echo, v)" = yes */
  sendEcho = 1;
  if (readyMaskFull == 0)
    goto L1140;
  /* "READY suppress mask covers all n" = yes */
L1142:;
  if (type == BRACHA87_ECHO)
    goto L1099;
L1144:;
  if (type == BRACHA87_INITIAL)
    goto L1102;
  goto L1103;
L1140:;
  /* "READY suppress mask covers all n" = no */
  goto L1142;
L1137:;
  /* "ready-count(v) >= t+1" = no */
  if (readyMaskFull == 0)
    goto L1146;
  /* "READY suppress mask covers all n" = yes */
L1148:;
  if (type == BRACHA87_ECHO)
    goto L1149;
L1150:;
  if (type == BRACHA87_INITIAL)
    goto L1152;
  /* "accept(v)" = no */
  /* "arm re-send to sender" = no */
  /* "kind of message" = (ready, v) */
  /* "send (echo, v)" = no */
  /* "send (ready, v)" = no */
  acceptV = 0;
  armSender = 0;
  sendEcho = 0;
  sendReady = 0;
  goto Ldone;
L1152:;
  /* "accept(v)" = no */
  /* "arm re-send to sender" = no */
  /* "kind of message" = (initial, v) */
  /* "send (echo, v)" = yes */
  /* "send (ready, v)" = no */
  acceptV = 0;
  armSender = 0;
  sendEcho = 1;
  sendReady = 0;
  goto Ldone;
L1149:;
  /* "accept(v)" = no */
  /* "arm re-send to sender" = no */
  /* "kind of message" = (echo, v) */
  /* "send (echo, v)" = yes */
  /* "send (ready, v)" = yes */
  acceptV = 0;
  armSender = 0;
  sendEcho = 1;
  sendReady = 1;
  goto Ldone;
L1146:;
  /* "READY suppress mask covers all n" = no */
  goto L1148;
L1134:;
  /* "accept(v)" = no */
  /* "arm re-send to sender" = no */
  /* "ready-count(v) >= 2t+1" = no */
  acceptV = 0;
  armSender = 0;
  goto L728;
L1131:;
  /* "held" = no */
  goto L1133;
L965:;
  /* "echo-count(v) > (n+t)/2" = no */
  if (haveAccepted == 0)
    goto L1155;
  /* "accept(v)" = no */
  /* "have accepted" = yes */
  /* "retry (echo, v)" = no */
  acceptV = 0;
  retryEcho = 0;
L1157:;
  if (haveEchoed == 0)
    goto L1158;
  /* "have echoed" = yes */
  /* "send (echo, v)" = no */
  sendEcho = 0;
  if (haveSentReady == 0)
    goto L1161;
  goto L975;
L1161:;
  /* "have sent ready" = no */
  /* "retry (ready, v)" = no */
  retryReady = 0;
  if (held == 0)
    goto L1163;
  /* "held" = yes */
L1165:;
  if (rdGe2TPlus1 == 0)
    goto L1166;
  /* "ready-count(v) >= 2t+1" = yes */
L1168:;
  if (rdGeTPlus1 == 0)
    goto L1169;
  /* "ready-count(v) >= t+1" = yes */
  if (readyMaskFull == 0)
    goto L1172;
  /* "READY suppress mask covers all n" = yes */
L1174:;
  if (type == BRACHA87_ECHO)
    goto L1175;
  goto L1008;
L1175:;
  /* "arm re-send to sender" = no */
  /* "kind of message" = (echo, v) */
  /* "send (ready, v)" = no */
  armSender = 0;
  sendReady = 0;
  goto Ldone;
L1172:;
  /* "READY suppress mask covers all n" = no */
  goto L1174;
L1169:;
  /* "ready-count(v) >= t+1" = no */
  /* "send (ready, v)" = no */
  sendReady = 0;
  if (readyMaskFull == 0)
    goto L1177;
  /* "READY suppress mask covers all n" = yes */
  goto L988;
L1177:;
  /* "READY suppress mask covers all n" = no */
  goto L988;
L1166:;
  /* "ready-count(v) >= 2t+1" = no */
  goto L1168;
L1163:;
  /* "held" = no */
  goto L1165;
L1158:;
  /* "have echoed" = no */
  if (haveSentReady == 0)
    goto L1180;
  /* "have sent ready" = yes */
  /* "send (ready, v)" = no */
  sendReady = 0;
  if (held == 0)
    goto L1183;
  /* "held" = yes */
L1185:;
  if (rdGe2TPlus1 == 0)
    goto L1186;
  /* "ready-count(v) >= 2t+1" = yes */
L1188:;
  if (rdGeTPlus1 == 0)
    goto L1189;
  /* "ready-count(v) >= t+1" = yes */
  if (readyMaskFull == 0)
    goto L1192;
  /* "READY suppress mask covers all n" = yes */
  /* "retry (ready, v)" = no */
  retryReady = 0;
L1194:;
  if (type == BRACHA87_ECHO)
    goto L1195;
  /* "send (echo, v)" = yes */
  sendEcho = 1;
  goto L991;
L1195:;
  /* "arm re-send to sender" = no */
  /* "kind of message" = (echo, v) */
  /* "send (echo, v)" = no */
  armSender = 0;
  sendEcho = 0;
  goto Ldone;
L1192:;
  /* "READY suppress mask covers all n" = no */
  /* "retry (ready, v)" = yes */
  retryReady = 1;
  goto L1194;
L1189:;
  /* "ready-count(v) >= t+1" = no */
  if (readyMaskFull == 0)
    goto L1198;
  /* "READY suppress mask covers all n" = yes */
  /* "retry (ready, v)" = no */
  retryReady = 0;
L1200:;
  if (type == BRACHA87_ECHO)
    goto L1195;
  goto L1034;
L1198:;
  /* "READY suppress mask covers all n" = no */
  /* "retry (ready, v)" = yes */
  retryReady = 1;
  goto L1200;
L1186:;
  /* "ready-count(v) >= 2t+1" = no */
  goto L1188;
L1183:;
  /* "held" = no */
  goto L1185;
L1180:;
  /* "have sent ready" = no */
  /* "retry (ready, v)" = no */
  retryReady = 0;
  if (held == 0)
    goto L1202;
  /* "held" = yes */
L1204:;
  if (rdGe2TPlus1 == 0)
    goto L1205;
  /* "ready-count(v) >= 2t+1" = yes */
L1207:;
  if (rdGeTPlus1 == 0)
    goto L1208;
  /* "ready-count(v) >= t+1" = yes */
  if (readyMaskFull == 0)
    goto L1211;
  /* "READY suppress mask covers all n" = yes */
L1213:;
  if (type == BRACHA87_ECHO)
    goto L1214;
  /* "send (echo, v)" = yes */
  sendEcho = 1;
  goto L1052;
L1214:;
  /* "arm re-send to sender" = no */
  /* "kind of message" = (echo, v) */
  /* "send (echo, v)" = no */
  /* "send (ready, v)" = no */
  armSender = 0;
  sendEcho = 0;
  sendReady = 0;
  goto Ldone;
L1211:;
  /* "READY suppress mask covers all n" = no */
  goto L1213;
L1208:;
  /* "ready-count(v) >= t+1" = no */
  if (readyMaskFull == 0)
    goto L1217;
  /* "READY suppress mask covers all n" = yes */
L1219:;
  if (type == BRACHA87_ECHO)
    goto L1214;
  goto L1058;
L1217:;
  /* "READY suppress mask covers all n" = no */
  goto L1219;
L1205:;
  /* "ready-count(v) >= 2t+1" = no */
  goto L1207;
L1202:;
  /* "held" = no */
  goto L1204;
L1155:;
  /* "have accepted" = no */
  if (haveEchoed == 0)
    goto L1221;
  /* "have echoed" = yes */
  /* "retry (echo, v)" = yes */
  /* "send (echo, v)" = no */
  retryEcho = 1;
  sendEcho = 0;
  if (haveSentReady == 0)
    goto L1224;
  goto L1067;
L1224:;
  /* "have sent ready" = no */
  /* "retry (ready, v)" = no */
  retryReady = 0;
  if (held == 0)
    goto L1226;
  /* "held" = yes */
L1228:;
  if (rdGe2TPlus1 == 0)
    goto L1229;
  /* "ready-count(v) >= 2t+1" = yes */
  if (rdGeTPlus1 == 0)
    goto L1232;
  /* "ready-count(v) >= t+1" = yes */
  if (readyMaskFull == 0)
    goto L1235;
  /* "READY suppress mask covers all n" = yes */
L1237:;
  if (type == BRACHA87_ECHO)
    goto L1238;
  goto L1100;
L1238:;
  /* "accept(v)" = no */
  /* "arm re-send to sender" = no */
  /* "kind of message" = (echo, v) */
  /* "send (ready, v)" = no */
  acceptV = 0;
  armSender = 0;
  sendReady = 0;
  goto Ldone;
L1235:;
  /* "READY suppress mask covers all n" = no */
  goto L1237;
L1232:;
  /* "accept(v)" = no */
  /* "arm re-send to sender" = no */
  /* "ready-count(v) >= t+1" = no */
  /* "send (ready, v)" = no */
  acceptV = 0;
  armSender = 0;
  sendReady = 0;
  goto L860;
L1229:;
  /* "accept(v)" = no */
  /* "arm re-send to sender" = no */
  /* "ready-count(v) >= 2t+1" = no */
  acceptV = 0;
  armSender = 0;
  goto L852;
L1226:;
  /* "held" = no */
  goto L1228;
L1221:;
  /* "have echoed" = no */
  /* "retry (echo, v)" = no */
  retryEcho = 0;
  if (haveSentReady == 0)
    goto L1240;
  /* "have sent ready" = yes */
  /* "send (ready, v)" = no */
  sendReady = 0;
  if (held == 0)
    goto L1243;
  /* "held" = yes */
L1245:;
  if (rdGe2TPlus1 == 0)
    goto L1246;
  /* "ready-count(v) >= 2t+1" = yes */
  if (rdGeTPlus1 == 0)
    goto L1249;
  /* "ready-count(v) >= t+1" = yes */
  if (readyMaskFull == 0)
    goto L1252;
  /* "READY suppress mask covers all n" = yes */
  /* "retry (ready, v)" = no */
  retryReady = 0;
L1254:;
  if (type == BRACHA87_ECHO)
    goto L1255;
  /* "send (echo, v)" = yes */
  sendEcho = 1;
  goto L1083;
L1255:;
  /* "accept(v)" = no */
  /* "arm re-send to sender" = no */
  /* "kind of message" = (echo, v) */
  /* "send (echo, v)" = no */
  acceptV = 0;
  armSender = 0;
  sendEcho = 0;
  goto Ldone;
L1252:;
  /* "READY suppress mask covers all n" = no */
  /* "retry (ready, v)" = yes */
  retryReady = 1;
  goto L1254;
L1249:;
  /* "ready-count(v) >= t+1" = no */
  if (readyMaskFull == 0)
    goto L1258;
  /* "READY suppress mask covers all n" = yes */
  /* "retry (ready, v)" = no */
  retryReady = 0;
L1260:;
  if (type == BRACHA87_ECHO)
    goto L1255;
  goto L1126;
L1258:;
  /* "READY suppress mask covers all n" = no */
  /* "retry (ready, v)" = yes */
  retryReady = 1;
  goto L1260;
L1246:;
  /* "accept(v)" = no */
  /* "arm re-send to sender" = no */
  /* "ready-count(v) >= 2t+1" = no */
  acceptV = 0;
  armSender = 0;
  goto L872;
L1243:;
  /* "held" = no */
  goto L1245;
L1240:;
  /* "have sent ready" = no */
  /* "retry (ready, v)" = no */
  retryReady = 0;
  if (held == 0)
    goto L1262;
  /* "held" = yes */
L1264:;
  if (rdGe2TPlus1 == 0)
    goto L1265;
  /* "ready-count(v) >= 2t+1" = yes */
  if (rdGeTPlus1 == 0)
    goto L1268;
  /* "ready-count(v) >= t+1" = yes */
  if (readyMaskFull == 0)
    goto L1271;
  /* "READY suppress mask covers all n" = yes */
L1273:;
  if (type == BRACHA87_ECHO)
    goto L1274;
  /* "send (echo, v)" = yes */
  sendEcho = 1;
  goto L1144;
L1274:;
  /* "accept(v)" = no */
  /* "arm re-send to sender" = no */
  /* "kind of message" = (echo, v) */
  /* "send (echo, v)" = no */
  /* "send (ready, v)" = no */
  acceptV = 0;
  armSender = 0;
  sendEcho = 0;
  sendReady = 0;
  goto Ldone;
L1271:;
  /* "READY suppress mask covers all n" = no */
  goto L1273;
L1268:;
  /* "ready-count(v) >= t+1" = no */
  if (readyMaskFull == 0)
    goto L1277;
  /* "READY suppress mask covers all n" = yes */
L1279:;
  if (type == BRACHA87_ECHO)
    goto L1274;
  goto L1150;
L1277:;
  /* "READY suppress mask covers all n" = no */
  goto L1279;
L1265:;
  /* "accept(v)" = no */
  /* "arm re-send to sender" = no */
  /* "ready-count(v) >= 2t+1" = no */
  acceptV = 0;
  armSender = 0;
  goto L891;
L1262:;
  /* "held" = no */
  goto L1264;
L5:;
  /* "am initiator" = no */
  goto L7;
L2:;
  /* "all echoed" = no */
  if (amInitiator == 0)
    goto L1281;
  /* "am initiator" = yes */
  if (annAccepted == 0)
    goto L1284;
  /* "carries ACCEPTED" = yes */
  if (annReceived == 0)
    goto L1287;
  /* "arm re-send to sender" = no */
  /* "carries RECEIVED" = yes */
  armSender = 0;
  if (ecGtHalfNT == 0)
    goto L1290;
  /* "echo-count(v) > (n+t)/2" = yes */
  if (haveAccepted == 0)
    goto L1293;
  /* "accept(v)" = no */
  /* "have accepted" = yes */
  /* "retry (echo, v)" = no */
  /* "retry (initial, v)" = no */
  acceptV = 0;
  retryEcho = 0;
  retryInitial = 0;
  goto L19;
L1293:;
  /* "have accepted" = no */
  if (haveEchoed == 0)
    goto L1296;
  /* "have echoed" = yes */
  /* "retry (echo, v)" = yes */
  /* "send (echo, v)" = no */
  retryEcho = 1;
  sendEcho = 0;
  if (haveSentReady == 0)
    goto L1299;
L1300:;
  /* "have sent ready" = yes */
  /* "send (ready, v)" = no */
  sendReady = 0;
  if (held == 0)
    goto L1302;
  /* "held" = yes */
  /* "retry (initial, v)" = no */
  retryInitial = 0;
  goto L120;
L1302:;
  /* "held" = no */
  /* "retry (initial, v)" = yes */
  retryInitial = 1;
  goto L120;
L1299:;
  /* "have sent ready" = no */
  /* "retry (ready, v)" = no */
  retryReady = 0;
  if (held == 0)
    goto L1305;
  /* "held" = yes */
  /* "retry (initial, v)" = no */
  retryInitial = 0;
  goto L138;
L1305:;
  /* "held" = no */
  /* "retry (initial, v)" = yes */
  retryInitial = 1;
  goto L138;
L1296:;
  /* "have echoed" = no */
  /* "retry (echo, v)" = no */
  retryEcho = 0;
  if (haveSentReady == 0)
    goto L1308;
  /* "have sent ready" = yes */
  /* "send (ready, v)" = no */
  sendReady = 0;
  if (held == 0)
    goto L1311;
  /* "held" = yes */
  /* "retry (initial, v)" = no */
  retryInitial = 0;
  goto L164;
L1311:;
  /* "held" = no */
  /* "retry (initial, v)" = yes */
  retryInitial = 1;
  goto L164;
L1308:;
  /* "have sent ready" = no */
  /* "retry (ready, v)" = no */
  retryReady = 0;
  if (held == 0)
    goto L1314;
  /* "held" = yes */
  /* "retry (initial, v)" = no */
  retryInitial = 0;
  goto L182;
L1314:;
  /* "held" = no */
  /* "retry (initial, v)" = yes */
  retryInitial = 1;
  goto L182;
L1290:;
  /* "echo-count(v) > (n+t)/2" = no */
  if (haveAccepted == 0)
    goto L1317;
  /* "accept(v)" = no */
  /* "have accepted" = yes */
  /* "retry (echo, v)" = no */
  /* "retry (initial, v)" = no */
  acceptV = 0;
  retryEcho = 0;
  retryInitial = 0;
  goto L206;
L1317:;
  /* "have accepted" = no */
  if (haveEchoed == 0)
    goto L1320;
  /* "have echoed" = yes */
  /* "retry (echo, v)" = yes */
  /* "send (echo, v)" = no */
  retryEcho = 1;
  sendEcho = 0;
  if (haveSentReady == 0)
    goto L1323;
  goto L1300;
L1323:;
  /* "have sent ready" = no */
  /* "retry (ready, v)" = no */
  retryReady = 0;
  if (held == 0)
    goto L1325;
  /* "held" = yes */
  /* "retry (initial, v)" = no */
  retryInitial = 0;
  goto L277;
L1325:;
  /* "held" = no */
  /* "retry (initial, v)" = yes */
  retryInitial = 1;
  goto L277;
L1320:;
  /* "have echoed" = no */
  /* "retry (echo, v)" = no */
  retryEcho = 0;
  if (haveSentReady == 0)
    goto L1328;
  /* "have sent ready" = yes */
  /* "send (ready, v)" = no */
  sendReady = 0;
  if (held == 0)
    goto L1331;
  /* "held" = yes */
  /* "retry (initial, v)" = no */
  retryInitial = 0;
  goto L294;
L1331:;
  /* "held" = no */
  /* "retry (initial, v)" = yes */
  retryInitial = 1;
  goto L294;
L1328:;
  /* "have sent ready" = no */
  /* "retry (ready, v)" = no */
  retryReady = 0;
  if (held == 0)
    goto L1334;
  /* "held" = yes */
  /* "retry (initial, v)" = no */
  retryInitial = 0;
  goto L313;
L1334:;
  /* "held" = no */
  /* "retry (initial, v)" = yes */
  retryInitial = 1;
  goto L313;
L1287:;
  /* "carries RECEIVED" = no */
  if (ecGtHalfNT == 0)
    goto L1337;
  /* "echo-count(v) > (n+t)/2" = yes */
  if (haveAccepted == 0)
    goto L1340;
  /* "accept(v)" = no */
  /* "have accepted" = yes */
  /* "retry (echo, v)" = no */
  /* "retry (initial, v)" = no */
  acceptV = 0;
  retryEcho = 0;
  retryInitial = 0;
  goto L335;
L1340:;
  /* "have accepted" = no */
  if (haveEchoed == 0)
    goto L1343;
  /* "have echoed" = yes */
  /* "retry (echo, v)" = yes */
  /* "send (echo, v)" = no */
  retryEcho = 1;
  sendEcho = 0;
  if (haveSentReady == 0)
    goto L1346;
L1347:;
  /* "have sent ready" = yes */
  /* "send (ready, v)" = no */
  sendReady = 0;
  if (held == 0)
    goto L1349;
  /* "held" = yes */
  /* "retry (initial, v)" = no */
  retryInitial = 0;
  goto L436;
L1349:;
  /* "held" = no */
  /* "retry (initial, v)" = yes */
  retryInitial = 1;
  goto L436;
L1346:;
  /* "have sent ready" = no */
  /* "retry (ready, v)" = no */
  retryReady = 0;
  if (held == 0)
    goto L1352;
  /* "held" = yes */
  /* "retry (initial, v)" = no */
  retryInitial = 0;
  goto L454;
L1352:;
  /* "held" = no */
  /* "retry (initial, v)" = yes */
  retryInitial = 1;
  goto L454;
L1343:;
  /* "have echoed" = no */
  /* "retry (echo, v)" = no */
  retryEcho = 0;
  if (haveSentReady == 0)
    goto L1355;
  /* "have sent ready" = yes */
  /* "send (ready, v)" = no */
  sendReady = 0;
  if (held == 0)
    goto L1358;
  /* "held" = yes */
  /* "retry (initial, v)" = no */
  retryInitial = 0;
  goto L480;
L1358:;
  /* "held" = no */
  /* "retry (initial, v)" = yes */
  retryInitial = 1;
  goto L480;
L1355:;
  /* "have sent ready" = no */
  /* "retry (ready, v)" = no */
  retryReady = 0;
  if (held == 0)
    goto L1361;
  /* "held" = yes */
  /* "retry (initial, v)" = no */
  retryInitial = 0;
  goto L498;
L1361:;
  /* "held" = no */
  /* "retry (initial, v)" = yes */
  retryInitial = 1;
  goto L498;
L1337:;
  /* "echo-count(v) > (n+t)/2" = no */
  if (haveAccepted == 0)
    goto L1364;
  /* "accept(v)" = no */
  /* "have accepted" = yes */
  /* "retry (echo, v)" = no */
  /* "retry (initial, v)" = no */
  acceptV = 0;
  retryEcho = 0;
  retryInitial = 0;
  goto L522;
L1364:;
  /* "have accepted" = no */
  if (haveEchoed == 0)
    goto L1367;
  /* "have echoed" = yes */
  /* "retry (echo, v)" = yes */
  /* "send (echo, v)" = no */
  retryEcho = 1;
  sendEcho = 0;
  if (haveSentReady == 0)
    goto L1370;
  goto L1347;
L1370:;
  /* "have sent ready" = no */
  /* "retry (ready, v)" = no */
  retryReady = 0;
  if (held == 0)
    goto L1372;
  /* "held" = yes */
  /* "retry (initial, v)" = no */
  retryInitial = 0;
  goto L593;
L1372:;
  /* "held" = no */
  /* "retry (initial, v)" = yes */
  retryInitial = 1;
  goto L593;
L1367:;
  /* "have echoed" = no */
  /* "retry (echo, v)" = no */
  retryEcho = 0;
  if (haveSentReady == 0)
    goto L1375;
  /* "have sent ready" = yes */
  /* "send (ready, v)" = no */
  sendReady = 0;
  if (held == 0)
    goto L1378;
  /* "held" = yes */
  /* "retry (initial, v)" = no */
  retryInitial = 0;
  goto L610;
L1378:;
  /* "held" = no */
  /* "retry (initial, v)" = yes */
  retryInitial = 1;
  goto L610;
L1375:;
  /* "have sent ready" = no */
  /* "retry (ready, v)" = no */
  retryReady = 0;
  if (held == 0)
    goto L1381;
  /* "held" = yes */
  /* "retry (initial, v)" = no */
  retryInitial = 0;
  goto L629;
L1381:;
  /* "held" = no */
  /* "retry (initial, v)" = yes */
  retryInitial = 1;
  goto L629;
L1284:;
  /* "carries ACCEPTED" = no */
  /* "record sender accepted" = no */
  recordSender = 0;
  if (annReceived == 0)
    goto L1384;
  /* "arm re-send to sender" = no */
  /* "carries RECEIVED" = yes */
  armSender = 0;
  if (ecGtHalfNT == 0)
    goto L1387;
  /* "echo-count(v) > (n+t)/2" = yes */
  if (haveAccepted == 0)
    goto L1390;
  /* "accept(v)" = no */
  /* "have accepted" = yes */
  /* "retry (echo, v)" = no */
  /* "retry (initial, v)" = no */
  acceptV = 0;
  retryEcho = 0;
  retryInitial = 0;
  goto L654;
L1390:;
  /* "have accepted" = no */
  if (haveEchoed == 0)
    goto L1393;
  /* "have echoed" = yes */
  /* "retry (echo, v)" = yes */
  /* "send (echo, v)" = no */
  retryEcho = 1;
  sendEcho = 0;
  if (haveSentReady == 0)
    goto L1396;
L1397:;
  /* "have sent ready" = yes */
  /* "send (ready, v)" = no */
  sendReady = 0;
  if (held == 0)
    goto L1399;
  /* "held" = yes */
  /* "retry (initial, v)" = no */
  retryInitial = 0;
  goto L755;
L1399:;
  /* "held" = no */
  /* "retry (initial, v)" = yes */
  retryInitial = 1;
  goto L755;
L1396:;
  /* "have sent ready" = no */
  /* "retry (ready, v)" = no */
  retryReady = 0;
  if (held == 0)
    goto L1402;
  /* "held" = yes */
  /* "retry (initial, v)" = no */
  retryInitial = 0;
  goto L773;
L1402:;
  /* "held" = no */
  /* "retry (initial, v)" = yes */
  retryInitial = 1;
  goto L773;
L1393:;
  /* "have echoed" = no */
  /* "retry (echo, v)" = no */
  retryEcho = 0;
  if (haveSentReady == 0)
    goto L1405;
  /* "have sent ready" = yes */
  /* "send (ready, v)" = no */
  sendReady = 0;
  if (held == 0)
    goto L1408;
  /* "held" = yes */
  /* "retry (initial, v)" = no */
  retryInitial = 0;
  goto L799;
L1408:;
  /* "held" = no */
  /* "retry (initial, v)" = yes */
  retryInitial = 1;
  goto L799;
L1405:;
  /* "have sent ready" = no */
  /* "retry (ready, v)" = no */
  retryReady = 0;
  if (held == 0)
    goto L1411;
  /* "held" = yes */
  /* "retry (initial, v)" = no */
  retryInitial = 0;
  goto L817;
L1411:;
  /* "held" = no */
  /* "retry (initial, v)" = yes */
  retryInitial = 1;
  goto L817;
L1387:;
  /* "echo-count(v) > (n+t)/2" = no */
  if (haveAccepted == 0)
    goto L1414;
  /* "accept(v)" = no */
  /* "have accepted" = yes */
  /* "retry (echo, v)" = no */
  /* "retry (initial, v)" = no */
  acceptV = 0;
  retryEcho = 0;
  retryInitial = 0;
  goto L841;
L1414:;
  /* "have accepted" = no */
  if (haveEchoed == 0)
    goto L1417;
  /* "have echoed" = yes */
  /* "retry (echo, v)" = yes */
  /* "send (echo, v)" = no */
  retryEcho = 1;
  sendEcho = 0;
  if (haveSentReady == 0)
    goto L1420;
  goto L1397;
L1420:;
  /* "have sent ready" = no */
  /* "retry (ready, v)" = no */
  retryReady = 0;
  if (held == 0)
    goto L1422;
  /* "held" = yes */
  /* "retry (initial, v)" = no */
  retryInitial = 0;
  goto L912;
L1422:;
  /* "held" = no */
  /* "retry (initial, v)" = yes */
  retryInitial = 1;
  goto L912;
L1417:;
  /* "have echoed" = no */
  /* "retry (echo, v)" = no */
  retryEcho = 0;
  if (haveSentReady == 0)
    goto L1425;
  /* "have sent ready" = yes */
  /* "send (ready, v)" = no */
  sendReady = 0;
  if (held == 0)
    goto L1428;
  /* "held" = yes */
  /* "retry (initial, v)" = no */
  retryInitial = 0;
  goto L929;
L1428:;
  /* "held" = no */
  /* "retry (initial, v)" = yes */
  retryInitial = 1;
  goto L929;
L1425:;
  /* "have sent ready" = no */
  /* "retry (ready, v)" = no */
  retryReady = 0;
  if (held == 0)
    goto L1431;
  /* "held" = yes */
  /* "retry (initial, v)" = no */
  retryInitial = 0;
  goto L948;
L1431:;
  /* "held" = no */
  /* "retry (initial, v)" = yes */
  retryInitial = 1;
  goto L948;
L1384:;
  /* "carries RECEIVED" = no */
  if (ecGtHalfNT == 0)
    goto L1434;
  /* "echo-count(v) > (n+t)/2" = yes */
  if (haveAccepted == 0)
    goto L1437;
  /* "accept(v)" = no */
  /* "have accepted" = yes */
  /* "retry (echo, v)" = no */
  /* "retry (initial, v)" = no */
  acceptV = 0;
  retryEcho = 0;
  retryInitial = 0;
  goto L970;
L1437:;
  /* "have accepted" = no */
  if (haveEchoed == 0)
    goto L1440;
  /* "have echoed" = yes */
  /* "retry (echo, v)" = yes */
  /* "send (echo, v)" = no */
  retryEcho = 1;
  sendEcho = 0;
  if (haveSentReady == 0)
    goto L1443;
L1444:;
  /* "have sent ready" = yes */
  /* "send (ready, v)" = no */
  sendReady = 0;
  if (held == 0)
    goto L1446;
  /* "held" = yes */
  /* "retry (initial, v)" = no */
  retryInitial = 0;
  goto L1071;
L1446:;
  /* "held" = no */
  /* "retry (initial, v)" = yes */
  retryInitial = 1;
  goto L1071;
L1443:;
  /* "have sent ready" = no */
  /* "retry (ready, v)" = no */
  retryReady = 0;
  if (held == 0)
    goto L1449;
  /* "held" = yes */
  /* "retry (initial, v)" = no */
  retryInitial = 0;
  goto L1089;
L1449:;
  /* "held" = no */
  /* "retry (initial, v)" = yes */
  retryInitial = 1;
  goto L1089;
L1440:;
  /* "have echoed" = no */
  /* "retry (echo, v)" = no */
  retryEcho = 0;
  if (haveSentReady == 0)
    goto L1452;
  /* "have sent ready" = yes */
  /* "send (ready, v)" = no */
  sendReady = 0;
  if (held == 0)
    goto L1455;
  /* "held" = yes */
  /* "retry (initial, v)" = no */
  retryInitial = 0;
  goto L1115;
L1455:;
  /* "held" = no */
  /* "retry (initial, v)" = yes */
  retryInitial = 1;
  goto L1115;
L1452:;
  /* "have sent ready" = no */
  /* "retry (ready, v)" = no */
  retryReady = 0;
  if (held == 0)
    goto L1458;
  /* "held" = yes */
  /* "retry (initial, v)" = no */
  retryInitial = 0;
  goto L1133;
L1458:;
  /* "held" = no */
  /* "retry (initial, v)" = yes */
  retryInitial = 1;
  goto L1133;
L1434:;
  /* "echo-count(v) > (n+t)/2" = no */
  if (haveAccepted == 0)
    goto L1461;
  /* "accept(v)" = no */
  /* "have accepted" = yes */
  /* "retry (echo, v)" = no */
  /* "retry (initial, v)" = no */
  acceptV = 0;
  retryEcho = 0;
  retryInitial = 0;
  goto L1157;
L1461:;
  /* "have accepted" = no */
  if (haveEchoed == 0)
    goto L1464;
  /* "have echoed" = yes */
  /* "retry (echo, v)" = yes */
  /* "send (echo, v)" = no */
  retryEcho = 1;
  sendEcho = 0;
  if (haveSentReady == 0)
    goto L1467;
  goto L1444;
L1467:;
  /* "have sent ready" = no */
  /* "retry (ready, v)" = no */
  retryReady = 0;
  if (held == 0)
    goto L1469;
  /* "held" = yes */
  /* "retry (initial, v)" = no */
  retryInitial = 0;
  goto L1228;
L1469:;
  /* "held" = no */
  /* "retry (initial, v)" = yes */
  retryInitial = 1;
  goto L1228;
L1464:;
  /* "have echoed" = no */
  /* "retry (echo, v)" = no */
  retryEcho = 0;
  if (haveSentReady == 0)
    goto L1472;
  /* "have sent ready" = yes */
  /* "send (ready, v)" = no */
  sendReady = 0;
  if (held == 0)
    goto L1475;
  /* "held" = yes */
  /* "retry (initial, v)" = no */
  retryInitial = 0;
  goto L1245;
L1475:;
  /* "held" = no */
  /* "retry (initial, v)" = yes */
  retryInitial = 1;
  goto L1245;
L1472:;
  /* "have sent ready" = no */
  /* "retry (ready, v)" = no */
  retryReady = 0;
  if (held == 0)
    goto L1478;
  /* "held" = yes */
  /* "retry (initial, v)" = no */
  retryInitial = 0;
  goto L1264;
L1478:;
  /* "held" = no */
  /* "retry (initial, v)" = yes */
  retryInitial = 1;
  goto L1264;
L1281:;
  /* "am initiator" = no */
  /* "retry (initial, v)" = no */
  retryInitial = 0;
  goto L7;
Ldone:;
