/* Generated by psu.awk from bracha87Fig1.psu -- dispatch depth 7. */
/* Edit the .dtc and regenerate; changes here are overwritten. */
  if (ecGtHalfNT == 0)
    goto L2;
  /* "echo-count(v) > (n+t)/2" = yes */
  if (haveEchoed == 0)
    goto L5;
  /* "have echoed" = yes */
  /* "retry (echo, v)" = yes */
  /* "send (echo, v)" = no */
  retryEcho = 1;
  sendEcho = 0;
  if (haveSentReady == 0)
    goto L8;
L9:;
  /* "have sent ready" = yes */
  /* "retry (ready, v)" = yes */
  /* "send (ready, v)" = no */
  retryReady = 1;
  sendReady = 0;
  if (rdGe2TPlus1 == 0)
    goto L11;
  /* "ready-count(v) >= 2t+1" = yes */
  if (rdGeTPlus1 == 0)
    goto L14;
  /* "ready-count(v) >= t+1" = yes */
L16:;
  if (type == BRACHA87_ECHO)
    goto L17;
L19:;
  if (type == BRACHA87_INITIAL)
    goto L20;
  /* "accept(v)" = yes */
  /* "kind of message" = (ready, v) */
  acceptV = 1;
  goto Ldone;
L20:;
  /* "accept(v)" = no */
  /* "kind of message" = (initial, v) */
  acceptV = 0;
  goto Ldone;
L17:;
  /* "accept(v)" = no */
  /* "kind of message" = (echo, v) */
  acceptV = 0;
  goto Ldone;
L14:;
  /* "ready-count(v) >= t+1" = no */
  goto L16;
L11:;
  /* "accept(v)" = no */
  /* "ready-count(v) >= 2t+1" = no */
  acceptV = 0;
  if (rdGeTPlus1 == 0)
    goto L23;
  /* "ready-count(v) >= t+1" = yes */
L25:;
  if (type == BRACHA87_ECHO)
    goto L26;
L28:;
  if (type == BRACHA87_INITIAL)
    goto L29;
  /* "kind of message" = (ready, v) */
  goto Ldone;
L29:;
  /* "kind of message" = (initial, v) */
  goto Ldone;
L26:;
  /* "kind of message" = (echo, v) */
  goto Ldone;
L23:;
  /* "ready-count(v) >= t+1" = no */
  goto L25;
L8:;
  /* "have sent ready" = no */
  /* "retry (ready, v)" = no */
  retryReady = 0;
  if (rdGe2TPlus1 == 0)
    goto L32;
  /* "ready-count(v) >= 2t+1" = yes */
  if (rdGeTPlus1 == 0)
    goto L35;
  /* "ready-count(v) >= t+1" = yes */
  if (type == BRACHA87_ECHO)
    goto L38;
L39:;
  if (type == BRACHA87_INITIAL)
    goto L41;
L42:;
  /* "accept(v)" = yes */
  /* "kind of message" = (ready, v) */
  /* "send (ready, v)" = yes */
  acceptV = 1;
  sendReady = 1;
  goto Ldone;
L41:;
  /* "accept(v)" = no */
  /* "kind of message" = (initial, v) */
  /* "send (ready, v)" = no */
  acceptV = 0;
  sendReady = 0;
  goto Ldone;
L38:;
  /* "accept(v)" = no */
  /* "kind of message" = (echo, v) */
  /* "send (ready, v)" = yes */
  acceptV = 0;
  sendReady = 1;
  goto Ldone;
L35:;
  /* "ready-count(v) >= t+1" = no */
  if (type == BRACHA87_ECHO)
    goto L38;
  /* "accept(v)" = no */
  /* "send (ready, v)" = no */
  acceptV = 0;
  sendReady = 0;
  goto L28;
L32:;
  /* "accept(v)" = no */
  /* "ready-count(v) >= 2t+1" = no */
  acceptV = 0;
  if (rdGeTPlus1 == 0)
    goto L46;
  /* "ready-count(v) >= t+1" = yes */
  if (type == BRACHA87_ECHO)
    goto L49;
L50:;
  if (type == BRACHA87_INITIAL)
    goto L52;
L53:;
  /* "kind of message" = (ready, v) */
  /* "send (ready, v)" = yes */
  sendReady = 1;
  goto Ldone;
L52:;
  /* "kind of message" = (initial, v) */
  /* "send (ready, v)" = no */
  sendReady = 0;
  goto Ldone;
L49:;
  /* "kind of message" = (echo, v) */
  /* "send (ready, v)" = yes */
  sendReady = 1;
  goto Ldone;
L46:;
  /* "ready-count(v) >= t+1" = no */
  if (type == BRACHA87_ECHO)
    goto L49;
  /* "send (ready, v)" = no */
  sendReady = 0;
  goto L28;
L5:;
  /* "have echoed" = no */
  /* "retry (echo, v)" = no */
  retryEcho = 0;
  if (haveSentReady == 0)
    goto L57;
  /* "have sent ready" = yes */
  /* "retry (ready, v)" = yes */
  /* "send (ready, v)" = no */
  retryReady = 1;
  sendReady = 0;
  if (rdGe2TPlus1 == 0)
    goto L60;
  /* "ready-count(v) >= 2t+1" = yes */
  if (rdGeTPlus1 == 0)
    goto L63;
  /* "ready-count(v) >= t+1" = yes */
  /* "send (echo, v)" = yes */
  sendEcho = 1;
  goto L16;
L63:;
  /* "ready-count(v) >= t+1" = no */
  if (type == BRACHA87_ECHO)
    goto L66;
L67:;
  if (type == BRACHA87_INITIAL)
    goto L69;
  /* "accept(v)" = yes */
  /* "kind of message" = (ready, v) */
  /* "send (echo, v)" = no */
  acceptV = 1;
  sendEcho = 0;
  goto Ldone;
L69:;
  /* "accept(v)" = no */
  /* "kind of message" = (initial, v) */
  /* "send (echo, v)" = yes */
  acceptV = 0;
  sendEcho = 1;
  goto Ldone;
L66:;
  /* "accept(v)" = no */
  /* "kind of message" = (echo, v) */
  /* "send (echo, v)" = yes */
  acceptV = 0;
  sendEcho = 1;
  goto Ldone;
L60:;
  /* "accept(v)" = no */
  /* "ready-count(v) >= 2t+1" = no */
  acceptV = 0;
  if (rdGeTPlus1 == 0)
    goto L72;
  /* "ready-count(v) >= t+1" = yes */
  /* "send (echo, v)" = yes */
  sendEcho = 1;
  goto L25;
L72:;
  /* "ready-count(v) >= t+1" = no */
  if (type == BRACHA87_ECHO)
    goto L75;
L76:;
  if (type == BRACHA87_INITIAL)
    goto L78;
  /* "kind of message" = (ready, v) */
  /* "send (echo, v)" = no */
  sendEcho = 0;
  goto Ldone;
L78:;
  /* "kind of message" = (initial, v) */
  /* "send (echo, v)" = yes */
  sendEcho = 1;
  goto Ldone;
L75:;
  /* "kind of message" = (echo, v) */
  /* "send (echo, v)" = yes */
  sendEcho = 1;
  goto Ldone;
L57:;
  /* "have sent ready" = no */
  /* "retry (ready, v)" = no */
  retryReady = 0;
  if (rdGe2TPlus1 == 0)
    goto L81;
  /* "ready-count(v) >= 2t+1" = yes */
  if (rdGeTPlus1 == 0)
    goto L84;
  /* "ready-count(v) >= t+1" = yes */
  /* "send (echo, v)" = yes */
  sendEcho = 1;
  if (type == BRACHA87_ECHO)
    goto L38;
L88:;
  if (type == BRACHA87_INITIAL)
    goto L41;
  goto L42;
L84:;
  /* "ready-count(v) >= t+1" = no */
  if (type == BRACHA87_ECHO)
    goto L90;
L91:;
  if (type == BRACHA87_INITIAL)
    goto L93;
  /* "accept(v)" = no */
  /* "kind of message" = (ready, v) */
  /* "send (echo, v)" = no */
  /* "send (ready, v)" = no */
  acceptV = 0;
  sendEcho = 0;
  sendReady = 0;
  goto Ldone;
L93:;
  /* "accept(v)" = no */
  /* "kind of message" = (initial, v) */
  /* "send (echo, v)" = yes */
  /* "send (ready, v)" = no */
  acceptV = 0;
  sendEcho = 1;
  sendReady = 0;
  goto Ldone;
L90:;
  /* "accept(v)" = no */
  /* "kind of message" = (echo, v) */
  /* "send (echo, v)" = yes */
  /* "send (ready, v)" = yes */
  acceptV = 0;
  sendEcho = 1;
  sendReady = 1;
  goto Ldone;
L81:;
  /* "accept(v)" = no */
  /* "ready-count(v) >= 2t+1" = no */
  acceptV = 0;
  if (rdGeTPlus1 == 0)
    goto L96;
  /* "ready-count(v) >= t+1" = yes */
  /* "send (echo, v)" = yes */
  sendEcho = 1;
  if (type == BRACHA87_ECHO)
    goto L49;
L100:;
  if (type == BRACHA87_INITIAL)
    goto L52;
  goto L53;
L96:;
  /* "ready-count(v) >= t+1" = no */
  if (type == BRACHA87_ECHO)
    goto L102;
L103:;
  if (type == BRACHA87_INITIAL)
    goto L105;
  /* "kind of message" = (ready, v) */
  /* "send (echo, v)" = no */
  /* "send (ready, v)" = no */
  sendEcho = 0;
  sendReady = 0;
  goto Ldone;
L105:;
  /* "kind of message" = (initial, v) */
  /* "send (echo, v)" = yes */
  /* "send (ready, v)" = no */
  sendEcho = 1;
  sendReady = 0;
  goto Ldone;
L102:;
  /* "kind of message" = (echo, v) */
  /* "send (echo, v)" = yes */
  /* "send (ready, v)" = yes */
  sendEcho = 1;
  sendReady = 1;
  goto Ldone;
L2:;
  /* "echo-count(v) > (n+t)/2" = no */
  if (haveEchoed == 0)
    goto L108;
  /* "have echoed" = yes */
  /* "retry (echo, v)" = yes */
  /* "send (echo, v)" = no */
  retryEcho = 1;
  sendEcho = 0;
  if (haveSentReady == 0)
    goto L111;
  goto L9;
L111:;
  /* "have sent ready" = no */
  /* "retry (ready, v)" = no */
  retryReady = 0;
  if (rdGe2TPlus1 == 0)
    goto L113;
  /* "ready-count(v) >= 2t+1" = yes */
  if (rdGeTPlus1 == 0)
    goto L116;
  /* "ready-count(v) >= t+1" = yes */
  if (type == BRACHA87_ECHO)
    goto L119;
  goto L39;
L119:;
  /* "accept(v)" = no */
  /* "kind of message" = (echo, v) */
  /* "send (ready, v)" = no */
  acceptV = 0;
  sendReady = 0;
  goto Ldone;
L116:;
  /* "accept(v)" = no */
  /* "ready-count(v) >= t+1" = no */
  /* "send (ready, v)" = no */
  acceptV = 0;
  sendReady = 0;
  goto L25;
L113:;
  /* "accept(v)" = no */
  /* "ready-count(v) >= 2t+1" = no */
  acceptV = 0;
  if (rdGeTPlus1 == 0)
    goto L121;
  /* "ready-count(v) >= t+1" = yes */
  if (type == BRACHA87_ECHO)
    goto L124;
  goto L50;
L124:;
  /* "kind of message" = (echo, v) */
  /* "send (ready, v)" = no */
  sendReady = 0;
  goto Ldone;
L121:;
  /* "ready-count(v) >= t+1" = no */
  /* "send (ready, v)" = no */
  sendReady = 0;
  goto L25;
L108:;
  /* "have echoed" = no */
  /* "retry (echo, v)" = no */
  retryEcho = 0;
  if (haveSentReady == 0)
    goto L126;
  /* "have sent ready" = yes */
  /* "retry (ready, v)" = yes */
  /* "send (ready, v)" = no */
  retryReady = 1;
  sendReady = 0;
  if (rdGe2TPlus1 == 0)
    goto L129;
  /* "ready-count(v) >= 2t+1" = yes */
  if (rdGeTPlus1 == 0)
    goto L132;
  /* "ready-count(v) >= t+1" = yes */
  if (type == BRACHA87_ECHO)
    goto L135;
  /* "send (echo, v)" = yes */
  sendEcho = 1;
  goto L19;
L135:;
  /* "accept(v)" = no */
  /* "kind of message" = (echo, v) */
  /* "send (echo, v)" = no */
  acceptV = 0;
  sendEcho = 0;
  goto Ldone;
L132:;
  /* "ready-count(v) >= t+1" = no */
  if (type == BRACHA87_ECHO)
    goto L135;
  goto L67;
L129:;
  /* "accept(v)" = no */
  /* "ready-count(v) >= 2t+1" = no */
  acceptV = 0;
  if (rdGeTPlus1 == 0)
    goto L139;
  /* "ready-count(v) >= t+1" = yes */
  if (type == BRACHA87_ECHO)
    goto L142;
  /* "send (echo, v)" = yes */
  sendEcho = 1;
  goto L28;
L142:;
  /* "kind of message" = (echo, v) */
  /* "send (echo, v)" = no */
  sendEcho = 0;
  goto Ldone;
L139:;
  /* "ready-count(v) >= t+1" = no */
  if (type == BRACHA87_ECHO)
    goto L142;
  goto L76;
L126:;
  /* "have sent ready" = no */
  /* "retry (ready, v)" = no */
  retryReady = 0;
  if (rdGe2TPlus1 == 0)
    goto L146;
  /* "ready-count(v) >= 2t+1" = yes */
  if (rdGeTPlus1 == 0)
    goto L149;
  /* "ready-count(v) >= t+1" = yes */
  if (type == BRACHA87_ECHO)
    goto L152;
  /* "send (echo, v)" = yes */
  sendEcho = 1;
  goto L88;
L152:;
  /* "accept(v)" = no */
  /* "kind of message" = (echo, v) */
  /* "send (echo, v)" = no */
  /* "send (ready, v)" = no */
  acceptV = 0;
  sendEcho = 0;
  sendReady = 0;
  goto Ldone;
L149:;
  /* "ready-count(v) >= t+1" = no */
  if (type == BRACHA87_ECHO)
    goto L152;
  goto L91;
L146:;
  /* "accept(v)" = no */
  /* "ready-count(v) >= 2t+1" = no */
  acceptV = 0;
  if (rdGeTPlus1 == 0)
    goto L156;
  /* "ready-count(v) >= t+1" = yes */
  if (type == BRACHA87_ECHO)
    goto L159;
  /* "send (echo, v)" = yes */
  sendEcho = 1;
  goto L100;
L159:;
  /* "kind of message" = (echo, v) */
  /* "send (echo, v)" = no */
  /* "send (ready, v)" = no */
  sendEcho = 0;
  sendReady = 0;
  goto Ldone;
L156:;
  /* "ready-count(v) >= t+1" = no */
  if (type == BRACHA87_ECHO)
    goto L159;
  goto L103;
Ldone:;
