/* Generated by psu.awk from bracha87Fig4.psu -- dispatch depth 6. */
/* Edit the .dtc and regenerate; changes here are overwritten. */
  if (gt2T == 0)
    goto L2;
  /* ">2t round-(3i+3) messages of form (d,v) agree on v" = yes */
  /* "adopt v" = no */
  /* "set value to coin flip" = no */
  adoptV = 0;
  setCoin = 0;
  if (gtT == 0)
    goto L5;
  /* ">t round-(3i+3) messages of form (d,v) agree on v" = yes */
L7:;
  if (haveDecided == 0)
    goto L8;
  /* "decide v" = no */
  /* "have decided" = yes */
  /* "set value to (d, majority of round (3i+2))" = no */
  /* "set value to majority of round (3i+1)" = no */
  decideV = 0;
  setDMajority = 0;
  setMajority = 0;
L10:;
  if (n2Half == 0)
    goto L11;
  /* ">n/2 round-(3i+2) messages have same value v" = yes */
L13:;
  if (subRound == 0)
    goto L14;
  if (subRound == 1)
    goto L17;
  /* "step" = 3 */
  goto Ldone;
L17:;
  /* "step" = 2 */
  goto Ldone;
L14:;
  /* "step" = 1 */
  goto Ldone;
L11:;
  /* ">n/2 round-(3i+2) messages have same value v" = no */
  goto L13;
L8:;
  /* "have decided" = no */
  if (n2Half == 0)
    goto L20;
  /* ">n/2 round-(3i+2) messages have same value v" = yes */
  if (subRound == 0)
    goto L23;
  /* "set value to majority of round (3i+1)" = no */
  setMajority = 0;
  if (subRound == 1)
    goto L26;
  /* "decide v" = yes */
  /* "set value to (d, majority of round (3i+2))" = no */
  /* "step" = 3 */
  decideV = 1;
  setDMajority = 0;
  goto Ldone;
L26:;
  /* "decide v" = no */
  /* "set value to (d, majority of round (3i+2))" = yes */
  /* "step" = 2 */
  decideV = 0;
  setDMajority = 1;
  goto Ldone;
L23:;
  /* "decide v" = no */
  /* "set value to (d, majority of round (3i+2))" = no */
  /* "set value to majority of round (3i+1)" = yes */
  /* "step" = 1 */
  decideV = 0;
  setDMajority = 0;
  setMajority = 1;
  goto Ldone;
L20:;
  /* ">n/2 round-(3i+2) messages have same value v" = no */
  /* "set value to (d, majority of round (3i+2))" = no */
  setDMajority = 0;
  if (subRound == 0)
    goto L29;
  /* "set value to majority of round (3i+1)" = no */
  setMajority = 0;
  if (subRound == 1)
    goto L32;
  /* "decide v" = yes */
  /* "step" = 3 */
  decideV = 1;
  goto Ldone;
L32:;
  /* "decide v" = no */
  /* "step" = 2 */
  decideV = 0;
  goto Ldone;
L29:;
  /* "decide v" = no */
  /* "set value to majority of round (3i+1)" = yes */
  /* "step" = 1 */
  decideV = 0;
  setMajority = 1;
  goto Ldone;
L5:;
  /* ">t round-(3i+3) messages of form (d,v) agree on v" = no */
  goto L7;
L2:;
  /* ">2t round-(3i+3) messages of form (d,v) agree on v" = no */
  /* "decide v" = no */
  decideV = 0;
  if (gtT == 0)
    goto L35;
  /* ">t round-(3i+3) messages of form (d,v) agree on v" = yes */
  /* "set value to coin flip" = no */
  setCoin = 0;
  if (haveDecided == 0)
    goto L38;
  /* "adopt v" = no */
  /* "have decided" = yes */
  /* "set value to (d, majority of round (3i+2))" = no */
  /* "set value to majority of round (3i+1)" = no */
  adoptV = 0;
  setDMajority = 0;
  setMajority = 0;
  goto L10;
L38:;
  /* "have decided" = no */
  if (n2Half == 0)
    goto L41;
  /* ">n/2 round-(3i+2) messages have same value v" = yes */
  if (subRound == 0)
    goto L44;
  /* "set value to majority of round (3i+1)" = no */
  setMajority = 0;
  if (subRound == 1)
    goto L47;
  /* "adopt v" = yes */
  /* "set value to (d, majority of round (3i+2))" = no */
  /* "step" = 3 */
  adoptV = 1;
  setDMajority = 0;
  goto Ldone;
L47:;
  /* "adopt v" = no */
  /* "set value to (d, majority of round (3i+2))" = yes */
  /* "step" = 2 */
  adoptV = 0;
  setDMajority = 1;
  goto Ldone;
L44:;
  /* "adopt v" = no */
  /* "set value to (d, majority of round (3i+2))" = no */
  /* "set value to majority of round (3i+1)" = yes */
  /* "step" = 1 */
  adoptV = 0;
  setDMajority = 0;
  setMajority = 1;
  goto Ldone;
L41:;
  /* ">n/2 round-(3i+2) messages have same value v" = no */
  /* "set value to (d, majority of round (3i+2))" = no */
  setDMajority = 0;
  if (subRound == 0)
    goto L50;
  /* "set value to majority of round (3i+1)" = no */
  setMajority = 0;
  if (subRound == 1)
    goto L53;
  /* "adopt v" = yes */
  /* "step" = 3 */
  adoptV = 1;
  goto Ldone;
L53:;
  /* "adopt v" = no */
  /* "step" = 2 */
  adoptV = 0;
  goto Ldone;
L50:;
  /* "adopt v" = no */
  /* "set value to majority of round (3i+1)" = yes */
  /* "step" = 1 */
  adoptV = 0;
  setMajority = 1;
  goto Ldone;
L35:;
  /* ">t round-(3i+3) messages of form (d,v) agree on v" = no */
  /* "adopt v" = no */
  adoptV = 0;
  if (haveDecided == 0)
    goto L56;
  /* "have decided" = yes */
  /* "set value to (d, majority of round (3i+2))" = no */
  /* "set value to coin flip" = no */
  /* "set value to majority of round (3i+1)" = no */
  setCoin = 0;
  setDMajority = 0;
  setMajority = 0;
  goto L10;
L56:;
  /* "have decided" = no */
  if (n2Half == 0)
    goto L59;
  /* ">n/2 round-(3i+2) messages have same value v" = yes */
  if (subRound == 0)
    goto L62;
  /* "set value to majority of round (3i+1)" = no */
  setMajority = 0;
  if (subRound == 1)
    goto L65;
  /* "set value to (d, majority of round (3i+2))" = no */
  /* "set value to coin flip" = yes */
  /* "step" = 3 */
  setCoin = 1;
  setDMajority = 0;
  goto Ldone;
L65:;
  /* "set value to (d, majority of round (3i+2))" = yes */
  /* "set value to coin flip" = no */
  /* "step" = 2 */
  setCoin = 0;
  setDMajority = 1;
  goto Ldone;
L62:;
  /* "set value to (d, majority of round (3i+2))" = no */
  /* "set value to coin flip" = no */
  /* "set value to majority of round (3i+1)" = yes */
  /* "step" = 1 */
  setCoin = 0;
  setDMajority = 0;
  setMajority = 1;
  goto Ldone;
L59:;
  /* ">n/2 round-(3i+2) messages have same value v" = no */
  /* "set value to (d, majority of round (3i+2))" = no */
  setDMajority = 0;
  if (subRound == 0)
    goto L68;
  /* "set value to majority of round (3i+1)" = no */
  setMajority = 0;
  if (subRound == 1)
    goto L71;
  /* "set value to coin flip" = yes */
  /* "step" = 3 */
  setCoin = 1;
  goto Ldone;
L71:;
  /* "set value to coin flip" = no */
  /* "step" = 2 */
  setCoin = 0;
  goto Ldone;
L68:;
  /* "set value to coin flip" = no */
  /* "set value to majority of round (3i+1)" = yes */
  /* "step" = 1 */
  setCoin = 0;
  setMajority = 1;
  goto Ldone;
Ldone:;
