/* Generated by psu.awk from bracha87Fig1.psu -- dispatch depth 13. */
/* Edit the .dtc and regenerate; changes here are overwritten. */
  if (allEchoed == 0)
    goto L2;
  /* "all echoed" = yes */
  /* "retry (initial, v)" = no */
  retryInitial = 0;
  if (amInitiator == 0)
    goto L5;
  /* "am initiator" = yes */
L7:;
  if (annAccepted == 0)
    goto L8;
  /* "carries ACCEPTED" = yes */
  if (annReceived == 0)
    goto L11;
  /* "arm re-send to sender" = no */
  /* "carries RECEIVED" = yes */
  armSender = 0;
  if (ecGtHalfNT == 0)
    goto L14;
  /* "echo-count(v) > (n+t)/2" = yes */
  if (haveAccepted == 0)
    goto L17;
  /* "accept(v)" = no */
  /* "have accepted" = yes */
  /* "retry (echo, v)" = no */
  acceptV = 0;
  retryEcho = 0;
L19:;
  if (haveEchoed == 0)
    goto L20;
  /* "have echoed" = yes */
  /* "send (echo, v)" = no */
  sendEcho = 0;
  if (haveSentReady == 0)
    goto L23;
L24:;
  /* "have sent ready" = yes */
  /* "send (ready, v)" = no */
  sendReady = 0;
  if (rdGe2TPlus1 == 0)
    goto L26;
  /* "ready-count(v) >= 2t+1" = yes */
L28:;
  if (rdGeTPlus1 == 0)
    goto L29;
  /* "ready-count(v) >= t+1" = yes */
L31:;
  if (readyMaskFull == 0)
    goto L32;
  /* "READY suppress mask covers all n" = yes */
  /* "retry (ready, v)" = no */
  retryReady = 0;
L34:;
  if (type == BRACHA87_ECHO)
    goto L35;
L37:;
  if (type == BRACHA87_INITIAL)
    goto L38;
  /* "kind of message" = (ready, v) */
  /* "record sender accepted" = yes */
  recordSender = 1;
  goto Ldone;
L38:;
  /* "kind of message" = (initial, v) */
  /* "record sender accepted" = no */
  recordSender = 0;
  goto Ldone;
L35:;
  /* "kind of message" = (echo, v) */
  /* "record sender accepted" = no */
  recordSender = 0;
  goto Ldone;
L32:;
  /* "READY suppress mask covers all n" = no */
  /* "retry (ready, v)" = yes */
  retryReady = 1;
  goto L34;
L29:;
  /* "ready-count(v) >= t+1" = no */
  goto L31;
L26:;
  /* "ready-count(v) >= 2t+1" = no */
  goto L28;
L23:;
  /* "have sent ready" = no */
  /* "retry (ready, v)" = no */
  retryReady = 0;
  if (rdGe2TPlus1 == 0)
    goto L41;
  /* "ready-count(v) >= 2t+1" = yes */
L43:;
  if (rdGeTPlus1 == 0)
    goto L44;
  /* "ready-count(v) >= t+1" = yes */
  if (readyMaskFull == 0)
    goto L47;
  /* "READY suppress mask covers all n" = yes */
L49:;
  if (type == BRACHA87_ECHO)
    goto L50;
L51:;
  if (type == BRACHA87_INITIAL)
    goto L53;
L54:;
  /* "kind of message" = (ready, v) */
  /* "record sender accepted" = yes */
  /* "send (ready, v)" = yes */
  recordSender = 1;
  sendReady = 1;
  goto Ldone;
L53:;
  /* "kind of message" = (initial, v) */
  /* "record sender accepted" = no */
  /* "send (ready, v)" = no */
  recordSender = 0;
  sendReady = 0;
  goto Ldone;
L50:;
  /* "kind of message" = (echo, v) */
  /* "record sender accepted" = no */
  /* "send (ready, v)" = yes */
  recordSender = 0;
  sendReady = 1;
  goto Ldone;
L47:;
  /* "READY suppress mask covers all n" = no */
  goto L49;
L44:;
  /* "ready-count(v) >= t+1" = no */
  if (readyMaskFull == 0)
    goto L56;
  /* "READY suppress mask covers all n" = yes */
L58:;
  if (type == BRACHA87_ECHO)
    goto L50;
  /* "send (ready, v)" = no */
  sendReady = 0;
  goto L37;
L56:;
  /* "READY suppress mask covers all n" = no */
  goto L58;
L41:;
  /* "ready-count(v) >= 2t+1" = no */
  goto L43;
L20:;
  /* "have echoed" = no */
  if (haveSentReady == 0)
    goto L61;
  /* "have sent ready" = yes */
  /* "send (ready, v)" = no */
  sendReady = 0;
  if (rdGe2TPlus1 == 0)
    goto L64;
  /* "ready-count(v) >= 2t+1" = yes */
L66:;
  if (rdGeTPlus1 == 0)
    goto L67;
  /* "ready-count(v) >= t+1" = yes */
  /* "send (echo, v)" = yes */
  sendEcho = 1;
  goto L31;
L67:;
  /* "ready-count(v) >= t+1" = no */
  if (readyMaskFull == 0)
    goto L70;
  /* "READY suppress mask covers all n" = yes */
  /* "retry (ready, v)" = no */
  retryReady = 0;
L72:;
  if (type == BRACHA87_ECHO)
    goto L73;
L74:;
  if (type == BRACHA87_INITIAL)
    goto L76;
  /* "kind of message" = (ready, v) */
  /* "record sender accepted" = yes */
  /* "send (echo, v)" = no */
  recordSender = 1;
  sendEcho = 0;
  goto Ldone;
L76:;
  /* "kind of message" = (initial, v) */
  /* "record sender accepted" = no */
  /* "send (echo, v)" = yes */
  recordSender = 0;
  sendEcho = 1;
  goto Ldone;
L73:;
  /* "kind of message" = (echo, v) */
  /* "record sender accepted" = no */
  /* "send (echo, v)" = yes */
  recordSender = 0;
  sendEcho = 1;
  goto Ldone;
L70:;
  /* "READY suppress mask covers all n" = no */
  /* "retry (ready, v)" = yes */
  retryReady = 1;
  goto L72;
L64:;
  /* "ready-count(v) >= 2t+1" = no */
  goto L66;
L61:;
  /* "have sent ready" = no */
  /* "retry (ready, v)" = no */
  retryReady = 0;
  if (rdGe2TPlus1 == 0)
    goto L79;
  /* "ready-count(v) >= 2t+1" = yes */
L81:;
  if (rdGeTPlus1 == 0)
    goto L82;
  /* "ready-count(v) >= t+1" = yes */
  /* "send (echo, v)" = yes */
  sendEcho = 1;
  if (readyMaskFull == 0)
    goto L85;
  /* "READY suppress mask covers all n" = yes */
L87:;
  if (type == BRACHA87_ECHO)
    goto L50;
L89:;
  if (type == BRACHA87_INITIAL)
    goto L53;
  goto L54;
L85:;
  /* "READY suppress mask covers all n" = no */
  goto L87;
L82:;
  /* "ready-count(v) >= t+1" = no */
  if (readyMaskFull == 0)
    goto L91;
  /* "READY suppress mask covers all n" = yes */
L93:;
  if (type == BRACHA87_ECHO)
    goto L94;
L95:;
  if (type == BRACHA87_INITIAL)
    goto L97;
  /* "kind of message" = (ready, v) */
  /* "record sender accepted" = yes */
  /* "send (echo, v)" = no */
  /* "send (ready, v)" = no */
  recordSender = 1;
  sendEcho = 0;
  sendReady = 0;
  goto Ldone;
L97:;
  /* "kind of message" = (initial, v) */
  /* "record sender accepted" = no */
  /* "send (echo, v)" = yes */
  /* "send (ready, v)" = no */
  recordSender = 0;
  sendEcho = 1;
  sendReady = 0;
  goto Ldone;
L94:;
  /* "kind of message" = (echo, v) */
  /* "record sender accepted" = no */
  /* "send (echo, v)" = yes */
  /* "send (ready, v)" = yes */
  recordSender = 0;
  sendEcho = 1;
  sendReady = 1;
  goto Ldone;
L91:;
  /* "READY suppress mask covers all n" = no */
  goto L93;
L79:;
  /* "ready-count(v) >= 2t+1" = no */
  goto L81;
L17:;
  /* "have accepted" = no */
L99:;
  if (haveEchoed == 0)
    goto L100;
  /* "have echoed" = yes */
  /* "retry (echo, v)" = yes */
  /* "send (echo, v)" = no */
  retryEcho = 1;
  sendEcho = 0;
  if (haveSentReady == 0)
    goto L103;
L104:;
  /* "have sent ready" = yes */
  /* "send (ready, v)" = no */
  sendReady = 0;
  if (rdGe2TPlus1 == 0)
    goto L106;
  /* "ready-count(v) >= 2t+1" = yes */
  if (rdGeTPlus1 == 0)
    goto L109;
  /* "ready-count(v) >= t+1" = yes */
L111:;
  if (readyMaskFull == 0)
    goto L112;
  /* "READY suppress mask covers all n" = yes */
  /* "retry (ready, v)" = no */
  retryReady = 0;
L114:;
  if (type == BRACHA87_ECHO)
    goto L115;
L117:;
  if (type == BRACHA87_INITIAL)
    goto L118;
  /* "accept(v)" = yes */
  /* "kind of message" = (ready, v) */
  /* "record sender accepted" = yes */
  acceptV = 1;
  recordSender = 1;
  goto Ldone;
L118:;
  /* "accept(v)" = no */
  /* "kind of message" = (initial, v) */
  /* "record sender accepted" = no */
  acceptV = 0;
  recordSender = 0;
  goto Ldone;
L115:;
  /* "accept(v)" = no */
  /* "kind of message" = (echo, v) */
  /* "record sender accepted" = no */
  acceptV = 0;
  recordSender = 0;
  goto Ldone;
L112:;
  /* "READY suppress mask covers all n" = no */
  /* "retry (ready, v)" = yes */
  retryReady = 1;
  goto L114;
L109:;
  /* "ready-count(v) >= t+1" = no */
  goto L111;
L106:;
  /* "accept(v)" = no */
  /* "ready-count(v) >= 2t+1" = no */
  acceptV = 0;
  goto L28;
L103:;
  /* "have sent ready" = no */
  /* "retry (ready, v)" = no */
  retryReady = 0;
  if (rdGe2TPlus1 == 0)
    goto L121;
  /* "ready-count(v) >= 2t+1" = yes */
  if (rdGeTPlus1 == 0)
    goto L124;
  /* "ready-count(v) >= t+1" = yes */
  if (readyMaskFull == 0)
    goto L127;
  /* "READY suppress mask covers all n" = yes */
L129:;
  if (type == BRACHA87_ECHO)
    goto L130;
L131:;
  if (type == BRACHA87_INITIAL)
    goto L133;
L134:;
  /* "accept(v)" = yes */
  /* "kind of message" = (ready, v) */
  /* "record sender accepted" = yes */
  /* "send (ready, v)" = yes */
  acceptV = 1;
  recordSender = 1;
  sendReady = 1;
  goto Ldone;
L133:;
  /* "accept(v)" = no */
  /* "kind of message" = (initial, v) */
  /* "record sender accepted" = no */
  /* "send (ready, v)" = no */
  acceptV = 0;
  recordSender = 0;
  sendReady = 0;
  goto Ldone;
L130:;
  /* "accept(v)" = no */
  /* "kind of message" = (echo, v) */
  /* "record sender accepted" = no */
  /* "send (ready, v)" = yes */
  acceptV = 0;
  recordSender = 0;
  sendReady = 1;
  goto Ldone;
L127:;
  /* "READY suppress mask covers all n" = no */
  goto L129;
L124:;
  /* "ready-count(v) >= t+1" = no */
  if (readyMaskFull == 0)
    goto L136;
  /* "READY suppress mask covers all n" = yes */
L138:;
  if (type == BRACHA87_ECHO)
    goto L130;
  /* "accept(v)" = no */
  /* "send (ready, v)" = no */
  acceptV = 0;
  sendReady = 0;
  goto L37;
L136:;
  /* "READY suppress mask covers all n" = no */
  goto L138;
L121:;
  /* "accept(v)" = no */
  /* "ready-count(v) >= 2t+1" = no */
  acceptV = 0;
  goto L43;
L100:;
  /* "have echoed" = no */
  /* "retry (echo, v)" = no */
  retryEcho = 0;
  if (haveSentReady == 0)
    goto L141;
  /* "have sent ready" = yes */
  /* "send (ready, v)" = no */
  sendReady = 0;
  if (rdGe2TPlus1 == 0)
    goto L144;
  /* "ready-count(v) >= 2t+1" = yes */
  if (rdGeTPlus1 == 0)
    goto L147;
  /* "ready-count(v) >= t+1" = yes */
  /* "send (echo, v)" = yes */
  sendEcho = 1;
  goto L111;
L147:;
  /* "ready-count(v) >= t+1" = no */
  if (readyMaskFull == 0)
    goto L150;
  /* "READY suppress mask covers all n" = yes */
  /* "retry (ready, v)" = no */
  retryReady = 0;
L152:;
  if (type == BRACHA87_ECHO)
    goto L153;
L154:;
  if (type == BRACHA87_INITIAL)
    goto L156;
  /* "accept(v)" = yes */
  /* "kind of message" = (ready, v) */
  /* "record sender accepted" = yes */
  /* "send (echo, v)" = no */
  acceptV = 1;
  recordSender = 1;
  sendEcho = 0;
  goto Ldone;
L156:;
  /* "accept(v)" = no */
  /* "kind of message" = (initial, v) */
  /* "record sender accepted" = no */
  /* "send (echo, v)" = yes */
  acceptV = 0;
  recordSender = 0;
  sendEcho = 1;
  goto Ldone;
L153:;
  /* "accept(v)" = no */
  /* "kind of message" = (echo, v) */
  /* "record sender accepted" = no */
  /* "send (echo, v)" = yes */
  acceptV = 0;
  recordSender = 0;
  sendEcho = 1;
  goto Ldone;
L150:;
  /* "READY suppress mask covers all n" = no */
  /* "retry (ready, v)" = yes */
  retryReady = 1;
  goto L152;
L144:;
  /* "accept(v)" = no */
  /* "ready-count(v) >= 2t+1" = no */
  acceptV = 0;
  goto L66;
L141:;
  /* "have sent ready" = no */
  /* "retry (ready, v)" = no */
  retryReady = 0;
  if (rdGe2TPlus1 == 0)
    goto L159;
  /* "ready-count(v) >= 2t+1" = yes */
  if (rdGeTPlus1 == 0)
    goto L162;
  /* "ready-count(v) >= t+1" = yes */
  /* "send (echo, v)" = yes */
  sendEcho = 1;
  if (readyMaskFull == 0)
    goto L165;
  /* "READY suppress mask covers all n" = yes */
L167:;
  if (type == BRACHA87_ECHO)
    goto L130;
L169:;
  if (type == BRACHA87_INITIAL)
    goto L133;
  goto L134;
L165:;
  /* "READY suppress mask covers all n" = no */
  goto L167;
L162:;
  /* "ready-count(v) >= t+1" = no */
  if (readyMaskFull == 0)
    goto L171;
  /* "READY suppress mask covers all n" = yes */
L173:;
  if (type == BRACHA87_ECHO)
    goto L174;
L175:;
  if (type == BRACHA87_INITIAL)
    goto L177;
  /* "accept(v)" = no */
  /* "kind of message" = (ready, v) */
  /* "record sender accepted" = yes */
  /* "send (echo, v)" = no */
  /* "send (ready, v)" = no */
  acceptV = 0;
  recordSender = 1;
  sendEcho = 0;
  sendReady = 0;
  goto Ldone;
L177:;
  /* "accept(v)" = no */
  /* "kind of message" = (initial, v) */
  /* "record sender accepted" = no */
  /* "send (echo, v)" = yes */
  /* "send (ready, v)" = no */
  acceptV = 0;
  recordSender = 0;
  sendEcho = 1;
  sendReady = 0;
  goto Ldone;
L174:;
  /* "accept(v)" = no */
  /* "kind of message" = (echo, v) */
  /* "record sender accepted" = no */
  /* "send (echo, v)" = yes */
  /* "send (ready, v)" = yes */
  acceptV = 0;
  recordSender = 0;
  sendEcho = 1;
  sendReady = 1;
  goto Ldone;
L171:;
  /* "READY suppress mask covers all n" = no */
  goto L173;
L159:;
  /* "accept(v)" = no */
  /* "ready-count(v) >= 2t+1" = no */
  acceptV = 0;
  goto L81;
L14:;
  /* "echo-count(v) > (n+t)/2" = no */
  if (haveAccepted == 0)
    goto L180;
  /* "accept(v)" = no */
  /* "have accepted" = yes */
  /* "retry (echo, v)" = no */
  acceptV = 0;
  retryEcho = 0;
L182:;
  if (haveEchoed == 0)
    goto L183;
  /* "have echoed" = yes */
  /* "send (echo, v)" = no */
  sendEcho = 0;
  if (haveSentReady == 0)
    goto L186;
  goto L24;
L186:;
  /* "have sent ready" = no */
  /* "retry (ready, v)" = no */
  retryReady = 0;
  if (rdGe2TPlus1 == 0)
    goto L188;
  /* "ready-count(v) >= 2t+1" = yes */
L190:;
  if (rdGeTPlus1 == 0)
    goto L191;
  /* "ready-count(v) >= t+1" = yes */
  if (readyMaskFull == 0)
    goto L194;
  /* "READY suppress mask covers all n" = yes */
L196:;
  if (type == BRACHA87_ECHO)
    goto L197;
  goto L51;
L197:;
  /* "kind of message" = (echo, v) */
  /* "record sender accepted" = no */
  /* "send (ready, v)" = no */
  recordSender = 0;
  sendReady = 0;
  goto Ldone;
L194:;
  /* "READY suppress mask covers all n" = no */
  goto L196;
L191:;
  /* "ready-count(v) >= t+1" = no */
  /* "send (ready, v)" = no */
  sendReady = 0;
L198:;
  if (readyMaskFull == 0)
    goto L199;
  /* "READY suppress mask covers all n" = yes */
  goto L34;
L199:;
  /* "READY suppress mask covers all n" = no */
  goto L34;
L188:;
  /* "ready-count(v) >= 2t+1" = no */
  goto L190;
L183:;
  /* "have echoed" = no */
  if (haveSentReady == 0)
    goto L202;
  /* "have sent ready" = yes */
  /* "send (ready, v)" = no */
  sendReady = 0;
  if (rdGe2TPlus1 == 0)
    goto L205;
  /* "ready-count(v) >= 2t+1" = yes */
L207:;
  if (rdGeTPlus1 == 0)
    goto L208;
  /* "ready-count(v) >= t+1" = yes */
  if (readyMaskFull == 0)
    goto L211;
  /* "READY suppress mask covers all n" = yes */
  /* "retry (ready, v)" = no */
  retryReady = 0;
L213:;
  if (type == BRACHA87_ECHO)
    goto L214;
  /* "send (echo, v)" = yes */
  sendEcho = 1;
  goto L37;
L214:;
  /* "kind of message" = (echo, v) */
  /* "record sender accepted" = no */
  /* "send (echo, v)" = no */
  recordSender = 0;
  sendEcho = 0;
  goto Ldone;
L211:;
  /* "READY suppress mask covers all n" = no */
  /* "retry (ready, v)" = yes */
  retryReady = 1;
  goto L213;
L208:;
  /* "ready-count(v) >= t+1" = no */
  if (readyMaskFull == 0)
    goto L217;
  /* "READY suppress mask covers all n" = yes */
  /* "retry (ready, v)" = no */
  retryReady = 0;
L219:;
  if (type == BRACHA87_ECHO)
    goto L214;
  goto L74;
L217:;
  /* "READY suppress mask covers all n" = no */
  /* "retry (ready, v)" = yes */
  retryReady = 1;
  goto L219;
L205:;
  /* "ready-count(v) >= 2t+1" = no */
  goto L207;
L202:;
  /* "have sent ready" = no */
  /* "retry (ready, v)" = no */
  retryReady = 0;
  if (rdGe2TPlus1 == 0)
    goto L221;
  /* "ready-count(v) >= 2t+1" = yes */
L223:;
  if (rdGeTPlus1 == 0)
    goto L224;
  /* "ready-count(v) >= t+1" = yes */
  if (readyMaskFull == 0)
    goto L227;
  /* "READY suppress mask covers all n" = yes */
L229:;
  if (type == BRACHA87_ECHO)
    goto L230;
  /* "send (echo, v)" = yes */
  sendEcho = 1;
  goto L89;
L230:;
  /* "kind of message" = (echo, v) */
  /* "record sender accepted" = no */
  /* "send (echo, v)" = no */
  /* "send (ready, v)" = no */
  recordSender = 0;
  sendEcho = 0;
  sendReady = 0;
  goto Ldone;
L227:;
  /* "READY suppress mask covers all n" = no */
  goto L229;
L224:;
  /* "ready-count(v) >= t+1" = no */
  if (readyMaskFull == 0)
    goto L233;
  /* "READY suppress mask covers all n" = yes */
L235:;
  if (type == BRACHA87_ECHO)
    goto L230;
  goto L95;
L233:;
  /* "READY suppress mask covers all n" = no */
  goto L235;
L221:;
  /* "ready-count(v) >= 2t+1" = no */
  goto L223;
L180:;
  /* "have accepted" = no */
L236:;
  if (haveEchoed == 0)
    goto L237;
  /* "have echoed" = yes */
  /* "retry (echo, v)" = yes */
  /* "send (echo, v)" = no */
  retryEcho = 1;
  sendEcho = 0;
  if (haveSentReady == 0)
    goto L240;
  goto L104;
L240:;
  /* "have sent ready" = no */
  /* "retry (ready, v)" = no */
  retryReady = 0;
  if (rdGe2TPlus1 == 0)
    goto L242;
  /* "ready-count(v) >= 2t+1" = yes */
  if (rdGeTPlus1 == 0)
    goto L245;
  /* "ready-count(v) >= t+1" = yes */
  if (readyMaskFull == 0)
    goto L248;
  /* "READY suppress mask covers all n" = yes */
L250:;
  if (type == BRACHA87_ECHO)
    goto L251;
  goto L131;
L251:;
  /* "accept(v)" = no */
  /* "kind of message" = (echo, v) */
  /* "record sender accepted" = no */
  /* "send (ready, v)" = no */
  acceptV = 0;
  recordSender = 0;
  sendReady = 0;
  goto Ldone;
L248:;
  /* "READY suppress mask covers all n" = no */
  goto L250;
L245:;
  /* "accept(v)" = no */
  /* "ready-count(v) >= t+1" = no */
  /* "send (ready, v)" = no */
  acceptV = 0;
  sendReady = 0;
  goto L198;
L242:;
  /* "accept(v)" = no */
  /* "ready-count(v) >= 2t+1" = no */
  acceptV = 0;
  goto L190;
L237:;
  /* "have echoed" = no */
  /* "retry (echo, v)" = no */
  retryEcho = 0;
  if (haveSentReady == 0)
    goto L253;
  /* "have sent ready" = yes */
  /* "send (ready, v)" = no */
  sendReady = 0;
  if (rdGe2TPlus1 == 0)
    goto L256;
  /* "ready-count(v) >= 2t+1" = yes */
  if (rdGeTPlus1 == 0)
    goto L259;
  /* "ready-count(v) >= t+1" = yes */
  if (readyMaskFull == 0)
    goto L262;
  /* "READY suppress mask covers all n" = yes */
  /* "retry (ready, v)" = no */
  retryReady = 0;
L264:;
  if (type == BRACHA87_ECHO)
    goto L265;
  /* "send (echo, v)" = yes */
  sendEcho = 1;
  goto L117;
L265:;
  /* "accept(v)" = no */
  /* "kind of message" = (echo, v) */
  /* "record sender accepted" = no */
  /* "send (echo, v)" = no */
  acceptV = 0;
  recordSender = 0;
  sendEcho = 0;
  goto Ldone;
L262:;
  /* "READY suppress mask covers all n" = no */
  /* "retry (ready, v)" = yes */
  retryReady = 1;
  goto L264;
L259:;
  /* "ready-count(v) >= t+1" = no */
  if (readyMaskFull == 0)
    goto L268;
  /* "READY suppress mask covers all n" = yes */
  /* "retry (ready, v)" = no */
  retryReady = 0;
L270:;
  if (type == BRACHA87_ECHO)
    goto L265;
  goto L154;
L268:;
  /* "READY suppress mask covers all n" = no */
  /* "retry (ready, v)" = yes */
  retryReady = 1;
  goto L270;
L256:;
  /* "accept(v)" = no */
  /* "ready-count(v) >= 2t+1" = no */
  acceptV = 0;
  goto L207;
L253:;
  /* "have sent ready" = no */
  /* "retry (ready, v)" = no */
  retryReady = 0;
  if (rdGe2TPlus1 == 0)
    goto L272;
  /* "ready-count(v) >= 2t+1" = yes */
  if (rdGeTPlus1 == 0)
    goto L275;
  /* "ready-count(v) >= t+1" = yes */
  if (readyMaskFull == 0)
    goto L278;
  /* "READY suppress mask covers all n" = yes */
L280:;
  if (type == BRACHA87_ECHO)
    goto L281;
  /* "send (echo, v)" = yes */
  sendEcho = 1;
  goto L169;
L281:;
  /* "accept(v)" = no */
  /* "kind of message" = (echo, v) */
  /* "record sender accepted" = no */
  /* "send (echo, v)" = no */
  /* "send (ready, v)" = no */
  acceptV = 0;
  recordSender = 0;
  sendEcho = 0;
  sendReady = 0;
  goto Ldone;
L278:;
  /* "READY suppress mask covers all n" = no */
  goto L280;
L275:;
  /* "ready-count(v) >= t+1" = no */
  if (readyMaskFull == 0)
    goto L284;
  /* "READY suppress mask covers all n" = yes */
L286:;
  if (type == BRACHA87_ECHO)
    goto L281;
  goto L175;
L284:;
  /* "READY suppress mask covers all n" = no */
  goto L286;
L272:;
  /* "accept(v)" = no */
  /* "ready-count(v) >= 2t+1" = no */
  acceptV = 0;
  goto L223;
L11:;
  /* "carries RECEIVED" = no */
  if (ecGtHalfNT == 0)
    goto L288;
  /* "echo-count(v) > (n+t)/2" = yes */
  if (haveAccepted == 0)
    goto L291;
  /* "accept(v)" = no */
  /* "have accepted" = yes */
  /* "retry (echo, v)" = no */
  acceptV = 0;
  retryEcho = 0;
L293:;
  if (haveEchoed == 0)
    goto L294;
  /* "have echoed" = yes */
  /* "send (echo, v)" = no */
  sendEcho = 0;
  if (haveSentReady == 0)
    goto L297;
L298:;
  /* "have sent ready" = yes */
  /* "send (ready, v)" = no */
  sendReady = 0;
  if (rdGe2TPlus1 == 0)
    goto L300;
  /* "ready-count(v) >= 2t+1" = yes */
L302:;
  if (rdGeTPlus1 == 0)
    goto L303;
  /* "ready-count(v) >= t+1" = yes */
L305:;
  if (readyMaskFull == 0)
    goto L306;
  /* "READY suppress mask covers all n" = yes */
  /* "retry (ready, v)" = no */
  retryReady = 0;
L308:;
  if (type == BRACHA87_ECHO)
    goto L309;
L311:;
  if (type == BRACHA87_INITIAL)
    goto L312;
  /* "arm re-send to sender" = yes */
  /* "kind of message" = (ready, v) */
  /* "record sender accepted" = yes */
  armSender = 1;
  recordSender = 1;
  goto Ldone;
L312:;
  /* "arm re-send to sender" = no */
  /* "kind of message" = (initial, v) */
  /* "record sender accepted" = no */
  armSender = 0;
  recordSender = 0;
  goto Ldone;
L309:;
  /* "arm re-send to sender" = no */
  /* "kind of message" = (echo, v) */
  /* "record sender accepted" = no */
  armSender = 0;
  recordSender = 0;
  goto Ldone;
L306:;
  /* "READY suppress mask covers all n" = no */
  /* "retry (ready, v)" = yes */
  retryReady = 1;
  goto L308;
L303:;
  /* "ready-count(v) >= t+1" = no */
  goto L305;
L300:;
  /* "ready-count(v) >= 2t+1" = no */
  goto L302;
L297:;
  /* "have sent ready" = no */
  /* "retry (ready, v)" = no */
  retryReady = 0;
  if (rdGe2TPlus1 == 0)
    goto L315;
  /* "ready-count(v) >= 2t+1" = yes */
L317:;
  if (rdGeTPlus1 == 0)
    goto L318;
  /* "ready-count(v) >= t+1" = yes */
  if (readyMaskFull == 0)
    goto L321;
  /* "READY suppress mask covers all n" = yes */
L323:;
  if (type == BRACHA87_ECHO)
    goto L324;
L325:;
  if (type == BRACHA87_INITIAL)
    goto L327;
L328:;
  /* "arm re-send to sender" = yes */
  /* "kind of message" = (ready, v) */
  /* "record sender accepted" = yes */
  /* "send (ready, v)" = yes */
  armSender = 1;
  recordSender = 1;
  sendReady = 1;
  goto Ldone;
L327:;
  /* "arm re-send to sender" = no */
  /* "kind of message" = (initial, v) */
  /* "record sender accepted" = no */
  /* "send (ready, v)" = no */
  armSender = 0;
  recordSender = 0;
  sendReady = 0;
  goto Ldone;
L324:;
  /* "arm re-send to sender" = no */
  /* "kind of message" = (echo, v) */
  /* "record sender accepted" = no */
  /* "send (ready, v)" = yes */
  armSender = 0;
  recordSender = 0;
  sendReady = 1;
  goto Ldone;
L321:;
  /* "READY suppress mask covers all n" = no */
  goto L323;
L318:;
  /* "ready-count(v) >= t+1" = no */
  if (readyMaskFull == 0)
    goto L330;
  /* "READY suppress mask covers all n" = yes */
L332:;
  if (type == BRACHA87_ECHO)
    goto L324;
  /* "send (ready, v)" = no */
  sendReady = 0;
  goto L311;
L330:;
  /* "READY suppress mask covers all n" = no */
  goto L332;
L315:;
  /* "ready-count(v) >= 2t+1" = no */
  goto L317;
L294:;
  /* "have echoed" = no */
  if (haveSentReady == 0)
    goto L335;
  /* "have sent ready" = yes */
  /* "send (ready, v)" = no */
  sendReady = 0;
  if (rdGe2TPlus1 == 0)
    goto L338;
  /* "ready-count(v) >= 2t+1" = yes */
L340:;
  if (rdGeTPlus1 == 0)
    goto L341;
  /* "ready-count(v) >= t+1" = yes */
  /* "send (echo, v)" = yes */
  sendEcho = 1;
  goto L305;
L341:;
  /* "ready-count(v) >= t+1" = no */
  if (readyMaskFull == 0)
    goto L344;
  /* "READY suppress mask covers all n" = yes */
  /* "retry (ready, v)" = no */
  retryReady = 0;
L346:;
  if (type == BRACHA87_ECHO)
    goto L347;
L348:;
  if (type == BRACHA87_INITIAL)
    goto L350;
  /* "arm re-send to sender" = yes */
  /* "kind of message" = (ready, v) */
  /* "record sender accepted" = yes */
  /* "send (echo, v)" = no */
  armSender = 1;
  recordSender = 1;
  sendEcho = 0;
  goto Ldone;
L350:;
  /* "arm re-send to sender" = no */
  /* "kind of message" = (initial, v) */
  /* "record sender accepted" = no */
  /* "send (echo, v)" = yes */
  armSender = 0;
  recordSender = 0;
  sendEcho = 1;
  goto Ldone;
L347:;
  /* "arm re-send to sender" = no */
  /* "kind of message" = (echo, v) */
  /* "record sender accepted" = no */
  /* "send (echo, v)" = yes */
  armSender = 0;
  recordSender = 0;
  sendEcho = 1;
  goto Ldone;
L344:;
  /* "READY suppress mask covers all n" = no */
  /* "retry (ready, v)" = yes */
  retryReady = 1;
  goto L346;
L338:;
  /* "ready-count(v) >= 2t+1" = no */
  goto L340;
L335:;
  /* "have sent ready" = no */
  /* "retry (ready, v)" = no */
  retryReady = 0;
  if (rdGe2TPlus1 == 0)
    goto L353;
  /* "ready-count(v) >= 2t+1" = yes */
L355:;
  if (rdGeTPlus1 == 0)
    goto L356;
  /* "ready-count(v) >= t+1" = yes */
  /* "send (echo, v)" = yes */
  sendEcho = 1;
  if (readyMaskFull == 0)
    goto L359;
  /* "READY suppress mask covers all n" = yes */
L361:;
  if (type == BRACHA87_ECHO)
    goto L324;
L363:;
  if (type == BRACHA87_INITIAL)
    goto L327;
  goto L328;
L359:;
  /* "READY suppress mask covers all n" = no */
  goto L361;
L356:;
  /* "ready-count(v) >= t+1" = no */
  if (readyMaskFull == 0)
    goto L365;
  /* "READY suppress mask covers all n" = yes */
L367:;
  if (type == BRACHA87_ECHO)
    goto L368;
L369:;
  if (type == BRACHA87_INITIAL)
    goto L371;
  /* "arm re-send to sender" = yes */
  /* "kind of message" = (ready, v) */
  /* "record sender accepted" = yes */
  /* "send (echo, v)" = no */
  /* "send (ready, v)" = no */
  armSender = 1;
  recordSender = 1;
  sendEcho = 0;
  sendReady = 0;
  goto Ldone;
L371:;
  /* "arm re-send to sender" = no */
  /* "kind of message" = (initial, v) */
  /* "record sender accepted" = no */
  /* "send (echo, v)" = yes */
  /* "send (ready, v)" = no */
  armSender = 0;
  recordSender = 0;
  sendEcho = 1;
  sendReady = 0;
  goto Ldone;
L368:;
  /* "arm re-send to sender" = no */
  /* "kind of message" = (echo, v) */
  /* "record sender accepted" = no */
  /* "send (echo, v)" = yes */
  /* "send (ready, v)" = yes */
  armSender = 0;
  recordSender = 0;
  sendEcho = 1;
  sendReady = 1;
  goto Ldone;
L365:;
  /* "READY suppress mask covers all n" = no */
  goto L367;
L353:;
  /* "ready-count(v) >= 2t+1" = no */
  goto L355;
L291:;
  /* "have accepted" = no */
L373:;
  if (haveEchoed == 0)
    goto L374;
  /* "have echoed" = yes */
  /* "retry (echo, v)" = yes */
  /* "send (echo, v)" = no */
  retryEcho = 1;
  sendEcho = 0;
  if (haveSentReady == 0)
    goto L377;
L378:;
  /* "have sent ready" = yes */
  /* "send (ready, v)" = no */
  sendReady = 0;
  if (rdGe2TPlus1 == 0)
    goto L380;
  /* "ready-count(v) >= 2t+1" = yes */
  if (rdGeTPlus1 == 0)
    goto L383;
  /* "ready-count(v) >= t+1" = yes */
L385:;
  if (readyMaskFull == 0)
    goto L386;
  /* "READY suppress mask covers all n" = yes */
  /* "retry (ready, v)" = no */
  retryReady = 0;
L388:;
  if (type == BRACHA87_ECHO)
    goto L389;
L391:;
  if (type == BRACHA87_INITIAL)
    goto L392;
  /* "accept(v)" = yes */
  /* "arm re-send to sender" = yes */
  /* "kind of message" = (ready, v) */
  /* "record sender accepted" = yes */
  acceptV = 1;
  armSender = 1;
  recordSender = 1;
  goto Ldone;
L392:;
  /* "accept(v)" = no */
  /* "arm re-send to sender" = no */
  /* "kind of message" = (initial, v) */
  /* "record sender accepted" = no */
  acceptV = 0;
  armSender = 0;
  recordSender = 0;
  goto Ldone;
L389:;
  /* "accept(v)" = no */
  /* "arm re-send to sender" = no */
  /* "kind of message" = (echo, v) */
  /* "record sender accepted" = no */
  acceptV = 0;
  armSender = 0;
  recordSender = 0;
  goto Ldone;
L386:;
  /* "READY suppress mask covers all n" = no */
  /* "retry (ready, v)" = yes */
  retryReady = 1;
  goto L388;
L383:;
  /* "ready-count(v) >= t+1" = no */
  goto L385;
L380:;
  /* "accept(v)" = no */
  /* "arm re-send to sender" = no */
  /* "ready-count(v) >= 2t+1" = no */
  acceptV = 0;
  armSender = 0;
  goto L28;
L377:;
  /* "have sent ready" = no */
  /* "retry (ready, v)" = no */
  retryReady = 0;
  if (rdGe2TPlus1 == 0)
    goto L395;
  /* "ready-count(v) >= 2t+1" = yes */
  if (rdGeTPlus1 == 0)
    goto L398;
  /* "ready-count(v) >= t+1" = yes */
  if (readyMaskFull == 0)
    goto L401;
  /* "READY suppress mask covers all n" = yes */
L403:;
  if (type == BRACHA87_ECHO)
    goto L404;
L405:;
  if (type == BRACHA87_INITIAL)
    goto L407;
L408:;
  /* "accept(v)" = yes */
  /* "arm re-send to sender" = yes */
  /* "kind of message" = (ready, v) */
  /* "record sender accepted" = yes */
  /* "send (ready, v)" = yes */
  acceptV = 1;
  armSender = 1;
  recordSender = 1;
  sendReady = 1;
  goto Ldone;
L407:;
  /* "accept(v)" = no */
  /* "arm re-send to sender" = no */
  /* "kind of message" = (initial, v) */
  /* "record sender accepted" = no */
  /* "send (ready, v)" = no */
  acceptV = 0;
  armSender = 0;
  recordSender = 0;
  sendReady = 0;
  goto Ldone;
L404:;
  /* "accept(v)" = no */
  /* "arm re-send to sender" = no */
  /* "kind of message" = (echo, v) */
  /* "record sender accepted" = no */
  /* "send (ready, v)" = yes */
  acceptV = 0;
  armSender = 0;
  recordSender = 0;
  sendReady = 1;
  goto Ldone;
L401:;
  /* "READY suppress mask covers all n" = no */
  goto L403;
L398:;
  /* "ready-count(v) >= t+1" = no */
  if (readyMaskFull == 0)
    goto L410;
  /* "READY suppress mask covers all n" = yes */
L412:;
  if (type == BRACHA87_ECHO)
    goto L404;
  /* "accept(v)" = no */
  /* "arm re-send to sender" = no */
  /* "send (ready, v)" = no */
  acceptV = 0;
  armSender = 0;
  sendReady = 0;
  goto L37;
L410:;
  /* "READY suppress mask covers all n" = no */
  goto L412;
L395:;
  /* "accept(v)" = no */
  /* "arm re-send to sender" = no */
  /* "ready-count(v) >= 2t+1" = no */
  acceptV = 0;
  armSender = 0;
  goto L43;
L374:;
  /* "have echoed" = no */
  /* "retry (echo, v)" = no */
  retryEcho = 0;
  if (haveSentReady == 0)
    goto L415;
  /* "have sent ready" = yes */
  /* "send (ready, v)" = no */
  sendReady = 0;
  if (rdGe2TPlus1 == 0)
    goto L418;
  /* "ready-count(v) >= 2t+1" = yes */
  if (rdGeTPlus1 == 0)
    goto L421;
  /* "ready-count(v) >= t+1" = yes */
  /* "send (echo, v)" = yes */
  sendEcho = 1;
  goto L385;
L421:;
  /* "ready-count(v) >= t+1" = no */
  if (readyMaskFull == 0)
    goto L424;
  /* "READY suppress mask covers all n" = yes */
  /* "retry (ready, v)" = no */
  retryReady = 0;
L426:;
  if (type == BRACHA87_ECHO)
    goto L427;
L428:;
  if (type == BRACHA87_INITIAL)
    goto L430;
  /* "accept(v)" = yes */
  /* "arm re-send to sender" = yes */
  /* "kind of message" = (ready, v) */
  /* "record sender accepted" = yes */
  /* "send (echo, v)" = no */
  acceptV = 1;
  armSender = 1;
  recordSender = 1;
  sendEcho = 0;
  goto Ldone;
L430:;
  /* "accept(v)" = no */
  /* "arm re-send to sender" = no */
  /* "kind of message" = (initial, v) */
  /* "record sender accepted" = no */
  /* "send (echo, v)" = yes */
  acceptV = 0;
  armSender = 0;
  recordSender = 0;
  sendEcho = 1;
  goto Ldone;
L427:;
  /* "accept(v)" = no */
  /* "arm re-send to sender" = no */
  /* "kind of message" = (echo, v) */
  /* "record sender accepted" = no */
  /* "send (echo, v)" = yes */
  acceptV = 0;
  armSender = 0;
  recordSender = 0;
  sendEcho = 1;
  goto Ldone;
L424:;
  /* "READY suppress mask covers all n" = no */
  /* "retry (ready, v)" = yes */
  retryReady = 1;
  goto L426;
L418:;
  /* "accept(v)" = no */
  /* "arm re-send to sender" = no */
  /* "ready-count(v) >= 2t+1" = no */
  acceptV = 0;
  armSender = 0;
  goto L66;
L415:;
  /* "have sent ready" = no */
  /* "retry (ready, v)" = no */
  retryReady = 0;
  if (rdGe2TPlus1 == 0)
    goto L433;
  /* "ready-count(v) >= 2t+1" = yes */
  if (rdGeTPlus1 == 0)
    goto L436;
  /* "ready-count(v) >= t+1" = yes */
  /* "send (echo, v)" = yes */
  sendEcho = 1;
  if (readyMaskFull == 0)
    goto L439;
  /* "READY suppress mask covers all n" = yes */
L441:;
  if (type == BRACHA87_ECHO)
    goto L404;
L443:;
  if (type == BRACHA87_INITIAL)
    goto L407;
  goto L408;
L439:;
  /* "READY suppress mask covers all n" = no */
  goto L441;
L436:;
  /* "ready-count(v) >= t+1" = no */
  if (readyMaskFull == 0)
    goto L445;
  /* "READY suppress mask covers all n" = yes */
L447:;
  if (type == BRACHA87_ECHO)
    goto L448;
L449:;
  if (type == BRACHA87_INITIAL)
    goto L451;
  /* "accept(v)" = no */
  /* "arm re-send to sender" = no */
  /* "kind of message" = (ready, v) */
  /* "record sender accepted" = yes */
  /* "send (echo, v)" = no */
  /* "send (ready, v)" = no */
  acceptV = 0;
  armSender = 0;
  recordSender = 1;
  sendEcho = 0;
  sendReady = 0;
  goto Ldone;
L451:;
  /* "accept(v)" = no */
  /* "arm re-send to sender" = no */
  /* "kind of message" = (initial, v) */
  /* "record sender accepted" = no */
  /* "send (echo, v)" = yes */
  /* "send (ready, v)" = no */
  acceptV = 0;
  armSender = 0;
  recordSender = 0;
  sendEcho = 1;
  sendReady = 0;
  goto Ldone;
L448:;
  /* "accept(v)" = no */
  /* "arm re-send to sender" = no */
  /* "kind of message" = (echo, v) */
  /* "record sender accepted" = no */
  /* "send (echo, v)" = yes */
  /* "send (ready, v)" = yes */
  acceptV = 0;
  armSender = 0;
  recordSender = 0;
  sendEcho = 1;
  sendReady = 1;
  goto Ldone;
L445:;
  /* "READY suppress mask covers all n" = no */
  goto L447;
L433:;
  /* "accept(v)" = no */
  /* "arm re-send to sender" = no */
  /* "ready-count(v) >= 2t+1" = no */
  acceptV = 0;
  armSender = 0;
  goto L81;
L288:;
  /* "echo-count(v) > (n+t)/2" = no */
  if (haveAccepted == 0)
    goto L454;
  /* "accept(v)" = no */
  /* "have accepted" = yes */
  /* "retry (echo, v)" = no */
  acceptV = 0;
  retryEcho = 0;
L456:;
  if (haveEchoed == 0)
    goto L457;
  /* "have echoed" = yes */
  /* "send (echo, v)" = no */
  sendEcho = 0;
  if (haveSentReady == 0)
    goto L460;
  goto L298;
L460:;
  /* "have sent ready" = no */
  /* "retry (ready, v)" = no */
  retryReady = 0;
  if (rdGe2TPlus1 == 0)
    goto L462;
  /* "ready-count(v) >= 2t+1" = yes */
L464:;
  if (rdGeTPlus1 == 0)
    goto L465;
  /* "ready-count(v) >= t+1" = yes */
  if (readyMaskFull == 0)
    goto L468;
  /* "READY suppress mask covers all n" = yes */
L470:;
  if (type == BRACHA87_ECHO)
    goto L471;
  goto L325;
L471:;
  /* "arm re-send to sender" = no */
  /* "kind of message" = (echo, v) */
  /* "record sender accepted" = no */
  /* "send (ready, v)" = no */
  armSender = 0;
  recordSender = 0;
  sendReady = 0;
  goto Ldone;
L468:;
  /* "READY suppress mask covers all n" = no */
  goto L470;
L465:;
  /* "ready-count(v) >= t+1" = no */
  /* "send (ready, v)" = no */
  sendReady = 0;
  if (readyMaskFull == 0)
    goto L473;
  /* "READY suppress mask covers all n" = yes */
  goto L308;
L473:;
  /* "READY suppress mask covers all n" = no */
  goto L308;
L462:;
  /* "ready-count(v) >= 2t+1" = no */
  goto L464;
L457:;
  /* "have echoed" = no */
  if (haveSentReady == 0)
    goto L476;
  /* "have sent ready" = yes */
  /* "send (ready, v)" = no */
  sendReady = 0;
  if (rdGe2TPlus1 == 0)
    goto L479;
  /* "ready-count(v) >= 2t+1" = yes */
L481:;
  if (rdGeTPlus1 == 0)
    goto L482;
  /* "ready-count(v) >= t+1" = yes */
  if (readyMaskFull == 0)
    goto L485;
  /* "READY suppress mask covers all n" = yes */
  /* "retry (ready, v)" = no */
  retryReady = 0;
L487:;
  if (type == BRACHA87_ECHO)
    goto L488;
  /* "send (echo, v)" = yes */
  sendEcho = 1;
  goto L311;
L488:;
  /* "arm re-send to sender" = no */
  /* "kind of message" = (echo, v) */
  /* "record sender accepted" = no */
  /* "send (echo, v)" = no */
  armSender = 0;
  recordSender = 0;
  sendEcho = 0;
  goto Ldone;
L485:;
  /* "READY suppress mask covers all n" = no */
  /* "retry (ready, v)" = yes */
  retryReady = 1;
  goto L487;
L482:;
  /* "ready-count(v) >= t+1" = no */
  if (readyMaskFull == 0)
    goto L491;
  /* "READY suppress mask covers all n" = yes */
  /* "retry (ready, v)" = no */
  retryReady = 0;
L493:;
  if (type == BRACHA87_ECHO)
    goto L488;
  goto L348;
L491:;
  /* "READY suppress mask covers all n" = no */
  /* "retry (ready, v)" = yes */
  retryReady = 1;
  goto L493;
L479:;
  /* "ready-count(v) >= 2t+1" = no */
  goto L481;
L476:;
  /* "have sent ready" = no */
  /* "retry (ready, v)" = no */
  retryReady = 0;
  if (rdGe2TPlus1 == 0)
    goto L495;
  /* "ready-count(v) >= 2t+1" = yes */
L497:;
  if (rdGeTPlus1 == 0)
    goto L498;
  /* "ready-count(v) >= t+1" = yes */
  if (readyMaskFull == 0)
    goto L501;
  /* "READY suppress mask covers all n" = yes */
L503:;
  if (type == BRACHA87_ECHO)
    goto L504;
  /* "send (echo, v)" = yes */
  sendEcho = 1;
  goto L363;
L504:;
  /* "arm re-send to sender" = no */
  /* "kind of message" = (echo, v) */
  /* "record sender accepted" = no */
  /* "send (echo, v)" = no */
  /* "send (ready, v)" = no */
  armSender = 0;
  recordSender = 0;
  sendEcho = 0;
  sendReady = 0;
  goto Ldone;
L501:;
  /* "READY suppress mask covers all n" = no */
  goto L503;
L498:;
  /* "ready-count(v) >= t+1" = no */
  if (readyMaskFull == 0)
    goto L507;
  /* "READY suppress mask covers all n" = yes */
L509:;
  if (type == BRACHA87_ECHO)
    goto L504;
  goto L369;
L507:;
  /* "READY suppress mask covers all n" = no */
  goto L509;
L495:;
  /* "ready-count(v) >= 2t+1" = no */
  goto L497;
L454:;
  /* "have accepted" = no */
L510:;
  if (haveEchoed == 0)
    goto L511;
  /* "have echoed" = yes */
  /* "retry (echo, v)" = yes */
  /* "send (echo, v)" = no */
  retryEcho = 1;
  sendEcho = 0;
  if (haveSentReady == 0)
    goto L514;
  goto L378;
L514:;
  /* "have sent ready" = no */
  /* "retry (ready, v)" = no */
  retryReady = 0;
  if (rdGe2TPlus1 == 0)
    goto L516;
  /* "ready-count(v) >= 2t+1" = yes */
  if (rdGeTPlus1 == 0)
    goto L519;
  /* "ready-count(v) >= t+1" = yes */
  if (readyMaskFull == 0)
    goto L522;
  /* "READY suppress mask covers all n" = yes */
L524:;
  if (type == BRACHA87_ECHO)
    goto L525;
  goto L405;
L525:;
  /* "accept(v)" = no */
  /* "arm re-send to sender" = no */
  /* "kind of message" = (echo, v) */
  /* "record sender accepted" = no */
  /* "send (ready, v)" = no */
  acceptV = 0;
  armSender = 0;
  recordSender = 0;
  sendReady = 0;
  goto Ldone;
L522:;
  /* "READY suppress mask covers all n" = no */
  goto L524;
L519:;
  /* "accept(v)" = no */
  /* "arm re-send to sender" = no */
  /* "ready-count(v) >= t+1" = no */
  /* "send (ready, v)" = no */
  acceptV = 0;
  armSender = 0;
  sendReady = 0;
  goto L198;
L516:;
  /* "accept(v)" = no */
  /* "arm re-send to sender" = no */
  /* "ready-count(v) >= 2t+1" = no */
  acceptV = 0;
  armSender = 0;
  goto L190;
L511:;
  /* "have echoed" = no */
  /* "retry (echo, v)" = no */
  retryEcho = 0;
  if (haveSentReady == 0)
    goto L527;
  /* "have sent ready" = yes */
  /* "send (ready, v)" = no */
  sendReady = 0;
  if (rdGe2TPlus1 == 0)
    goto L530;
  /* "ready-count(v) >= 2t+1" = yes */
  if (rdGeTPlus1 == 0)
    goto L533;
  /* "ready-count(v) >= t+1" = yes */
  if (readyMaskFull == 0)
    goto L536;
  /* "READY suppress mask covers all n" = yes */
  /* "retry (ready, v)" = no */
  retryReady = 0;
L538:;
  if (type == BRACHA87_ECHO)
    goto L539;
  /* "send (echo, v)" = yes */
  sendEcho = 1;
  goto L391;
L539:;
  /* "accept(v)" = no */
  /* "arm re-send to sender" = no */
  /* "kind of message" = (echo, v) */
  /* "record sender accepted" = no */
  /* "send (echo, v)" = no */
  acceptV = 0;
  armSender = 0;
  recordSender = 0;
  sendEcho = 0;
  goto Ldone;
L536:;
  /* "READY suppress mask covers all n" = no */
  /* "retry (ready, v)" = yes */
  retryReady = 1;
  goto L538;
L533:;
  /* "ready-count(v) >= t+1" = no */
  if (readyMaskFull == 0)
    goto L542;
  /* "READY suppress mask covers all n" = yes */
  /* "retry (ready, v)" = no */
  retryReady = 0;
L544:;
  if (type == BRACHA87_ECHO)
    goto L539;
  goto L428;
L542:;
  /* "READY suppress mask covers all n" = no */
  /* "retry (ready, v)" = yes */
  retryReady = 1;
  goto L544;
L530:;
  /* "accept(v)" = no */
  /* "arm re-send to sender" = no */
  /* "ready-count(v) >= 2t+1" = no */
  acceptV = 0;
  armSender = 0;
  goto L207;
L527:;
  /* "have sent ready" = no */
  /* "retry (ready, v)" = no */
  retryReady = 0;
  if (rdGe2TPlus1 == 0)
    goto L546;
  /* "ready-count(v) >= 2t+1" = yes */
  if (rdGeTPlus1 == 0)
    goto L549;
  /* "ready-count(v) >= t+1" = yes */
  if (readyMaskFull == 0)
    goto L552;
  /* "READY suppress mask covers all n" = yes */
L554:;
  if (type == BRACHA87_ECHO)
    goto L555;
  /* "send (echo, v)" = yes */
  sendEcho = 1;
  goto L443;
L555:;
  /* "accept(v)" = no */
  /* "arm re-send to sender" = no */
  /* "kind of message" = (echo, v) */
  /* "record sender accepted" = no */
  /* "send (echo, v)" = no */
  /* "send (ready, v)" = no */
  acceptV = 0;
  armSender = 0;
  recordSender = 0;
  sendEcho = 0;
  sendReady = 0;
  goto Ldone;
L552:;
  /* "READY suppress mask covers all n" = no */
  goto L554;
L549:;
  /* "ready-count(v) >= t+1" = no */
  if (readyMaskFull == 0)
    goto L558;
  /* "READY suppress mask covers all n" = yes */
L560:;
  if (type == BRACHA87_ECHO)
    goto L555;
  goto L449;
L558:;
  /* "READY suppress mask covers all n" = no */
  goto L560;
L546:;
  /* "accept(v)" = no */
  /* "arm re-send to sender" = no */
  /* "ready-count(v) >= 2t+1" = no */
  acceptV = 0;
  armSender = 0;
  goto L223;
L8:;
  /* "carries ACCEPTED" = no */
  /* "record sender accepted" = no */
  recordSender = 0;
  if (annReceived == 0)
    goto L562;
  /* "arm re-send to sender" = no */
  /* "carries RECEIVED" = yes */
  armSender = 0;
  if (ecGtHalfNT == 0)
    goto L565;
  /* "echo-count(v) > (n+t)/2" = yes */
  if (haveAccepted == 0)
    goto L568;
  /* "accept(v)" = no */
  /* "have accepted" = yes */
  /* "retry (echo, v)" = no */
  acceptV = 0;
  retryEcho = 0;
L570:;
  if (haveEchoed == 0)
    goto L571;
  /* "have echoed" = yes */
  /* "send (echo, v)" = no */
  sendEcho = 0;
  if (haveSentReady == 0)
    goto L574;
L575:;
  /* "have sent ready" = yes */
  /* "send (ready, v)" = no */
  sendReady = 0;
  if (rdGe2TPlus1 == 0)
    goto L577;
  /* "ready-count(v) >= 2t+1" = yes */
L579:;
  if (rdGeTPlus1 == 0)
    goto L580;
  /* "ready-count(v) >= t+1" = yes */
L582:;
  if (readyMaskFull == 0)
    goto L583;
  /* "READY suppress mask covers all n" = yes */
  /* "retry (ready, v)" = no */
  retryReady = 0;
L585:;
  if (type == BRACHA87_ECHO)
    goto L586;
L588:;
  if (type == BRACHA87_INITIAL)
    goto L589;
  /* "kind of message" = (ready, v) */
  goto Ldone;
L589:;
  /* "kind of message" = (initial, v) */
  goto Ldone;
L586:;
  /* "kind of message" = (echo, v) */
  goto Ldone;
L583:;
  /* "READY suppress mask covers all n" = no */
  /* "retry (ready, v)" = yes */
  retryReady = 1;
  goto L585;
L580:;
  /* "ready-count(v) >= t+1" = no */
  goto L582;
L577:;
  /* "ready-count(v) >= 2t+1" = no */
  goto L579;
L574:;
  /* "have sent ready" = no */
  /* "retry (ready, v)" = no */
  retryReady = 0;
  if (rdGe2TPlus1 == 0)
    goto L592;
  /* "ready-count(v) >= 2t+1" = yes */
L594:;
  if (rdGeTPlus1 == 0)
    goto L595;
  /* "ready-count(v) >= t+1" = yes */
  if (readyMaskFull == 0)
    goto L598;
  /* "READY suppress mask covers all n" = yes */
L600:;
  if (type == BRACHA87_ECHO)
    goto L601;
L602:;
  if (type == BRACHA87_INITIAL)
    goto L604;
L605:;
  /* "kind of message" = (ready, v) */
  /* "send (ready, v)" = yes */
  sendReady = 1;
  goto Ldone;
L604:;
  /* "kind of message" = (initial, v) */
  /* "send (ready, v)" = no */
  sendReady = 0;
  goto Ldone;
L601:;
  /* "kind of message" = (echo, v) */
  /* "send (ready, v)" = yes */
  sendReady = 1;
  goto Ldone;
L598:;
  /* "READY suppress mask covers all n" = no */
  goto L600;
L595:;
  /* "ready-count(v) >= t+1" = no */
  if (readyMaskFull == 0)
    goto L607;
  /* "READY suppress mask covers all n" = yes */
L609:;
  if (type == BRACHA87_ECHO)
    goto L601;
  /* "send (ready, v)" = no */
  sendReady = 0;
  goto L588;
L607:;
  /* "READY suppress mask covers all n" = no */
  goto L609;
L592:;
  /* "ready-count(v) >= 2t+1" = no */
  goto L594;
L571:;
  /* "have echoed" = no */
  if (haveSentReady == 0)
    goto L612;
  /* "have sent ready" = yes */
  /* "send (ready, v)" = no */
  sendReady = 0;
  if (rdGe2TPlus1 == 0)
    goto L615;
  /* "ready-count(v) >= 2t+1" = yes */
L617:;
  if (rdGeTPlus1 == 0)
    goto L618;
  /* "ready-count(v) >= t+1" = yes */
  /* "send (echo, v)" = yes */
  sendEcho = 1;
  goto L582;
L618:;
  /* "ready-count(v) >= t+1" = no */
  if (readyMaskFull == 0)
    goto L621;
  /* "READY suppress mask covers all n" = yes */
  /* "retry (ready, v)" = no */
  retryReady = 0;
L623:;
  if (type == BRACHA87_ECHO)
    goto L624;
L625:;
  if (type == BRACHA87_INITIAL)
    goto L627;
  /* "kind of message" = (ready, v) */
  /* "send (echo, v)" = no */
  sendEcho = 0;
  goto Ldone;
L627:;
  /* "kind of message" = (initial, v) */
  /* "send (echo, v)" = yes */
  sendEcho = 1;
  goto Ldone;
L624:;
  /* "kind of message" = (echo, v) */
  /* "send (echo, v)" = yes */
  sendEcho = 1;
  goto Ldone;
L621:;
  /* "READY suppress mask covers all n" = no */
  /* "retry (ready, v)" = yes */
  retryReady = 1;
  goto L623;
L615:;
  /* "ready-count(v) >= 2t+1" = no */
  goto L617;
L612:;
  /* "have sent ready" = no */
  /* "retry (ready, v)" = no */
  retryReady = 0;
  if (rdGe2TPlus1 == 0)
    goto L630;
  /* "ready-count(v) >= 2t+1" = yes */
L632:;
  if (rdGeTPlus1 == 0)
    goto L633;
  /* "ready-count(v) >= t+1" = yes */
  /* "send (echo, v)" = yes */
  sendEcho = 1;
  if (readyMaskFull == 0)
    goto L636;
  /* "READY suppress mask covers all n" = yes */
L638:;
  if (type == BRACHA87_ECHO)
    goto L601;
L640:;
  if (type == BRACHA87_INITIAL)
    goto L604;
  goto L605;
L636:;
  /* "READY suppress mask covers all n" = no */
  goto L638;
L633:;
  /* "ready-count(v) >= t+1" = no */
  if (readyMaskFull == 0)
    goto L642;
  /* "READY suppress mask covers all n" = yes */
L644:;
  if (type == BRACHA87_ECHO)
    goto L645;
L646:;
  if (type == BRACHA87_INITIAL)
    goto L648;
  /* "kind of message" = (ready, v) */
  /* "send (echo, v)" = no */
  /* "send (ready, v)" = no */
  sendEcho = 0;
  sendReady = 0;
  goto Ldone;
L648:;
  /* "kind of message" = (initial, v) */
  /* "send (echo, v)" = yes */
  /* "send (ready, v)" = no */
  sendEcho = 1;
  sendReady = 0;
  goto Ldone;
L645:;
  /* "kind of message" = (echo, v) */
  /* "send (echo, v)" = yes */
  /* "send (ready, v)" = yes */
  sendEcho = 1;
  sendReady = 1;
  goto Ldone;
L642:;
  /* "READY suppress mask covers all n" = no */
  goto L644;
L630:;
  /* "ready-count(v) >= 2t+1" = no */
  goto L632;
L568:;
  /* "have accepted" = no */
L650:;
  if (haveEchoed == 0)
    goto L651;
  /* "have echoed" = yes */
  /* "retry (echo, v)" = yes */
  /* "send (echo, v)" = no */
  retryEcho = 1;
  sendEcho = 0;
  if (haveSentReady == 0)
    goto L654;
L655:;
  /* "have sent ready" = yes */
  /* "send (ready, v)" = no */
  sendReady = 0;
  if (rdGe2TPlus1 == 0)
    goto L657;
  /* "ready-count(v) >= 2t+1" = yes */
  if (rdGeTPlus1 == 0)
    goto L660;
  /* "ready-count(v) >= t+1" = yes */
L662:;
  if (readyMaskFull == 0)
    goto L663;
  /* "READY suppress mask covers all n" = yes */
  /* "retry (ready, v)" = no */
  retryReady = 0;
L665:;
  if (type == BRACHA87_ECHO)
    goto L666;
L668:;
  if (type == BRACHA87_INITIAL)
    goto L669;
  /* "accept(v)" = yes */
  /* "kind of message" = (ready, v) */
  acceptV = 1;
  goto Ldone;
L669:;
  /* "accept(v)" = no */
  /* "kind of message" = (initial, v) */
  acceptV = 0;
  goto Ldone;
L666:;
  /* "accept(v)" = no */
  /* "kind of message" = (echo, v) */
  acceptV = 0;
  goto Ldone;
L663:;
  /* "READY suppress mask covers all n" = no */
  /* "retry (ready, v)" = yes */
  retryReady = 1;
  goto L665;
L660:;
  /* "ready-count(v) >= t+1" = no */
  goto L662;
L657:;
  /* "accept(v)" = no */
  /* "ready-count(v) >= 2t+1" = no */
  acceptV = 0;
  goto L579;
L654:;
  /* "have sent ready" = no */
  /* "retry (ready, v)" = no */
  retryReady = 0;
  if (rdGe2TPlus1 == 0)
    goto L672;
  /* "ready-count(v) >= 2t+1" = yes */
  if (rdGeTPlus1 == 0)
    goto L675;
  /* "ready-count(v) >= t+1" = yes */
  if (readyMaskFull == 0)
    goto L678;
  /* "READY suppress mask covers all n" = yes */
L680:;
  if (type == BRACHA87_ECHO)
    goto L681;
L682:;
  if (type == BRACHA87_INITIAL)
    goto L684;
L685:;
  /* "accept(v)" = yes */
  /* "kind of message" = (ready, v) */
  /* "send (ready, v)" = yes */
  acceptV = 1;
  sendReady = 1;
  goto Ldone;
L684:;
  /* "accept(v)" = no */
  /* "kind of message" = (initial, v) */
  /* "send (ready, v)" = no */
  acceptV = 0;
  sendReady = 0;
  goto Ldone;
L681:;
  /* "accept(v)" = no */
  /* "kind of message" = (echo, v) */
  /* "send (ready, v)" = yes */
  acceptV = 0;
  sendReady = 1;
  goto Ldone;
L678:;
  /* "READY suppress mask covers all n" = no */
  goto L680;
L675:;
  /* "ready-count(v) >= t+1" = no */
  if (readyMaskFull == 0)
    goto L687;
  /* "READY suppress mask covers all n" = yes */
L689:;
  if (type == BRACHA87_ECHO)
    goto L681;
  /* "accept(v)" = no */
  /* "send (ready, v)" = no */
  acceptV = 0;
  sendReady = 0;
  goto L588;
L687:;
  /* "READY suppress mask covers all n" = no */
  goto L689;
L672:;
  /* "accept(v)" = no */
  /* "ready-count(v) >= 2t+1" = no */
  acceptV = 0;
  goto L594;
L651:;
  /* "have echoed" = no */
  /* "retry (echo, v)" = no */
  retryEcho = 0;
  if (haveSentReady == 0)
    goto L692;
  /* "have sent ready" = yes */
  /* "send (ready, v)" = no */
  sendReady = 0;
  if (rdGe2TPlus1 == 0)
    goto L695;
  /* "ready-count(v) >= 2t+1" = yes */
  if (rdGeTPlus1 == 0)
    goto L698;
  /* "ready-count(v) >= t+1" = yes */
  /* "send (echo, v)" = yes */
  sendEcho = 1;
  goto L662;
L698:;
  /* "ready-count(v) >= t+1" = no */
  if (readyMaskFull == 0)
    goto L701;
  /* "READY suppress mask covers all n" = yes */
  /* "retry (ready, v)" = no */
  retryReady = 0;
L703:;
  if (type == BRACHA87_ECHO)
    goto L704;
L705:;
  if (type == BRACHA87_INITIAL)
    goto L707;
  /* "accept(v)" = yes */
  /* "kind of message" = (ready, v) */
  /* "send (echo, v)" = no */
  acceptV = 1;
  sendEcho = 0;
  goto Ldone;
L707:;
  /* "accept(v)" = no */
  /* "kind of message" = (initial, v) */
  /* "send (echo, v)" = yes */
  acceptV = 0;
  sendEcho = 1;
  goto Ldone;
L704:;
  /* "accept(v)" = no */
  /* "kind of message" = (echo, v) */
  /* "send (echo, v)" = yes */
  acceptV = 0;
  sendEcho = 1;
  goto Ldone;
L701:;
  /* "READY suppress mask covers all n" = no */
  /* "retry (ready, v)" = yes */
  retryReady = 1;
  goto L703;
L695:;
  /* "accept(v)" = no */
  /* "ready-count(v) >= 2t+1" = no */
  acceptV = 0;
  goto L617;
L692:;
  /* "have sent ready" = no */
  /* "retry (ready, v)" = no */
  retryReady = 0;
  if (rdGe2TPlus1 == 0)
    goto L710;
  /* "ready-count(v) >= 2t+1" = yes */
  if (rdGeTPlus1 == 0)
    goto L713;
  /* "ready-count(v) >= t+1" = yes */
  /* "send (echo, v)" = yes */
  sendEcho = 1;
  if (readyMaskFull == 0)
    goto L716;
  /* "READY suppress mask covers all n" = yes */
L718:;
  if (type == BRACHA87_ECHO)
    goto L681;
L720:;
  if (type == BRACHA87_INITIAL)
    goto L684;
  goto L685;
L716:;
  /* "READY suppress mask covers all n" = no */
  goto L718;
L713:;
  /* "ready-count(v) >= t+1" = no */
  if (readyMaskFull == 0)
    goto L722;
  /* "READY suppress mask covers all n" = yes */
L724:;
  if (type == BRACHA87_ECHO)
    goto L725;
L726:;
  if (type == BRACHA87_INITIAL)
    goto L728;
  /* "accept(v)" = no */
  /* "kind of message" = (ready, v) */
  /* "send (echo, v)" = no */
  /* "send (ready, v)" = no */
  acceptV = 0;
  sendEcho = 0;
  sendReady = 0;
  goto Ldone;
L728:;
  /* "accept(v)" = no */
  /* "kind of message" = (initial, v) */
  /* "send (echo, v)" = yes */
  /* "send (ready, v)" = no */
  acceptV = 0;
  sendEcho = 1;
  sendReady = 0;
  goto Ldone;
L725:;
  /* "accept(v)" = no */
  /* "kind of message" = (echo, v) */
  /* "send (echo, v)" = yes */
  /* "send (ready, v)" = yes */
  acceptV = 0;
  sendEcho = 1;
  sendReady = 1;
  goto Ldone;
L722:;
  /* "READY suppress mask covers all n" = no */
  goto L724;
L710:;
  /* "accept(v)" = no */
  /* "ready-count(v) >= 2t+1" = no */
  acceptV = 0;
  goto L632;
L565:;
  /* "echo-count(v) > (n+t)/2" = no */
  if (haveAccepted == 0)
    goto L731;
  /* "accept(v)" = no */
  /* "have accepted" = yes */
  /* "retry (echo, v)" = no */
  acceptV = 0;
  retryEcho = 0;
L733:;
  if (haveEchoed == 0)
    goto L734;
  /* "have echoed" = yes */
  /* "send (echo, v)" = no */
  sendEcho = 0;
  if (haveSentReady == 0)
    goto L737;
  goto L575;
L737:;
  /* "have sent ready" = no */
  /* "retry (ready, v)" = no */
  retryReady = 0;
  if (rdGe2TPlus1 == 0)
    goto L739;
  /* "ready-count(v) >= 2t+1" = yes */
L741:;
  if (rdGeTPlus1 == 0)
    goto L742;
  /* "ready-count(v) >= t+1" = yes */
  if (readyMaskFull == 0)
    goto L745;
  /* "READY suppress mask covers all n" = yes */
L747:;
  if (type == BRACHA87_ECHO)
    goto L748;
  goto L602;
L748:;
  /* "kind of message" = (echo, v) */
  /* "send (ready, v)" = no */
  sendReady = 0;
  goto Ldone;
L745:;
  /* "READY suppress mask covers all n" = no */
  goto L747;
L742:;
  /* "ready-count(v) >= t+1" = no */
  /* "send (ready, v)" = no */
  sendReady = 0;
L749:;
  if (readyMaskFull == 0)
    goto L750;
  /* "READY suppress mask covers all n" = yes */
  goto L585;
L750:;
  /* "READY suppress mask covers all n" = no */
  goto L585;
L739:;
  /* "ready-count(v) >= 2t+1" = no */
  goto L741;
L734:;
  /* "have echoed" = no */
  if (haveSentReady == 0)
    goto L753;
  /* "have sent ready" = yes */
  /* "send (ready, v)" = no */
  sendReady = 0;
  if (rdGe2TPlus1 == 0)
    goto L756;
  /* "ready-count(v) >= 2t+1" = yes */
L758:;
  if (rdGeTPlus1 == 0)
    goto L759;
  /* "ready-count(v) >= t+1" = yes */
  if (readyMaskFull == 0)
    goto L762;
  /* "READY suppress mask covers all n" = yes */
  /* "retry (ready, v)" = no */
  retryReady = 0;
L764:;
  if (type == BRACHA87_ECHO)
    goto L765;
  /* "send (echo, v)" = yes */
  sendEcho = 1;
  goto L588;
L765:;
  /* "kind of message" = (echo, v) */
  /* "send (echo, v)" = no */
  sendEcho = 0;
  goto Ldone;
L762:;
  /* "READY suppress mask covers all n" = no */
  /* "retry (ready, v)" = yes */
  retryReady = 1;
  goto L764;
L759:;
  /* "ready-count(v) >= t+1" = no */
  if (readyMaskFull == 0)
    goto L768;
  /* "READY suppress mask covers all n" = yes */
  /* "retry (ready, v)" = no */
  retryReady = 0;
L770:;
  if (type == BRACHA87_ECHO)
    goto L765;
  goto L625;
L768:;
  /* "READY suppress mask covers all n" = no */
  /* "retry (ready, v)" = yes */
  retryReady = 1;
  goto L770;
L756:;
  /* "ready-count(v) >= 2t+1" = no */
  goto L758;
L753:;
  /* "have sent ready" = no */
  /* "retry (ready, v)" = no */
  retryReady = 0;
  if (rdGe2TPlus1 == 0)
    goto L772;
  /* "ready-count(v) >= 2t+1" = yes */
L774:;
  if (rdGeTPlus1 == 0)
    goto L775;
  /* "ready-count(v) >= t+1" = yes */
  if (readyMaskFull == 0)
    goto L778;
  /* "READY suppress mask covers all n" = yes */
L780:;
  if (type == BRACHA87_ECHO)
    goto L781;
  /* "send (echo, v)" = yes */
  sendEcho = 1;
  goto L640;
L781:;
  /* "kind of message" = (echo, v) */
  /* "send (echo, v)" = no */
  /* "send (ready, v)" = no */
  sendEcho = 0;
  sendReady = 0;
  goto Ldone;
L778:;
  /* "READY suppress mask covers all n" = no */
  goto L780;
L775:;
  /* "ready-count(v) >= t+1" = no */
  if (readyMaskFull == 0)
    goto L784;
  /* "READY suppress mask covers all n" = yes */
L786:;
  if (type == BRACHA87_ECHO)
    goto L781;
  goto L646;
L784:;
  /* "READY suppress mask covers all n" = no */
  goto L786;
L772:;
  /* "ready-count(v) >= 2t+1" = no */
  goto L774;
L731:;
  /* "have accepted" = no */
L787:;
  if (haveEchoed == 0)
    goto L788;
  /* "have echoed" = yes */
  /* "retry (echo, v)" = yes */
  /* "send (echo, v)" = no */
  retryEcho = 1;
  sendEcho = 0;
  if (haveSentReady == 0)
    goto L791;
  goto L655;
L791:;
  /* "have sent ready" = no */
  /* "retry (ready, v)" = no */
  retryReady = 0;
  if (rdGe2TPlus1 == 0)
    goto L793;
  /* "ready-count(v) >= 2t+1" = yes */
  if (rdGeTPlus1 == 0)
    goto L796;
  /* "ready-count(v) >= t+1" = yes */
  if (readyMaskFull == 0)
    goto L799;
  /* "READY suppress mask covers all n" = yes */
L801:;
  if (type == BRACHA87_ECHO)
    goto L802;
  goto L682;
L802:;
  /* "accept(v)" = no */
  /* "kind of message" = (echo, v) */
  /* "send (ready, v)" = no */
  acceptV = 0;
  sendReady = 0;
  goto Ldone;
L799:;
  /* "READY suppress mask covers all n" = no */
  goto L801;
L796:;
  /* "accept(v)" = no */
  /* "ready-count(v) >= t+1" = no */
  /* "send (ready, v)" = no */
  acceptV = 0;
  sendReady = 0;
  goto L749;
L793:;
  /* "accept(v)" = no */
  /* "ready-count(v) >= 2t+1" = no */
  acceptV = 0;
  goto L741;
L788:;
  /* "have echoed" = no */
  /* "retry (echo, v)" = no */
  retryEcho = 0;
  if (haveSentReady == 0)
    goto L804;
  /* "have sent ready" = yes */
  /* "send (ready, v)" = no */
  sendReady = 0;
  if (rdGe2TPlus1 == 0)
    goto L807;
  /* "ready-count(v) >= 2t+1" = yes */
  if (rdGeTPlus1 == 0)
    goto L810;
  /* "ready-count(v) >= t+1" = yes */
  if (readyMaskFull == 0)
    goto L813;
  /* "READY suppress mask covers all n" = yes */
  /* "retry (ready, v)" = no */
  retryReady = 0;
L815:;
  if (type == BRACHA87_ECHO)
    goto L816;
  /* "send (echo, v)" = yes */
  sendEcho = 1;
  goto L668;
L816:;
  /* "accept(v)" = no */
  /* "kind of message" = (echo, v) */
  /* "send (echo, v)" = no */
  acceptV = 0;
  sendEcho = 0;
  goto Ldone;
L813:;
  /* "READY suppress mask covers all n" = no */
  /* "retry (ready, v)" = yes */
  retryReady = 1;
  goto L815;
L810:;
  /* "ready-count(v) >= t+1" = no */
  if (readyMaskFull == 0)
    goto L819;
  /* "READY suppress mask covers all n" = yes */
  /* "retry (ready, v)" = no */
  retryReady = 0;
L821:;
  if (type == BRACHA87_ECHO)
    goto L816;
  goto L705;
L819:;
  /* "READY suppress mask covers all n" = no */
  /* "retry (ready, v)" = yes */
  retryReady = 1;
  goto L821;
L807:;
  /* "accept(v)" = no */
  /* "ready-count(v) >= 2t+1" = no */
  acceptV = 0;
  goto L758;
L804:;
  /* "have sent ready" = no */
  /* "retry (ready, v)" = no */
  retryReady = 0;
  if (rdGe2TPlus1 == 0)
    goto L823;
  /* "ready-count(v) >= 2t+1" = yes */
  if (rdGeTPlus1 == 0)
    goto L826;
  /* "ready-count(v) >= t+1" = yes */
  if (readyMaskFull == 0)
    goto L829;
  /* "READY suppress mask covers all n" = yes */
L831:;
  if (type == BRACHA87_ECHO)
    goto L832;
  /* "send (echo, v)" = yes */
  sendEcho = 1;
  goto L720;
L832:;
  /* "accept(v)" = no */
  /* "kind of message" = (echo, v) */
  /* "send (echo, v)" = no */
  /* "send (ready, v)" = no */
  acceptV = 0;
  sendEcho = 0;
  sendReady = 0;
  goto Ldone;
L829:;
  /* "READY suppress mask covers all n" = no */
  goto L831;
L826:;
  /* "ready-count(v) >= t+1" = no */
  if (readyMaskFull == 0)
    goto L835;
  /* "READY suppress mask covers all n" = yes */
L837:;
  if (type == BRACHA87_ECHO)
    goto L832;
  goto L726;
L835:;
  /* "READY suppress mask covers all n" = no */
  goto L837;
L823:;
  /* "accept(v)" = no */
  /* "ready-count(v) >= 2t+1" = no */
  acceptV = 0;
  goto L774;
L562:;
  /* "carries RECEIVED" = no */
  if (ecGtHalfNT == 0)
    goto L839;
  /* "echo-count(v) > (n+t)/2" = yes */
  if (haveAccepted == 0)
    goto L842;
  /* "accept(v)" = no */
  /* "have accepted" = yes */
  /* "retry (echo, v)" = no */
  acceptV = 0;
  retryEcho = 0;
L844:;
  if (haveEchoed == 0)
    goto L845;
  /* "have echoed" = yes */
  /* "send (echo, v)" = no */
  sendEcho = 0;
  if (haveSentReady == 0)
    goto L848;
L849:;
  /* "have sent ready" = yes */
  /* "send (ready, v)" = no */
  sendReady = 0;
  if (rdGe2TPlus1 == 0)
    goto L851;
  /* "ready-count(v) >= 2t+1" = yes */
L853:;
  if (rdGeTPlus1 == 0)
    goto L854;
  /* "ready-count(v) >= t+1" = yes */
L856:;
  if (readyMaskFull == 0)
    goto L857;
  /* "READY suppress mask covers all n" = yes */
  /* "retry (ready, v)" = no */
  retryReady = 0;
L859:;
  if (type == BRACHA87_ECHO)
    goto L860;
L862:;
  if (type == BRACHA87_INITIAL)
    goto L863;
  /* "arm re-send to sender" = yes */
  /* "kind of message" = (ready, v) */
  armSender = 1;
  goto Ldone;
L863:;
  /* "arm re-send to sender" = no */
  /* "kind of message" = (initial, v) */
  armSender = 0;
  goto Ldone;
L860:;
  /* "arm re-send to sender" = no */
  /* "kind of message" = (echo, v) */
  armSender = 0;
  goto Ldone;
L857:;
  /* "READY suppress mask covers all n" = no */
  /* "retry (ready, v)" = yes */
  retryReady = 1;
  goto L859;
L854:;
  /* "ready-count(v) >= t+1" = no */
  goto L856;
L851:;
  /* "ready-count(v) >= 2t+1" = no */
  goto L853;
L848:;
  /* "have sent ready" = no */
  /* "retry (ready, v)" = no */
  retryReady = 0;
  if (rdGe2TPlus1 == 0)
    goto L866;
  /* "ready-count(v) >= 2t+1" = yes */
L868:;
  if (rdGeTPlus1 == 0)
    goto L869;
  /* "ready-count(v) >= t+1" = yes */
  if (readyMaskFull == 0)
    goto L872;
  /* "READY suppress mask covers all n" = yes */
L874:;
  if (type == BRACHA87_ECHO)
    goto L875;
L876:;
  if (type == BRACHA87_INITIAL)
    goto L878;
L879:;
  /* "arm re-send to sender" = yes */
  /* "kind of message" = (ready, v) */
  /* "send (ready, v)" = yes */
  armSender = 1;
  sendReady = 1;
  goto Ldone;
L878:;
  /* "arm re-send to sender" = no */
  /* "kind of message" = (initial, v) */
  /* "send (ready, v)" = no */
  armSender = 0;
  sendReady = 0;
  goto Ldone;
L875:;
  /* "arm re-send to sender" = no */
  /* "kind of message" = (echo, v) */
  /* "send (ready, v)" = yes */
  armSender = 0;
  sendReady = 1;
  goto Ldone;
L872:;
  /* "READY suppress mask covers all n" = no */
  goto L874;
L869:;
  /* "ready-count(v) >= t+1" = no */
  if (readyMaskFull == 0)
    goto L881;
  /* "READY suppress mask covers all n" = yes */
L883:;
  if (type == BRACHA87_ECHO)
    goto L875;
  /* "send (ready, v)" = no */
  sendReady = 0;
  goto L862;
L881:;
  /* "READY suppress mask covers all n" = no */
  goto L883;
L866:;
  /* "ready-count(v) >= 2t+1" = no */
  goto L868;
L845:;
  /* "have echoed" = no */
  if (haveSentReady == 0)
    goto L886;
  /* "have sent ready" = yes */
  /* "send (ready, v)" = no */
  sendReady = 0;
  if (rdGe2TPlus1 == 0)
    goto L889;
  /* "ready-count(v) >= 2t+1" = yes */
L891:;
  if (rdGeTPlus1 == 0)
    goto L892;
  /* "ready-count(v) >= t+1" = yes */
  /* "send (echo, v)" = yes */
  sendEcho = 1;
  goto L856;
L892:;
  /* "ready-count(v) >= t+1" = no */
  if (readyMaskFull == 0)
    goto L895;
  /* "READY suppress mask covers all n" = yes */
  /* "retry (ready, v)" = no */
  retryReady = 0;
L897:;
  if (type == BRACHA87_ECHO)
    goto L898;
L899:;
  if (type == BRACHA87_INITIAL)
    goto L901;
  /* "arm re-send to sender" = yes */
  /* "kind of message" = (ready, v) */
  /* "send (echo, v)" = no */
  armSender = 1;
  sendEcho = 0;
  goto Ldone;
L901:;
  /* "arm re-send to sender" = no */
  /* "kind of message" = (initial, v) */
  /* "send (echo, v)" = yes */
  armSender = 0;
  sendEcho = 1;
  goto Ldone;
L898:;
  /* "arm re-send to sender" = no */
  /* "kind of message" = (echo, v) */
  /* "send (echo, v)" = yes */
  armSender = 0;
  sendEcho = 1;
  goto Ldone;
L895:;
  /* "READY suppress mask covers all n" = no */
  /* "retry (ready, v)" = yes */
  retryReady = 1;
  goto L897;
L889:;
  /* "ready-count(v) >= 2t+1" = no */
  goto L891;
L886:;
  /* "have sent ready" = no */
  /* "retry (ready, v)" = no */
  retryReady = 0;
  if (rdGe2TPlus1 == 0)
    goto L904;
  /* "ready-count(v) >= 2t+1" = yes */
L906:;
  if (rdGeTPlus1 == 0)
    goto L907;
  /* "ready-count(v) >= t+1" = yes */
  /* "send (echo, v)" = yes */
  sendEcho = 1;
  if (readyMaskFull == 0)
    goto L910;
  /* "READY suppress mask covers all n" = yes */
L912:;
  if (type == BRACHA87_ECHO)
    goto L875;
L914:;
  if (type == BRACHA87_INITIAL)
    goto L878;
  goto L879;
L910:;
  /* "READY suppress mask covers all n" = no */
  goto L912;
L907:;
  /* "ready-count(v) >= t+1" = no */
  if (readyMaskFull == 0)
    goto L916;
  /* "READY suppress mask covers all n" = yes */
L918:;
  if (type == BRACHA87_ECHO)
    goto L919;
L920:;
  if (type == BRACHA87_INITIAL)
    goto L922;
  /* "arm re-send to sender" = yes */
  /* "kind of message" = (ready, v) */
  /* "send (echo, v)" = no */
  /* "send (ready, v)" = no */
  armSender = 1;
  sendEcho = 0;
  sendReady = 0;
  goto Ldone;
L922:;
  /* "arm re-send to sender" = no */
  /* "kind of message" = (initial, v) */
  /* "send (echo, v)" = yes */
  /* "send (ready, v)" = no */
  armSender = 0;
  sendEcho = 1;
  sendReady = 0;
  goto Ldone;
L919:;
  /* "arm re-send to sender" = no */
  /* "kind of message" = (echo, v) */
  /* "send (echo, v)" = yes */
  /* "send (ready, v)" = yes */
  armSender = 0;
  sendEcho = 1;
  sendReady = 1;
  goto Ldone;
L916:;
  /* "READY suppress mask covers all n" = no */
  goto L918;
L904:;
  /* "ready-count(v) >= 2t+1" = no */
  goto L906;
L842:;
  /* "have accepted" = no */
L924:;
  if (haveEchoed == 0)
    goto L925;
  /* "have echoed" = yes */
  /* "retry (echo, v)" = yes */
  /* "send (echo, v)" = no */
  retryEcho = 1;
  sendEcho = 0;
  if (haveSentReady == 0)
    goto L928;
L929:;
  /* "have sent ready" = yes */
  /* "send (ready, v)" = no */
  sendReady = 0;
  if (rdGe2TPlus1 == 0)
    goto L931;
  /* "ready-count(v) >= 2t+1" = yes */
  if (rdGeTPlus1 == 0)
    goto L934;
  /* "ready-count(v) >= t+1" = yes */
L936:;
  if (readyMaskFull == 0)
    goto L937;
  /* "READY suppress mask covers all n" = yes */
  /* "retry (ready, v)" = no */
  retryReady = 0;
L939:;
  if (type == BRACHA87_ECHO)
    goto L940;
L942:;
  if (type == BRACHA87_INITIAL)
    goto L943;
  /* "accept(v)" = yes */
  /* "arm re-send to sender" = yes */
  /* "kind of message" = (ready, v) */
  acceptV = 1;
  armSender = 1;
  goto Ldone;
L943:;
  /* "accept(v)" = no */
  /* "arm re-send to sender" = no */
  /* "kind of message" = (initial, v) */
  acceptV = 0;
  armSender = 0;
  goto Ldone;
L940:;
  /* "accept(v)" = no */
  /* "arm re-send to sender" = no */
  /* "kind of message" = (echo, v) */
  acceptV = 0;
  armSender = 0;
  goto Ldone;
L937:;
  /* "READY suppress mask covers all n" = no */
  /* "retry (ready, v)" = yes */
  retryReady = 1;
  goto L939;
L934:;
  /* "ready-count(v) >= t+1" = no */
  goto L936;
L931:;
  /* "accept(v)" = no */
  /* "arm re-send to sender" = no */
  /* "ready-count(v) >= 2t+1" = no */
  acceptV = 0;
  armSender = 0;
  goto L579;
L928:;
  /* "have sent ready" = no */
  /* "retry (ready, v)" = no */
  retryReady = 0;
  if (rdGe2TPlus1 == 0)
    goto L946;
  /* "ready-count(v) >= 2t+1" = yes */
  if (rdGeTPlus1 == 0)
    goto L949;
  /* "ready-count(v) >= t+1" = yes */
  if (readyMaskFull == 0)
    goto L952;
  /* "READY suppress mask covers all n" = yes */
L954:;
  if (type == BRACHA87_ECHO)
    goto L955;
L956:;
  if (type == BRACHA87_INITIAL)
    goto L958;
L959:;
  /* "accept(v)" = yes */
  /* "arm re-send to sender" = yes */
  /* "kind of message" = (ready, v) */
  /* "send (ready, v)" = yes */
  acceptV = 1;
  armSender = 1;
  sendReady = 1;
  goto Ldone;
L958:;
  /* "accept(v)" = no */
  /* "arm re-send to sender" = no */
  /* "kind of message" = (initial, v) */
  /* "send (ready, v)" = no */
  acceptV = 0;
  armSender = 0;
  sendReady = 0;
  goto Ldone;
L955:;
  /* "accept(v)" = no */
  /* "arm re-send to sender" = no */
  /* "kind of message" = (echo, v) */
  /* "send (ready, v)" = yes */
  acceptV = 0;
  armSender = 0;
  sendReady = 1;
  goto Ldone;
L952:;
  /* "READY suppress mask covers all n" = no */
  goto L954;
L949:;
  /* "ready-count(v) >= t+1" = no */
  if (readyMaskFull == 0)
    goto L961;
  /* "READY suppress mask covers all n" = yes */
L963:;
  if (type == BRACHA87_ECHO)
    goto L955;
  /* "accept(v)" = no */
  /* "arm re-send to sender" = no */
  /* "send (ready, v)" = no */
  acceptV = 0;
  armSender = 0;
  sendReady = 0;
  goto L588;
L961:;
  /* "READY suppress mask covers all n" = no */
  goto L963;
L946:;
  /* "accept(v)" = no */
  /* "arm re-send to sender" = no */
  /* "ready-count(v) >= 2t+1" = no */
  acceptV = 0;
  armSender = 0;
  goto L594;
L925:;
  /* "have echoed" = no */
  /* "retry (echo, v)" = no */
  retryEcho = 0;
  if (haveSentReady == 0)
    goto L966;
  /* "have sent ready" = yes */
  /* "send (ready, v)" = no */
  sendReady = 0;
  if (rdGe2TPlus1 == 0)
    goto L969;
  /* "ready-count(v) >= 2t+1" = yes */
  if (rdGeTPlus1 == 0)
    goto L972;
  /* "ready-count(v) >= t+1" = yes */
  /* "send (echo, v)" = yes */
  sendEcho = 1;
  goto L936;
L972:;
  /* "ready-count(v) >= t+1" = no */
  if (readyMaskFull == 0)
    goto L975;
  /* "READY suppress mask covers all n" = yes */
  /* "retry (ready, v)" = no */
  retryReady = 0;
L977:;
  if (type == BRACHA87_ECHO)
    goto L978;
L979:;
  if (type == BRACHA87_INITIAL)
    goto L981;
  /* "accept(v)" = yes */
  /* "arm re-send to sender" = yes */
  /* "kind of message" = (ready, v) */
  /* "send (echo, v)" = no */
  acceptV = 1;
  armSender = 1;
  sendEcho = 0;
  goto Ldone;
L981:;
  /* "accept(v)" = no */
  /* "arm re-send to sender" = no */
  /* "kind of message" = (initial, v) */
  /* "send (echo, v)" = yes */
  acceptV = 0;
  armSender = 0;
  sendEcho = 1;
  goto Ldone;
L978:;
  /* "accept(v)" = no */
  /* "arm re-send to sender" = no */
  /* "kind of message" = (echo, v) */
  /* "send (echo, v)" = yes */
  acceptV = 0;
  armSender = 0;
  sendEcho = 1;
  goto Ldone;
L975:;
  /* "READY suppress mask covers all n" = no */
  /* "retry (ready, v)" = yes */
  retryReady = 1;
  goto L977;
L969:;
  /* "accept(v)" = no */
  /* "arm re-send to sender" = no */
  /* "ready-count(v) >= 2t+1" = no */
  acceptV = 0;
  armSender = 0;
  goto L617;
L966:;
  /* "have sent ready" = no */
  /* "retry (ready, v)" = no */
  retryReady = 0;
  if (rdGe2TPlus1 == 0)
    goto L984;
  /* "ready-count(v) >= 2t+1" = yes */
  if (rdGeTPlus1 == 0)
    goto L987;
  /* "ready-count(v) >= t+1" = yes */
  /* "send (echo, v)" = yes */
  sendEcho = 1;
  if (readyMaskFull == 0)
    goto L990;
  /* "READY suppress mask covers all n" = yes */
L992:;
  if (type == BRACHA87_ECHO)
    goto L955;
L994:;
  if (type == BRACHA87_INITIAL)
    goto L958;
  goto L959;
L990:;
  /* "READY suppress mask covers all n" = no */
  goto L992;
L987:;
  /* "ready-count(v) >= t+1" = no */
  if (readyMaskFull == 0)
    goto L996;
  /* "READY suppress mask covers all n" = yes */
L998:;
  if (type == BRACHA87_ECHO)
    goto L999;
L1000:;
  if (type == BRACHA87_INITIAL)
    goto L1002;
  /* "accept(v)" = no */
  /* "arm re-send to sender" = no */
  /* "kind of message" = (ready, v) */
  /* "send (echo, v)" = no */
  /* "send (ready, v)" = no */
  acceptV = 0;
  armSender = 0;
  sendEcho = 0;
  sendReady = 0;
  goto Ldone;
L1002:;
  /* "accept(v)" = no */
  /* "arm re-send to sender" = no */
  /* "kind of message" = (initial, v) */
  /* "send (echo, v)" = yes */
  /* "send (ready, v)" = no */
  acceptV = 0;
  armSender = 0;
  sendEcho = 1;
  sendReady = 0;
  goto Ldone;
L999:;
  /* "accept(v)" = no */
  /* "arm re-send to sender" = no */
  /* "kind of message" = (echo, v) */
  /* "send (echo, v)" = yes */
  /* "send (ready, v)" = yes */
  acceptV = 0;
  armSender = 0;
  sendEcho = 1;
  sendReady = 1;
  goto Ldone;
L996:;
  /* "READY suppress mask covers all n" = no */
  goto L998;
L984:;
  /* "accept(v)" = no */
  /* "arm re-send to sender" = no */
  /* "ready-count(v) >= 2t+1" = no */
  acceptV = 0;
  armSender = 0;
  goto L632;
L839:;
  /* "echo-count(v) > (n+t)/2" = no */
  if (haveAccepted == 0)
    goto L1005;
  /* "accept(v)" = no */
  /* "have accepted" = yes */
  /* "retry (echo, v)" = no */
  acceptV = 0;
  retryEcho = 0;
L1007:;
  if (haveEchoed == 0)
    goto L1008;
  /* "have echoed" = yes */
  /* "send (echo, v)" = no */
  sendEcho = 0;
  if (haveSentReady == 0)
    goto L1011;
  goto L849;
L1011:;
  /* "have sent ready" = no */
  /* "retry (ready, v)" = no */
  retryReady = 0;
  if (rdGe2TPlus1 == 0)
    goto L1013;
  /* "ready-count(v) >= 2t+1" = yes */
L1015:;
  if (rdGeTPlus1 == 0)
    goto L1016;
  /* "ready-count(v) >= t+1" = yes */
  if (readyMaskFull == 0)
    goto L1019;
  /* "READY suppress mask covers all n" = yes */
L1021:;
  if (type == BRACHA87_ECHO)
    goto L1022;
  goto L876;
L1022:;
  /* "arm re-send to sender" = no */
  /* "kind of message" = (echo, v) */
  /* "send (ready, v)" = no */
  armSender = 0;
  sendReady = 0;
  goto Ldone;
L1019:;
  /* "READY suppress mask covers all n" = no */
  goto L1021;
L1016:;
  /* "ready-count(v) >= t+1" = no */
  /* "send (ready, v)" = no */
  sendReady = 0;
  if (readyMaskFull == 0)
    goto L1024;
  /* "READY suppress mask covers all n" = yes */
  goto L859;
L1024:;
  /* "READY suppress mask covers all n" = no */
  goto L859;
L1013:;
  /* "ready-count(v) >= 2t+1" = no */
  goto L1015;
L1008:;
  /* "have echoed" = no */
  if (haveSentReady == 0)
    goto L1027;
  /* "have sent ready" = yes */
  /* "send (ready, v)" = no */
  sendReady = 0;
  if (rdGe2TPlus1 == 0)
    goto L1030;
  /* "ready-count(v) >= 2t+1" = yes */
L1032:;
  if (rdGeTPlus1 == 0)
    goto L1033;
  /* "ready-count(v) >= t+1" = yes */
  if (readyMaskFull == 0)
    goto L1036;
  /* "READY suppress mask covers all n" = yes */
  /* "retry (ready, v)" = no */
  retryReady = 0;
L1038:;
  if (type == BRACHA87_ECHO)
    goto L1039;
  /* "send (echo, v)" = yes */
  sendEcho = 1;
  goto L862;
L1039:;
  /* "arm re-send to sender" = no */
  /* "kind of message" = (echo, v) */
  /* "send (echo, v)" = no */
  armSender = 0;
  sendEcho = 0;
  goto Ldone;
L1036:;
  /* "READY suppress mask covers all n" = no */
  /* "retry (ready, v)" = yes */
  retryReady = 1;
  goto L1038;
L1033:;
  /* "ready-count(v) >= t+1" = no */
  if (readyMaskFull == 0)
    goto L1042;
  /* "READY suppress mask covers all n" = yes */
  /* "retry (ready, v)" = no */
  retryReady = 0;
L1044:;
  if (type == BRACHA87_ECHO)
    goto L1039;
  goto L899;
L1042:;
  /* "READY suppress mask covers all n" = no */
  /* "retry (ready, v)" = yes */
  retryReady = 1;
  goto L1044;
L1030:;
  /* "ready-count(v) >= 2t+1" = no */
  goto L1032;
L1027:;
  /* "have sent ready" = no */
  /* "retry (ready, v)" = no */
  retryReady = 0;
  if (rdGe2TPlus1 == 0)
    goto L1046;
  /* "ready-count(v) >= 2t+1" = yes */
L1048:;
  if (rdGeTPlus1 == 0)
    goto L1049;
  /* "ready-count(v) >= t+1" = yes */
  if (readyMaskFull == 0)
    goto L1052;
  /* "READY suppress mask covers all n" = yes */
L1054:;
  if (type == BRACHA87_ECHO)
    goto L1055;
  /* "send (echo, v)" = yes */
  sendEcho = 1;
  goto L914;
L1055:;
  /* "arm re-send to sender" = no */
  /* "kind of message" = (echo, v) */
  /* "send (echo, v)" = no */
  /* "send (ready, v)" = no */
  armSender = 0;
  sendEcho = 0;
  sendReady = 0;
  goto Ldone;
L1052:;
  /* "READY suppress mask covers all n" = no */
  goto L1054;
L1049:;
  /* "ready-count(v) >= t+1" = no */
  if (readyMaskFull == 0)
    goto L1058;
  /* "READY suppress mask covers all n" = yes */
L1060:;
  if (type == BRACHA87_ECHO)
    goto L1055;
  goto L920;
L1058:;
  /* "READY suppress mask covers all n" = no */
  goto L1060;
L1046:;
  /* "ready-count(v) >= 2t+1" = no */
  goto L1048;
L1005:;
  /* "have accepted" = no */
L1061:;
  if (haveEchoed == 0)
    goto L1062;
  /* "have echoed" = yes */
  /* "retry (echo, v)" = yes */
  /* "send (echo, v)" = no */
  retryEcho = 1;
  sendEcho = 0;
  if (haveSentReady == 0)
    goto L1065;
  goto L929;
L1065:;
  /* "have sent ready" = no */
  /* "retry (ready, v)" = no */
  retryReady = 0;
  if (rdGe2TPlus1 == 0)
    goto L1067;
  /* "ready-count(v) >= 2t+1" = yes */
  if (rdGeTPlus1 == 0)
    goto L1070;
  /* "ready-count(v) >= t+1" = yes */
  if (readyMaskFull == 0)
    goto L1073;
  /* "READY suppress mask covers all n" = yes */
L1075:;
  if (type == BRACHA87_ECHO)
    goto L1076;
  goto L956;
L1076:;
  /* "accept(v)" = no */
  /* "arm re-send to sender" = no */
  /* "kind of message" = (echo, v) */
  /* "send (ready, v)" = no */
  acceptV = 0;
  armSender = 0;
  sendReady = 0;
  goto Ldone;
L1073:;
  /* "READY suppress mask covers all n" = no */
  goto L1075;
L1070:;
  /* "accept(v)" = no */
  /* "arm re-send to sender" = no */
  /* "ready-count(v) >= t+1" = no */
  /* "send (ready, v)" = no */
  acceptV = 0;
  armSender = 0;
  sendReady = 0;
  goto L749;
L1067:;
  /* "accept(v)" = no */
  /* "arm re-send to sender" = no */
  /* "ready-count(v) >= 2t+1" = no */
  acceptV = 0;
  armSender = 0;
  goto L741;
L1062:;
  /* "have echoed" = no */
  /* "retry (echo, v)" = no */
  retryEcho = 0;
  if (haveSentReady == 0)
    goto L1078;
  /* "have sent ready" = yes */
  /* "send (ready, v)" = no */
  sendReady = 0;
  if (rdGe2TPlus1 == 0)
    goto L1081;
  /* "ready-count(v) >= 2t+1" = yes */
  if (rdGeTPlus1 == 0)
    goto L1084;
  /* "ready-count(v) >= t+1" = yes */
  if (readyMaskFull == 0)
    goto L1087;
  /* "READY suppress mask covers all n" = yes */
  /* "retry (ready, v)" = no */
  retryReady = 0;
L1089:;
  if (type == BRACHA87_ECHO)
    goto L1090;
  /* "send (echo, v)" = yes */
  sendEcho = 1;
  goto L942;
L1090:;
  /* "accept(v)" = no */
  /* "arm re-send to sender" = no */
  /* "kind of message" = (echo, v) */
  /* "send (echo, v)" = no */
  acceptV = 0;
  armSender = 0;
  sendEcho = 0;
  goto Ldone;
L1087:;
  /* "READY suppress mask covers all n" = no */
  /* "retry (ready, v)" = yes */
  retryReady = 1;
  goto L1089;
L1084:;
  /* "ready-count(v) >= t+1" = no */
  if (readyMaskFull == 0)
    goto L1093;
  /* "READY suppress mask covers all n" = yes */
  /* "retry (ready, v)" = no */
  retryReady = 0;
L1095:;
  if (type == BRACHA87_ECHO)
    goto L1090;
  goto L979;
L1093:;
  /* "READY suppress mask covers all n" = no */
  /* "retry (ready, v)" = yes */
  retryReady = 1;
  goto L1095;
L1081:;
  /* "accept(v)" = no */
  /* "arm re-send to sender" = no */
  /* "ready-count(v) >= 2t+1" = no */
  acceptV = 0;
  armSender = 0;
  goto L758;
L1078:;
  /* "have sent ready" = no */
  /* "retry (ready, v)" = no */
  retryReady = 0;
  if (rdGe2TPlus1 == 0)
    goto L1097;
  /* "ready-count(v) >= 2t+1" = yes */
  if (rdGeTPlus1 == 0)
    goto L1100;
  /* "ready-count(v) >= t+1" = yes */
  if (readyMaskFull == 0)
    goto L1103;
  /* "READY suppress mask covers all n" = yes */
L1105:;
  if (type == BRACHA87_ECHO)
    goto L1106;
  /* "send (echo, v)" = yes */
  sendEcho = 1;
  goto L994;
L1106:;
  /* "accept(v)" = no */
  /* "arm re-send to sender" = no */
  /* "kind of message" = (echo, v) */
  /* "send (echo, v)" = no */
  /* "send (ready, v)" = no */
  acceptV = 0;
  armSender = 0;
  sendEcho = 0;
  sendReady = 0;
  goto Ldone;
L1103:;
  /* "READY suppress mask covers all n" = no */
  goto L1105;
L1100:;
  /* "ready-count(v) >= t+1" = no */
  if (readyMaskFull == 0)
    goto L1109;
  /* "READY suppress mask covers all n" = yes */
L1111:;
  if (type == BRACHA87_ECHO)
    goto L1106;
  goto L1000;
L1109:;
  /* "READY suppress mask covers all n" = no */
  goto L1111;
L1097:;
  /* "accept(v)" = no */
  /* "arm re-send to sender" = no */
  /* "ready-count(v) >= 2t+1" = no */
  acceptV = 0;
  armSender = 0;
  goto L774;
L5:;
  /* "am initiator" = no */
  goto L7;
L2:;
  /* "all echoed" = no */
  if (amInitiator == 0)
    goto L1113;
  /* "am initiator" = yes */
  if (annAccepted == 0)
    goto L1116;
  /* "carries ACCEPTED" = yes */
  if (annReceived == 0)
    goto L1119;
  /* "arm re-send to sender" = no */
  /* "carries RECEIVED" = yes */
  armSender = 0;
  if (ecGtHalfNT == 0)
    goto L1122;
  /* "echo-count(v) > (n+t)/2" = yes */
  if (haveAccepted == 0)
    goto L1125;
  /* "accept(v)" = no */
  /* "have accepted" = yes */
  /* "retry (echo, v)" = no */
  /* "retry (initial, v)" = no */
  acceptV = 0;
  retryEcho = 0;
  retryInitial = 0;
  goto L19;
L1125:;
  /* "have accepted" = no */
  /* "retry (initial, v)" = yes */
  retryInitial = 1;
  goto L99;
L1122:;
  /* "echo-count(v) > (n+t)/2" = no */
  if (haveAccepted == 0)
    goto L1128;
  /* "accept(v)" = no */
  /* "have accepted" = yes */
  /* "retry (echo, v)" = no */
  /* "retry (initial, v)" = no */
  acceptV = 0;
  retryEcho = 0;
  retryInitial = 0;
  goto L182;
L1128:;
  /* "have accepted" = no */
  /* "retry (initial, v)" = yes */
  retryInitial = 1;
  goto L236;
L1119:;
  /* "carries RECEIVED" = no */
  if (ecGtHalfNT == 0)
    goto L1131;
  /* "echo-count(v) > (n+t)/2" = yes */
  if (haveAccepted == 0)
    goto L1134;
  /* "accept(v)" = no */
  /* "have accepted" = yes */
  /* "retry (echo, v)" = no */
  /* "retry (initial, v)" = no */
  acceptV = 0;
  retryEcho = 0;
  retryInitial = 0;
  goto L293;
L1134:;
  /* "have accepted" = no */
  /* "retry (initial, v)" = yes */
  retryInitial = 1;
  goto L373;
L1131:;
  /* "echo-count(v) > (n+t)/2" = no */
  if (haveAccepted == 0)
    goto L1137;
  /* "accept(v)" = no */
  /* "have accepted" = yes */
  /* "retry (echo, v)" = no */
  /* "retry (initial, v)" = no */
  acceptV = 0;
  retryEcho = 0;
  retryInitial = 0;
  goto L456;
L1137:;
  /* "have accepted" = no */
  /* "retry (initial, v)" = yes */
  retryInitial = 1;
  goto L510;
L1116:;
  /* "carries ACCEPTED" = no */
  /* "record sender accepted" = no */
  recordSender = 0;
  if (annReceived == 0)
    goto L1140;
  /* "arm re-send to sender" = no */
  /* "carries RECEIVED" = yes */
  armSender = 0;
  if (ecGtHalfNT == 0)
    goto L1143;
  /* "echo-count(v) > (n+t)/2" = yes */
  if (haveAccepted == 0)
    goto L1146;
  /* "accept(v)" = no */
  /* "have accepted" = yes */
  /* "retry (echo, v)" = no */
  /* "retry (initial, v)" = no */
  acceptV = 0;
  retryEcho = 0;
  retryInitial = 0;
  goto L570;
L1146:;
  /* "have accepted" = no */
  /* "retry (initial, v)" = yes */
  retryInitial = 1;
  goto L650;
L1143:;
  /* "echo-count(v) > (n+t)/2" = no */
  if (haveAccepted == 0)
    goto L1149;
  /* "accept(v)" = no */
  /* "have accepted" = yes */
  /* "retry (echo, v)" = no */
  /* "retry (initial, v)" = no */
  acceptV = 0;
  retryEcho = 0;
  retryInitial = 0;
  goto L733;
L1149:;
  /* "have accepted" = no */
  /* "retry (initial, v)" = yes */
  retryInitial = 1;
  goto L787;
L1140:;
  /* "carries RECEIVED" = no */
  if (ecGtHalfNT == 0)
    goto L1152;
  /* "echo-count(v) > (n+t)/2" = yes */
  if (haveAccepted == 0)
    goto L1155;
  /* "accept(v)" = no */
  /* "have accepted" = yes */
  /* "retry (echo, v)" = no */
  /* "retry (initial, v)" = no */
  acceptV = 0;
  retryEcho = 0;
  retryInitial = 0;
  goto L844;
L1155:;
  /* "have accepted" = no */
  /* "retry (initial, v)" = yes */
  retryInitial = 1;
  goto L924;
L1152:;
  /* "echo-count(v) > (n+t)/2" = no */
  if (haveAccepted == 0)
    goto L1158;
  /* "accept(v)" = no */
  /* "have accepted" = yes */
  /* "retry (echo, v)" = no */
  /* "retry (initial, v)" = no */
  acceptV = 0;
  retryEcho = 0;
  retryInitial = 0;
  goto L1007;
L1158:;
  /* "have accepted" = no */
  /* "retry (initial, v)" = yes */
  retryInitial = 1;
  goto L1061;
L1113:;
  /* "am initiator" = no */
  /* "retry (initial, v)" = no */
  retryInitial = 0;
  goto L7;
Ldone:;
