/* Generated by psu.awk from system.psu -- dispatch depth 15. */
/* Edit the .dtc and regenerate; changes here are overwritten. */
  if (valuePending == 1)
    goto L2;
  /* "admit the next round" = no */
  /* "application value pending" = no */
  doAdmit = 0;
  if (toleranceElapsed == 1)
    goto L5;
  /* "tolerance elapsed" = no */
  if (senderPossesses == 1)
    goto L8;
  /* "sender has evidenced possession of R" = no */
  if (allPossess == 0)
    goto L11;
  /* "all n processes have evidenced possession of R" = yes */
  /* "release R" = yes */
  doRelease = 1;
  if (backlogDrained == 0)
    goto L14;
  /* "own backlog drained" = yes */
  if (budgetExceeded == 0)
    goto L17;
  /* "recovery reach exhausted" = yes */
L19:;
  if (instanceLive == 0)
    goto L20;
L21:;
  /* "join the oldest owed round" = no */
  /* "maintain the next round" = no */
  /* "own instance live" = yes */
  doJoin = 0;
  doMaintain = 0;
L22:;
  if (maintenanceDue == 0)
    goto L23;
  /* "identity maintenance due" = yes */
L25:;
  if (oldestRetained == 1)
    goto L26;
  /* "R is the oldest retained round" = no */
L28:;
  if (participationOwed == 1)
    goto L29;
  /* "participation owed to any round" = no */
L31:;
  if (priorPossession == SYSTEM_DUTY_HELD)
    goto L32;
L34:;
  if (priorPossession == SYSTEM_DUTY_MET)
    goto L35;
  /* "possession of the prior round" = at n-t, short of all n */
L37:;
  if (roundClass == SYSTEM_ROUND_AHEAD)
    goto L38;
  /* "record participation owed for R" = no */
  doParticipationOwed = 0;
  if (roundClass == SYSTEM_ROUND_LIVE)
    goto L41;
  /* "deliver the act to the live instance" = no */
  doDeliver = 0;
  if (roundClass == SYSTEM_ROUND_RELEASED)
    goto L44;
  /* "record serve owed to the sender for R" = yes */
  /* "round R relative to self" = R COMPLETE and retained */
  doServeOwed = 1;
  goto Ldone;
L44:;
  /* "record serve owed to the sender for R" = no */
  /* "round R relative to self" = R COMPLETE and released */
  doServeOwed = 0;
  goto Ldone;
L41:;
  /* "deliver the act to the live instance" = yes */
  /* "record serve owed to the sender for R" = no */
  /* "round R relative to self" = R is the live instance */
  doDeliver = 1;
  doServeOwed = 0;
  goto Ldone;
L38:;
  /* "deliver the act to the live instance" = no */
  /* "record participation owed for R" = yes */
  /* "record serve owed to the sender for R" = no */
  /* "round R relative to self" = R not yet reached */
  doDeliver = 0;
  doParticipationOwed = 1;
  doServeOwed = 0;
  goto Ldone;
L35:;
  /* "possession of the prior round" = at all n, or not retained */
  goto L37;
L32:;
  /* "possession of the prior round" = short of n-t */
  goto L37;
L29:;
  /* "participation owed to any round" = yes */
  goto L31;
L26:;
  /* "R is the oldest retained round" = yes */
  goto L28;
L23:;
  /* "identity maintenance due" = no */
  goto L25;
L20:;
  /* "own instance live" = no */
  if (maintenanceDue == 0)
    goto L47;
  /* "identity maintenance due" = yes */
L49:;
  if (oldestRetained == 1)
    goto L50;
  /* "R is the oldest retained round" = no */
L52:;
  if (participationOwed == 1)
    goto L53;
  /* "join the oldest owed round" = no */
  /* "participation owed to any round" = no */
  doJoin = 0;
  if (priorPossession == SYSTEM_DUTY_HELD)
    goto L56;
  if (priorPossession == SYSTEM_DUTY_MET)
    goto L59;
  /* "maintain the next round" = no */
  /* "possession of the prior round" = at n-t, short of all n */
  doMaintain = 0;
  goto L37;
L59:;
  /* "maintain the next round" = yes */
  /* "possession of the prior round" = at all n, or not retained */
  doMaintain = 1;
  goto L37;
L56:;
  /* "maintain the next round" = no */
  /* "possession of the prior round" = short of n-t */
  doMaintain = 0;
  goto L37;
L53:;
  /* "maintain the next round" = no */
  /* "participation owed to any round" = yes */
  doMaintain = 0;
L61:;
  if (priorPossession == SYSTEM_DUTY_HELD)
    goto L62;
  if (priorPossession == SYSTEM_DUTY_MET)
    goto L65;
  /* "join the oldest owed round" = no */
  /* "possession of the prior round" = at n-t, short of all n */
  doJoin = 0;
  goto L37;
L65:;
  /* "join the oldest owed round" = yes */
  /* "possession of the prior round" = at all n, or not retained */
  doJoin = 1;
  goto L37;
L62:;
  /* "join the oldest owed round" = no */
  /* "possession of the prior round" = short of n-t */
  doJoin = 0;
  goto L37;
L50:;
  /* "R is the oldest retained round" = yes */
  goto L52;
L47:;
  /* "identity maintenance due" = no */
  /* "maintain the next round" = no */
  doMaintain = 0;
L67:;
  if (oldestRetained == 1)
    goto L68;
  /* "R is the oldest retained round" = no */
L70:;
  if (participationOwed == 1)
    goto L71;
L72:;
  /* "join the oldest owed round" = no */
  /* "participation owed to any round" = no */
  doJoin = 0;
  goto L31;
L71:;
  /* "participation owed to any round" = yes */
  goto L61;
L68:;
  /* "R is the oldest retained round" = yes */
  goto L70;
L17:;
  /* "recovery reach exhausted" = no */
  goto L19;
L14:;
  /* "maintain the next round" = no */
  /* "own backlog drained" = no */
  doMaintain = 0;
L73:;
  if (budgetExceeded == 0)
    goto L74;
  /* "recovery reach exhausted" = yes */
L76:;
  if (instanceLive == 0)
    goto L77;
L78:;
  /* "join the oldest owed round" = no */
  /* "own instance live" = yes */
  doJoin = 0;
  goto L22;
L77:;
  /* "own instance live" = no */
  if (maintenanceDue == 0)
    goto L80;
  /* "identity maintenance due" = yes */
  goto L67;
L80:;
  /* "identity maintenance due" = no */
  goto L67;
L74:;
  /* "recovery reach exhausted" = no */
  goto L76;
L11:;
  /* "all n processes have evidenced possession of R" = no */
  if (backlogDrained == 0)
    goto L83;
  /* "own backlog drained" = yes */
  if (budgetExceeded == 0)
    goto L86;
  /* "recovery reach exhausted" = yes */
  if (instanceLive == 0)
    goto L89;
L90:;
  /* "join the oldest owed round" = no */
  /* "maintain the next round" = no */
  /* "own instance live" = yes */
  doJoin = 0;
  doMaintain = 0;
L91:;
  if (maintenanceDue == 0)
    goto L92;
  /* "identity maintenance due" = yes */
L94:;
  if (oldestRetained == 1)
    goto L95;
  /* "R is the oldest retained round" = no */
  /* "release R" = no */
  doRelease = 0;
  goto L28;
L95:;
  /* "R is the oldest retained round" = yes */
  /* "release R" = yes */
  doRelease = 1;
  goto L28;
L92:;
  /* "identity maintenance due" = no */
  goto L94;
L89:;
  /* "own instance live" = no */
  if (maintenanceDue == 0)
    goto L98;
  /* "identity maintenance due" = yes */
L100:;
  if (oldestRetained == 1)
    goto L101;
  /* "R is the oldest retained round" = no */
  /* "release R" = no */
  doRelease = 0;
  goto L52;
L101:;
  /* "R is the oldest retained round" = yes */
  /* "release R" = yes */
  doRelease = 1;
  goto L52;
L98:;
  /* "identity maintenance due" = no */
  /* "maintain the next round" = no */
  doMaintain = 0;
L103:;
  if (oldestRetained == 1)
    goto L104;
  /* "R is the oldest retained round" = no */
  /* "release R" = no */
  doRelease = 0;
  goto L70;
L104:;
  /* "R is the oldest retained round" = yes */
  /* "release R" = yes */
  doRelease = 1;
  goto L70;
L86:;
  /* "recovery reach exhausted" = no */
  /* "release R" = no */
  doRelease = 0;
  goto L19;
L83:;
  /* "maintain the next round" = no */
  /* "own backlog drained" = no */
  doMaintain = 0;
L106:;
  if (budgetExceeded == 0)
    goto L107;
  /* "recovery reach exhausted" = yes */
  if (instanceLive == 0)
    goto L110;
L111:;
  /* "join the oldest owed round" = no */
  /* "own instance live" = yes */
  doJoin = 0;
  goto L91;
L110:;
  /* "own instance live" = no */
  if (maintenanceDue == 0)
    goto L113;
  /* "identity maintenance due" = yes */
  goto L103;
L113:;
  /* "identity maintenance due" = no */
  goto L103;
L107:;
  /* "recovery reach exhausted" = no */
  /* "release R" = no */
  doRelease = 0;
  goto L76;
L8:;
  /* "record serve owed to the sender for R" = no */
  /* "sender has evidenced possession of R" = yes */
  doServeOwed = 0;
  if (allPossess == 0)
    goto L116;
  /* "all n processes have evidenced possession of R" = yes */
  /* "release R" = yes */
  doRelease = 1;
  if (backlogDrained == 0)
    goto L119;
  /* "own backlog drained" = yes */
  if (budgetExceeded == 0)
    goto L122;
  /* "recovery reach exhausted" = yes */
L124:;
  if (instanceLive == 0)
    goto L125;
L126:;
  /* "join the oldest owed round" = no */
  /* "maintain the next round" = no */
  /* "own instance live" = yes */
  doJoin = 0;
  doMaintain = 0;
L127:;
  if (maintenanceDue == 0)
    goto L128;
  /* "identity maintenance due" = yes */
L130:;
  if (oldestRetained == 1)
    goto L131;
  /* "R is the oldest retained round" = no */
L133:;
  if (participationOwed == 1)
    goto L134;
  /* "participation owed to any round" = no */
L136:;
  if (priorPossession == SYSTEM_DUTY_HELD)
    goto L137;
L139:;
  if (priorPossession == SYSTEM_DUTY_MET)
    goto L140;
  /* "possession of the prior round" = at n-t, short of all n */
L142:;
  if (roundClass == SYSTEM_ROUND_AHEAD)
    goto L143;
  /* "record participation owed for R" = no */
  doParticipationOwed = 0;
  if (roundClass == SYSTEM_ROUND_LIVE)
    goto L146;
  /* "deliver the act to the live instance" = no */
  doDeliver = 0;
  if (roundClass == SYSTEM_ROUND_RELEASED)
    goto L149;
  /* "round R relative to self" = R COMPLETE and retained */
  goto Ldone;
L149:;
  /* "round R relative to self" = R COMPLETE and released */
  goto Ldone;
L146:;
  /* "deliver the act to the live instance" = yes */
  /* "round R relative to self" = R is the live instance */
  doDeliver = 1;
  goto Ldone;
L143:;
  /* "deliver the act to the live instance" = no */
  /* "record participation owed for R" = yes */
  /* "round R relative to self" = R not yet reached */
  doDeliver = 0;
  doParticipationOwed = 1;
  goto Ldone;
L140:;
  /* "possession of the prior round" = at all n, or not retained */
  goto L142;
L137:;
  /* "possession of the prior round" = short of n-t */
  goto L142;
L134:;
  /* "participation owed to any round" = yes */
  goto L136;
L131:;
  /* "R is the oldest retained round" = yes */
  goto L133;
L128:;
  /* "identity maintenance due" = no */
  goto L130;
L125:;
  /* "own instance live" = no */
  if (maintenanceDue == 0)
    goto L152;
  /* "identity maintenance due" = yes */
L154:;
  if (oldestRetained == 1)
    goto L155;
  /* "R is the oldest retained round" = no */
L157:;
  if (participationOwed == 1)
    goto L158;
  /* "join the oldest owed round" = no */
  /* "participation owed to any round" = no */
  doJoin = 0;
  if (priorPossession == SYSTEM_DUTY_HELD)
    goto L161;
  if (priorPossession == SYSTEM_DUTY_MET)
    goto L164;
  /* "maintain the next round" = no */
  /* "possession of the prior round" = at n-t, short of all n */
  doMaintain = 0;
  goto L142;
L164:;
  /* "maintain the next round" = yes */
  /* "possession of the prior round" = at all n, or not retained */
  doMaintain = 1;
  goto L142;
L161:;
  /* "maintain the next round" = no */
  /* "possession of the prior round" = short of n-t */
  doMaintain = 0;
  goto L142;
L158:;
  /* "maintain the next round" = no */
  /* "participation owed to any round" = yes */
  doMaintain = 0;
L166:;
  if (priorPossession == SYSTEM_DUTY_HELD)
    goto L167;
  if (priorPossession == SYSTEM_DUTY_MET)
    goto L170;
  /* "join the oldest owed round" = no */
  /* "possession of the prior round" = at n-t, short of all n */
  doJoin = 0;
  goto L142;
L170:;
  /* "join the oldest owed round" = yes */
  /* "possession of the prior round" = at all n, or not retained */
  doJoin = 1;
  goto L142;
L167:;
  /* "join the oldest owed round" = no */
  /* "possession of the prior round" = short of n-t */
  doJoin = 0;
  goto L142;
L155:;
  /* "R is the oldest retained round" = yes */
  goto L157;
L152:;
  /* "identity maintenance due" = no */
  /* "maintain the next round" = no */
  doMaintain = 0;
L172:;
  if (oldestRetained == 1)
    goto L173;
  /* "R is the oldest retained round" = no */
L175:;
  if (participationOwed == 1)
    goto L176;
L177:;
  /* "join the oldest owed round" = no */
  /* "participation owed to any round" = no */
  doJoin = 0;
  goto L136;
L176:;
  /* "participation owed to any round" = yes */
  goto L166;
L173:;
  /* "R is the oldest retained round" = yes */
  goto L175;
L122:;
  /* "recovery reach exhausted" = no */
  goto L124;
L119:;
  /* "maintain the next round" = no */
  /* "own backlog drained" = no */
  doMaintain = 0;
L178:;
  if (budgetExceeded == 0)
    goto L179;
  /* "recovery reach exhausted" = yes */
L181:;
  if (instanceLive == 0)
    goto L182;
L183:;
  /* "join the oldest owed round" = no */
  /* "own instance live" = yes */
  doJoin = 0;
  goto L127;
L182:;
  /* "own instance live" = no */
  if (maintenanceDue == 0)
    goto L185;
  /* "identity maintenance due" = yes */
  goto L172;
L185:;
  /* "identity maintenance due" = no */
  goto L172;
L179:;
  /* "recovery reach exhausted" = no */
  goto L181;
L116:;
  /* "all n processes have evidenced possession of R" = no */
  if (backlogDrained == 0)
    goto L188;
  /* "own backlog drained" = yes */
  if (budgetExceeded == 0)
    goto L191;
  /* "recovery reach exhausted" = yes */
  if (instanceLive == 0)
    goto L194;
L195:;
  /* "join the oldest owed round" = no */
  /* "maintain the next round" = no */
  /* "own instance live" = yes */
  doJoin = 0;
  doMaintain = 0;
L196:;
  if (maintenanceDue == 0)
    goto L197;
  /* "identity maintenance due" = yes */
L199:;
  if (oldestRetained == 1)
    goto L200;
  /* "R is the oldest retained round" = no */
  /* "release R" = no */
  doRelease = 0;
  goto L133;
L200:;
  /* "R is the oldest retained round" = yes */
  /* "release R" = yes */
  doRelease = 1;
  goto L133;
L197:;
  /* "identity maintenance due" = no */
  goto L199;
L194:;
  /* "own instance live" = no */
  if (maintenanceDue == 0)
    goto L203;
  /* "identity maintenance due" = yes */
L205:;
  if (oldestRetained == 1)
    goto L206;
  /* "R is the oldest retained round" = no */
  /* "release R" = no */
  doRelease = 0;
  goto L157;
L206:;
  /* "R is the oldest retained round" = yes */
  /* "release R" = yes */
  doRelease = 1;
  goto L157;
L203:;
  /* "identity maintenance due" = no */
  /* "maintain the next round" = no */
  doMaintain = 0;
L208:;
  if (oldestRetained == 1)
    goto L209;
  /* "R is the oldest retained round" = no */
  /* "release R" = no */
  doRelease = 0;
  goto L175;
L209:;
  /* "R is the oldest retained round" = yes */
  /* "release R" = yes */
  doRelease = 1;
  goto L175;
L191:;
  /* "recovery reach exhausted" = no */
  /* "release R" = no */
  doRelease = 0;
  goto L124;
L188:;
  /* "maintain the next round" = no */
  /* "own backlog drained" = no */
  doMaintain = 0;
L211:;
  if (budgetExceeded == 0)
    goto L212;
  /* "recovery reach exhausted" = yes */
  if (instanceLive == 0)
    goto L215;
L216:;
  /* "join the oldest owed round" = no */
  /* "own instance live" = yes */
  doJoin = 0;
  goto L196;
L215:;
  /* "own instance live" = no */
  if (maintenanceDue == 0)
    goto L218;
  /* "identity maintenance due" = yes */
  goto L208;
L218:;
  /* "identity maintenance due" = no */
  goto L208;
L212:;
  /* "recovery reach exhausted" = no */
  /* "release R" = no */
  doRelease = 0;
  goto L181;
L5:;
  /* "tolerance elapsed" = yes */
  if (senderPossesses == 1)
    goto L221;
  /* "sender has evidenced possession of R" = no */
  if (allPossess == 0)
    goto L224;
  /* "all n processes have evidenced possession of R" = yes */
  /* "release R" = yes */
  doRelease = 1;
  if (backlogDrained == 0)
    goto L227;
  /* "own backlog drained" = yes */
  if (budgetExceeded == 0)
    goto L230;
  /* "recovery reach exhausted" = yes */
L232:;
  if (instanceLive == 0)
    goto L233;
  goto L21;
L233:;
  /* "own instance live" = no */
  if (maintenanceDue == 0)
    goto L235;
  /* "identity maintenance due" = yes */
L237:;
  if (oldestRetained == 1)
    goto L238;
  /* "R is the oldest retained round" = no */
L240:;
  if (participationOwed == 1)
    goto L241;
  /* "join the oldest owed round" = no */
  /* "participation owed to any round" = no */
  doJoin = 0;
  if (priorPossession == SYSTEM_DUTY_HELD)
    goto L56;
  /* "maintain the next round" = yes */
  doMaintain = 1;
  goto L34;
L241:;
  /* "maintain the next round" = no */
  /* "participation owed to any round" = yes */
  doMaintain = 0;
L245:;
  if (priorPossession == SYSTEM_DUTY_HELD)
    goto L62;
  /* "join the oldest owed round" = yes */
  doJoin = 1;
  goto L34;
L238:;
  /* "R is the oldest retained round" = yes */
  goto L240;
L235:;
  /* "identity maintenance due" = no */
  /* "maintain the next round" = no */
  doMaintain = 0;
L247:;
  if (oldestRetained == 1)
    goto L248;
  /* "R is the oldest retained round" = no */
L250:;
  if (participationOwed == 1)
    goto L251;
  goto L72;
L251:;
  /* "participation owed to any round" = yes */
  goto L245;
L248:;
  /* "R is the oldest retained round" = yes */
  goto L250;
L230:;
  /* "recovery reach exhausted" = no */
  goto L232;
L227:;
  /* "maintain the next round" = no */
  /* "own backlog drained" = no */
  doMaintain = 0;
L252:;
  if (budgetExceeded == 0)
    goto L253;
  /* "recovery reach exhausted" = yes */
L255:;
  if (instanceLive == 0)
    goto L256;
  goto L78;
L256:;
  /* "own instance live" = no */
  if (maintenanceDue == 0)
    goto L258;
  /* "identity maintenance due" = yes */
  goto L247;
L258:;
  /* "identity maintenance due" = no */
  goto L247;
L253:;
  /* "recovery reach exhausted" = no */
  goto L255;
L224:;
  /* "all n processes have evidenced possession of R" = no */
  if (backlogDrained == 0)
    goto L261;
  /* "own backlog drained" = yes */
  if (budgetExceeded == 0)
    goto L264;
  /* "recovery reach exhausted" = yes */
  if (instanceLive == 0)
    goto L267;
  goto L90;
L267:;
  /* "own instance live" = no */
  if (maintenanceDue == 0)
    goto L269;
  /* "identity maintenance due" = yes */
L271:;
  if (oldestRetained == 1)
    goto L272;
  /* "R is the oldest retained round" = no */
  /* "release R" = no */
  doRelease = 0;
  goto L240;
L272:;
  /* "R is the oldest retained round" = yes */
  /* "release R" = yes */
  doRelease = 1;
  goto L240;
L269:;
  /* "identity maintenance due" = no */
  /* "maintain the next round" = no */
  doMaintain = 0;
L274:;
  if (oldestRetained == 1)
    goto L275;
  /* "R is the oldest retained round" = no */
  /* "release R" = no */
  doRelease = 0;
  goto L250;
L275:;
  /* "R is the oldest retained round" = yes */
  /* "release R" = yes */
  doRelease = 1;
  goto L250;
L264:;
  /* "recovery reach exhausted" = no */
  /* "release R" = no */
  doRelease = 0;
  goto L232;
L261:;
  /* "maintain the next round" = no */
  /* "own backlog drained" = no */
  doMaintain = 0;
L277:;
  if (budgetExceeded == 0)
    goto L278;
  /* "recovery reach exhausted" = yes */
  if (instanceLive == 0)
    goto L281;
  goto L111;
L281:;
  /* "own instance live" = no */
  if (maintenanceDue == 0)
    goto L283;
  /* "identity maintenance due" = yes */
  goto L274;
L283:;
  /* "identity maintenance due" = no */
  goto L274;
L278:;
  /* "recovery reach exhausted" = no */
  /* "release R" = no */
  doRelease = 0;
  goto L255;
L221:;
  /* "record serve owed to the sender for R" = no */
  /* "sender has evidenced possession of R" = yes */
  doServeOwed = 0;
  if (allPossess == 0)
    goto L286;
  /* "all n processes have evidenced possession of R" = yes */
  /* "release R" = yes */
  doRelease = 1;
  if (backlogDrained == 0)
    goto L289;
  /* "own backlog drained" = yes */
  if (budgetExceeded == 0)
    goto L292;
  /* "recovery reach exhausted" = yes */
L294:;
  if (instanceLive == 0)
    goto L295;
  goto L126;
L295:;
  /* "own instance live" = no */
  if (maintenanceDue == 0)
    goto L297;
  /* "identity maintenance due" = yes */
L299:;
  if (oldestRetained == 1)
    goto L300;
  /* "R is the oldest retained round" = no */
L302:;
  if (participationOwed == 1)
    goto L303;
  /* "join the oldest owed round" = no */
  /* "participation owed to any round" = no */
  doJoin = 0;
  if (priorPossession == SYSTEM_DUTY_HELD)
    goto L161;
  /* "maintain the next round" = yes */
  doMaintain = 1;
  goto L139;
L303:;
  /* "maintain the next round" = no */
  /* "participation owed to any round" = yes */
  doMaintain = 0;
L307:;
  if (priorPossession == SYSTEM_DUTY_HELD)
    goto L167;
  /* "join the oldest owed round" = yes */
  doJoin = 1;
  goto L139;
L300:;
  /* "R is the oldest retained round" = yes */
  goto L302;
L297:;
  /* "identity maintenance due" = no */
  /* "maintain the next round" = no */
  doMaintain = 0;
L309:;
  if (oldestRetained == 1)
    goto L310;
  /* "R is the oldest retained round" = no */
L312:;
  if (participationOwed == 1)
    goto L313;
  goto L177;
L313:;
  /* "participation owed to any round" = yes */
  goto L307;
L310:;
  /* "R is the oldest retained round" = yes */
  goto L312;
L292:;
  /* "recovery reach exhausted" = no */
  goto L294;
L289:;
  /* "maintain the next round" = no */
  /* "own backlog drained" = no */
  doMaintain = 0;
L314:;
  if (budgetExceeded == 0)
    goto L315;
  /* "recovery reach exhausted" = yes */
L317:;
  if (instanceLive == 0)
    goto L318;
  goto L183;
L318:;
  /* "own instance live" = no */
  if (maintenanceDue == 0)
    goto L320;
  /* "identity maintenance due" = yes */
  goto L309;
L320:;
  /* "identity maintenance due" = no */
  goto L309;
L315:;
  /* "recovery reach exhausted" = no */
  goto L317;
L286:;
  /* "all n processes have evidenced possession of R" = no */
  if (backlogDrained == 0)
    goto L323;
  /* "own backlog drained" = yes */
  if (budgetExceeded == 0)
    goto L326;
  /* "recovery reach exhausted" = yes */
  if (instanceLive == 0)
    goto L329;
  goto L195;
L329:;
  /* "own instance live" = no */
  if (maintenanceDue == 0)
    goto L331;
  /* "identity maintenance due" = yes */
L333:;
  if (oldestRetained == 1)
    goto L334;
  /* "R is the oldest retained round" = no */
  /* "release R" = no */
  doRelease = 0;
  goto L302;
L334:;
  /* "R is the oldest retained round" = yes */
  /* "release R" = yes */
  doRelease = 1;
  goto L302;
L331:;
  /* "identity maintenance due" = no */
  /* "maintain the next round" = no */
  doMaintain = 0;
L336:;
  if (oldestRetained == 1)
    goto L337;
  /* "R is the oldest retained round" = no */
  /* "release R" = no */
  doRelease = 0;
  goto L312;
L337:;
  /* "R is the oldest retained round" = yes */
  /* "release R" = yes */
  doRelease = 1;
  goto L312;
L326:;
  /* "recovery reach exhausted" = no */
  /* "release R" = no */
  doRelease = 0;
  goto L294;
L323:;
  /* "maintain the next round" = no */
  /* "own backlog drained" = no */
  doMaintain = 0;
L339:;
  if (budgetExceeded == 0)
    goto L340;
  /* "recovery reach exhausted" = yes */
  if (instanceLive == 0)
    goto L343;
  goto L216;
L343:;
  /* "own instance live" = no */
  if (maintenanceDue == 0)
    goto L345;
  /* "identity maintenance due" = yes */
  goto L336;
L345:;
  /* "identity maintenance due" = no */
  goto L336;
L340:;
  /* "recovery reach exhausted" = no */
  /* "release R" = no */
  doRelease = 0;
  goto L317;
L2:;
  /* "application value pending" = yes */
  if (toleranceElapsed == 1)
    goto L348;
  /* "tolerance elapsed" = no */
  if (senderPossesses == 1)
    goto L351;
  /* "sender has evidenced possession of R" = no */
  if (allPossess == 0)
    goto L354;
  /* "all n processes have evidenced possession of R" = yes */
  /* "release R" = yes */
  doRelease = 1;
  if (backlogDrained == 0)
    goto L357;
  /* "own backlog drained" = yes */
  if (budgetExceeded == 0)
    goto L360;
  /* "recovery reach exhausted" = yes */
L362:;
  if (instanceLive == 0)
    goto L363;
L364:;
  /* "admit the next round" = no */
  /* "join the oldest owed round" = no */
  /* "maintain the next round" = no */
  /* "own instance live" = yes */
  doAdmit = 0;
  doJoin = 0;
  doMaintain = 0;
  goto L22;
L363:;
  /* "own instance live" = no */
  if (maintenanceDue == 0)
    goto L366;
  /* "admit the next round" = no */
  /* "identity maintenance due" = yes */
  doAdmit = 0;
  goto L49;
L366:;
  /* "identity maintenance due" = no */
  /* "maintain the next round" = no */
  doMaintain = 0;
  if (oldestRetained == 1)
    goto L369;
  /* "R is the oldest retained round" = no */
L371:;
  if (participationOwed == 1)
    goto L372;
  /* "join the oldest owed round" = no */
  /* "participation owed to any round" = no */
  doJoin = 0;
  if (priorPossession == SYSTEM_DUTY_HELD)
    goto L375;
  if (priorPossession == SYSTEM_DUTY_MET)
    goto L378;
  /* "admit the next round" = no */
  /* "possession of the prior round" = at n-t, short of all n */
  doAdmit = 0;
  goto L37;
L378:;
  /* "admit the next round" = yes */
  /* "possession of the prior round" = at all n, or not retained */
  doAdmit = 1;
  goto L37;
L375:;
  /* "admit the next round" = no */
  /* "possession of the prior round" = short of n-t */
  doAdmit = 0;
  goto L37;
L372:;
  /* "admit the next round" = no */
  /* "participation owed to any round" = yes */
  doAdmit = 0;
  goto L61;
L369:;
  /* "R is the oldest retained round" = yes */
  goto L371;
L360:;
  /* "recovery reach exhausted" = no */
  goto L362;
L357:;
  /* "admit the next round" = no */
  /* "maintain the next round" = no */
  /* "own backlog drained" = no */
  doAdmit = 0;
  doMaintain = 0;
  goto L73;
L354:;
  /* "all n processes have evidenced possession of R" = no */
  if (backlogDrained == 0)
    goto L381;
  /* "own backlog drained" = yes */
  if (budgetExceeded == 0)
    goto L384;
  /* "recovery reach exhausted" = yes */
  if (instanceLive == 0)
    goto L387;
L388:;
  /* "admit the next round" = no */
  /* "join the oldest owed round" = no */
  /* "maintain the next round" = no */
  /* "own instance live" = yes */
  doAdmit = 0;
  doJoin = 0;
  doMaintain = 0;
  goto L91;
L387:;
  /* "own instance live" = no */
  if (maintenanceDue == 0)
    goto L390;
  /* "admit the next round" = no */
  /* "identity maintenance due" = yes */
  doAdmit = 0;
  goto L100;
L390:;
  /* "identity maintenance due" = no */
  /* "maintain the next round" = no */
  doMaintain = 0;
  if (oldestRetained == 1)
    goto L393;
  /* "R is the oldest retained round" = no */
  /* "release R" = no */
  doRelease = 0;
  goto L371;
L393:;
  /* "R is the oldest retained round" = yes */
  /* "release R" = yes */
  doRelease = 1;
  goto L371;
L384:;
  /* "recovery reach exhausted" = no */
  /* "release R" = no */
  doRelease = 0;
  goto L362;
L381:;
  /* "admit the next round" = no */
  /* "maintain the next round" = no */
  /* "own backlog drained" = no */
  doAdmit = 0;
  doMaintain = 0;
  goto L106;
L351:;
  /* "record serve owed to the sender for R" = no */
  /* "sender has evidenced possession of R" = yes */
  doServeOwed = 0;
  if (allPossess == 0)
    goto L396;
  /* "all n processes have evidenced possession of R" = yes */
  /* "release R" = yes */
  doRelease = 1;
  if (backlogDrained == 0)
    goto L399;
  /* "own backlog drained" = yes */
  if (budgetExceeded == 0)
    goto L402;
  /* "recovery reach exhausted" = yes */
L404:;
  if (instanceLive == 0)
    goto L405;
L406:;
  /* "admit the next round" = no */
  /* "join the oldest owed round" = no */
  /* "maintain the next round" = no */
  /* "own instance live" = yes */
  doAdmit = 0;
  doJoin = 0;
  doMaintain = 0;
  goto L127;
L405:;
  /* "own instance live" = no */
  if (maintenanceDue == 0)
    goto L408;
  /* "admit the next round" = no */
  /* "identity maintenance due" = yes */
  doAdmit = 0;
  goto L154;
L408:;
  /* "identity maintenance due" = no */
  /* "maintain the next round" = no */
  doMaintain = 0;
  if (oldestRetained == 1)
    goto L411;
  /* "R is the oldest retained round" = no */
L413:;
  if (participationOwed == 1)
    goto L414;
  /* "join the oldest owed round" = no */
  /* "participation owed to any round" = no */
  doJoin = 0;
  if (priorPossession == SYSTEM_DUTY_HELD)
    goto L417;
  if (priorPossession == SYSTEM_DUTY_MET)
    goto L420;
  /* "admit the next round" = no */
  /* "possession of the prior round" = at n-t, short of all n */
  doAdmit = 0;
  goto L142;
L420:;
  /* "admit the next round" = yes */
  /* "possession of the prior round" = at all n, or not retained */
  doAdmit = 1;
  goto L142;
L417:;
  /* "admit the next round" = no */
  /* "possession of the prior round" = short of n-t */
  doAdmit = 0;
  goto L142;
L414:;
  /* "admit the next round" = no */
  /* "participation owed to any round" = yes */
  doAdmit = 0;
  goto L166;
L411:;
  /* "R is the oldest retained round" = yes */
  goto L413;
L402:;
  /* "recovery reach exhausted" = no */
  goto L404;
L399:;
  /* "admit the next round" = no */
  /* "maintain the next round" = no */
  /* "own backlog drained" = no */
  doAdmit = 0;
  doMaintain = 0;
  goto L178;
L396:;
  /* "all n processes have evidenced possession of R" = no */
  if (backlogDrained == 0)
    goto L423;
  /* "own backlog drained" = yes */
  if (budgetExceeded == 0)
    goto L426;
  /* "recovery reach exhausted" = yes */
  if (instanceLive == 0)
    goto L429;
L430:;
  /* "admit the next round" = no */
  /* "join the oldest owed round" = no */
  /* "maintain the next round" = no */
  /* "own instance live" = yes */
  doAdmit = 0;
  doJoin = 0;
  doMaintain = 0;
  goto L196;
L429:;
  /* "own instance live" = no */
  if (maintenanceDue == 0)
    goto L432;
  /* "admit the next round" = no */
  /* "identity maintenance due" = yes */
  doAdmit = 0;
  goto L205;
L432:;
  /* "identity maintenance due" = no */
  /* "maintain the next round" = no */
  doMaintain = 0;
  if (oldestRetained == 1)
    goto L435;
  /* "R is the oldest retained round" = no */
  /* "release R" = no */
  doRelease = 0;
  goto L413;
L435:;
  /* "R is the oldest retained round" = yes */
  /* "release R" = yes */
  doRelease = 1;
  goto L413;
L426:;
  /* "recovery reach exhausted" = no */
  /* "release R" = no */
  doRelease = 0;
  goto L404;
L423:;
  /* "admit the next round" = no */
  /* "maintain the next round" = no */
  /* "own backlog drained" = no */
  doAdmit = 0;
  doMaintain = 0;
  goto L211;
L348:;
  /* "tolerance elapsed" = yes */
  if (senderPossesses == 1)
    goto L438;
  /* "sender has evidenced possession of R" = no */
  if (allPossess == 0)
    goto L441;
  /* "all n processes have evidenced possession of R" = yes */
  /* "release R" = yes */
  doRelease = 1;
  if (backlogDrained == 0)
    goto L444;
  /* "own backlog drained" = yes */
  if (budgetExceeded == 0)
    goto L447;
  /* "recovery reach exhausted" = yes */
L449:;
  if (instanceLive == 0)
    goto L450;
  goto L364;
L450:;
  /* "own instance live" = no */
  if (maintenanceDue == 0)
    goto L452;
  /* "admit the next round" = no */
  /* "identity maintenance due" = yes */
  doAdmit = 0;
  goto L237;
L452:;
  /* "identity maintenance due" = no */
  /* "maintain the next round" = no */
  doMaintain = 0;
  if (oldestRetained == 1)
    goto L455;
  /* "R is the oldest retained round" = no */
L457:;
  if (participationOwed == 1)
    goto L458;
  /* "join the oldest owed round" = no */
  /* "participation owed to any round" = no */
  doJoin = 0;
  if (priorPossession == SYSTEM_DUTY_HELD)
    goto L375;
  /* "admit the next round" = yes */
  doAdmit = 1;
  goto L34;
L458:;
  /* "admit the next round" = no */
  /* "participation owed to any round" = yes */
  doAdmit = 0;
  goto L245;
L455:;
  /* "R is the oldest retained round" = yes */
  goto L457;
L447:;
  /* "recovery reach exhausted" = no */
  goto L449;
L444:;
  /* "admit the next round" = no */
  /* "maintain the next round" = no */
  /* "own backlog drained" = no */
  doAdmit = 0;
  doMaintain = 0;
  goto L252;
L441:;
  /* "all n processes have evidenced possession of R" = no */
  if (backlogDrained == 0)
    goto L463;
  /* "own backlog drained" = yes */
  if (budgetExceeded == 0)
    goto L466;
  /* "recovery reach exhausted" = yes */
  if (instanceLive == 0)
    goto L469;
  goto L388;
L469:;
  /* "own instance live" = no */
  if (maintenanceDue == 0)
    goto L471;
  /* "admit the next round" = no */
  /* "identity maintenance due" = yes */
  doAdmit = 0;
  goto L271;
L471:;
  /* "identity maintenance due" = no */
  /* "maintain the next round" = no */
  doMaintain = 0;
  if (oldestRetained == 1)
    goto L474;
  /* "R is the oldest retained round" = no */
  /* "release R" = no */
  doRelease = 0;
  goto L457;
L474:;
  /* "R is the oldest retained round" = yes */
  /* "release R" = yes */
  doRelease = 1;
  goto L457;
L466:;
  /* "recovery reach exhausted" = no */
  /* "release R" = no */
  doRelease = 0;
  goto L449;
L463:;
  /* "admit the next round" = no */
  /* "maintain the next round" = no */
  /* "own backlog drained" = no */
  doAdmit = 0;
  doMaintain = 0;
  goto L277;
L438:;
  /* "record serve owed to the sender for R" = no */
  /* "sender has evidenced possession of R" = yes */
  doServeOwed = 0;
  if (allPossess == 0)
    goto L477;
  /* "all n processes have evidenced possession of R" = yes */
  /* "release R" = yes */
  doRelease = 1;
  if (backlogDrained == 0)
    goto L480;
  /* "own backlog drained" = yes */
  if (budgetExceeded == 0)
    goto L483;
  /* "recovery reach exhausted" = yes */
L485:;
  if (instanceLive == 0)
    goto L486;
  goto L406;
L486:;
  /* "own instance live" = no */
  if (maintenanceDue == 0)
    goto L488;
  /* "admit the next round" = no */
  /* "identity maintenance due" = yes */
  doAdmit = 0;
  goto L299;
L488:;
  /* "identity maintenance due" = no */
  /* "maintain the next round" = no */
  doMaintain = 0;
  if (oldestRetained == 1)
    goto L491;
  /* "R is the oldest retained round" = no */
L493:;
  if (participationOwed == 1)
    goto L494;
  /* "join the oldest owed round" = no */
  /* "participation owed to any round" = no */
  doJoin = 0;
  if (priorPossession == SYSTEM_DUTY_HELD)
    goto L417;
  /* "admit the next round" = yes */
  doAdmit = 1;
  goto L139;
L494:;
  /* "admit the next round" = no */
  /* "participation owed to any round" = yes */
  doAdmit = 0;
  goto L307;
L491:;
  /* "R is the oldest retained round" = yes */
  goto L493;
L483:;
  /* "recovery reach exhausted" = no */
  goto L485;
L480:;
  /* "admit the next round" = no */
  /* "maintain the next round" = no */
  /* "own backlog drained" = no */
  doAdmit = 0;
  doMaintain = 0;
  goto L314;
L477:;
  /* "all n processes have evidenced possession of R" = no */
  if (backlogDrained == 0)
    goto L499;
  /* "own backlog drained" = yes */
  if (budgetExceeded == 0)
    goto L502;
  /* "recovery reach exhausted" = yes */
  if (instanceLive == 0)
    goto L505;
  goto L430;
L505:;
  /* "own instance live" = no */
  if (maintenanceDue == 0)
    goto L507;
  /* "admit the next round" = no */
  /* "identity maintenance due" = yes */
  doAdmit = 0;
  goto L333;
L507:;
  /* "identity maintenance due" = no */
  /* "maintain the next round" = no */
  doMaintain = 0;
  if (oldestRetained == 1)
    goto L510;
  /* "R is the oldest retained round" = no */
  /* "release R" = no */
  doRelease = 0;
  goto L493;
L510:;
  /* "R is the oldest retained round" = yes */
  /* "release R" = yes */
  doRelease = 1;
  goto L493;
L502:;
  /* "recovery reach exhausted" = no */
  /* "release R" = no */
  doRelease = 0;
  goto L485;
L499:;
  /* "admit the next round" = no */
  /* "maintain the next round" = no */
  /* "own backlog drained" = no */
  doAdmit = 0;
  doMaintain = 0;
  goto L339;
Ldone:;
